/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_model_mpcc_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[27] = {9, 3, 0, 7, 14, 21, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 7, 0, 1, 2, 3, 4, 5, 8};
static const casadi_int casadi_s1[33] = {3, 9, 0, 3, 6, 9, 12, 15, 18, 19, 20, 21, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[87] = {9, 9, 0, 9, 18, 27, 36, 45, 54, 61, 68, 75, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 7, 0, 1, 2, 3, 4, 5, 8};
static const casadi_int casadi_s3[93] = {9, 9, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s4[30] = {9, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3};
static const casadi_int casadi_s5[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s8[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s9[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s10[10] = {9, 1, 0, 6, 2, 3, 5, 6, 7, 8};
static const casadi_int casadi_s11[49] = {45, 1, 0, 45, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44};

static const casadi_real casadi_c0[21] = {0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.};

/* unicycle_model_mpcc_expl_ode_hess:(i0[6],i1[6x6],i2[6x3],i3[6],i4[3],i5[46])->(o0[9x1,6nz],o1[45]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, *w3=w+12, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+28, *w15=w+109, *w16=w+145, *w17=w+163, *w18=w+217, *w19=w+271, *w20=w+292, *w21=w+313, *w24=w+388, *w25=w+463, *w26=w+472, *w27=w+481, *w28=w+490, *w29=w+499, *w30=w+508, *w31=w+517, *w32=w+524, *w33=w+531, *w39=w+538, w40, *w41=w+541, *w42=w+543, *w43=w+545, *w44=w+547, *w45=w+549, *w46=w+551, *w47=w+553, *w48=w+555;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[3][0] */
  casadi_copy(arg[3], 6, w3);
  /* #4: {@4, @5, @6, @7, @8, @9} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  /* #5: @10 = (@2*@5) */
  w10  = (w2*w5);
  /* #6: @11 = (@1*@10) */
  w11  = (w1*w10);
  /* #7: @12 = sin(@0) */
  w12 = sin( w0 );
  /* #8: @2 = (@2*@4) */
  w2 *= w4;
  /* #9: @13 = (@12*@2) */
  w13  = (w12*w2);
  /* #10: @11 = (@11-@13) */
  w11 -= w13;
  /* #11: output[0][0] = @11 */
  if (res[0]) res[0][0] = w11;
  /* #12: @11 = sin(@0) */
  w11 = sin( w0 );
  /* #13: @11 = (@11*@5) */
  w11 *= w5;
  /* #14: @13 = cos(@0) */
  w13 = cos( w0 );
  /* #15: @13 = (@13*@4) */
  w13 *= w4;
  /* #16: @11 = (@11+@13) */
  w11 += w13;
  /* #17: output[0][1] = @11 */
  if (res[0]) res[0][1] = w11;
  /* #18: output[0][2] = @8 */
  if (res[0]) res[0][2] = w8;
  /* #19: output[0][3] = @7 */
  if (res[0]) res[0][3] = w7;
  /* #20: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #21: output[0][5] = @9 */
  if (res[0]) res[0][5] = w9;
  /* #22: @14 = zeros(9x9) */
  casadi_clear(w14, 81);
  /* #23: @15 = input[1][0] */
  casadi_copy(arg[1], 36, w15);
  /* #24: @16 = input[2][0] */
  casadi_copy(arg[2], 18, w16);
  /* #25: @17 = horzcat(@15, @16) */
  rr=w17;
  for (i=0, cs=w15; i<36; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<18; ++i) *rr++ = *cs++;
  /* #26: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<9; ++i) for (j=0; j<6; ++j) rr[i+j*9] = *cs++;
  /* #27: @19 = 
  [[0, 0, 0, 0, 0, 0, 1, 00, 00], 
   [0, 0, 0, 0, 0, 0, 00, 1, 00], 
   [0, 0, 0, 0, 0, 0, 00, 00, 1]] */
  casadi_copy(casadi_c0, 21, w19);
  /* #28: @20 = @19' */
  casadi_trans(w19,casadi_s1, w20, casadi_s0, iw);
  /* #29: @21 = horzcat(@18, @20) */
  rr=w21;
  for (i=0, cs=w18; i<54; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<21; ++i) *rr++ = *cs++;
  /* #30: @22 = 00 */
  /* #31: @23 = 00 */
  /* #32: @24 = @21' */
  casadi_trans(w21,casadi_s2, w24, casadi_s2, iw);
  /* #33: {@25, @26, @27, @28, @29, @30, @31, @32, @33} = horzsplit(@24) */
  casadi_copy(w24, 9, w25);
  casadi_copy(w24+9, 9, w26);
  casadi_copy(w24+18, 9, w27);
  casadi_copy(w24+27, 9, w28);
  casadi_copy(w24+36, 9, w29);
  casadi_copy(w24+45, 9, w30);
  casadi_copy(w24+54, 7, w31);
  casadi_copy(w24+61, 7, w32);
  casadi_copy(w24+68, 7, w33);
  /* #34: {NULL, NULL, @9, @6, NULL, NULL, NULL, NULL, NULL} = vertsplit(@25) */
  w9 = w25[2];
  w6 = w25[3];
  /* #35: @7 = (@5*@6) */
  w7  = (w5*w6);
  /* #36: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #37: @8 = sin(@0) */
  w8 = sin( w0 );
  /* #38: @11 = (@8*@9) */
  w11  = (w8*w9);
  /* #39: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #40: @7 = (@7-@11) */
  w7 -= w11;
  /* #41: @11 = cos(@0) */
  w11 = cos( w0 );
  /* #42: @13 = (@11*@9) */
  w13  = (w11*w9);
  /* #43: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #44: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #45: @6 = (@12*@6) */
  w6  = (w12*w6);
  /* #46: @13 = (@13+@6) */
  w13 += w6;
  /* #47: @7 = (@7-@13) */
  w7 -= w13;
  /* #48: @13 = cos(@0) */
  w13 = cos( w0 );
  /* #49: @6 = (@13*@9) */
  w6  = (w13*w9);
  /* #50: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #51: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #52: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #53: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #54: @6 = (@6-@9) */
  w6 -= w9;
  /* #55: @34 = 00 */
  /* #56: @35 = 00 */
  /* #57: @36 = 00 */
  /* #58: @37 = 00 */
  /* #59: @38 = 00 */
  /* #60: @39 = vertcat(@22, @23, @7, @6, @34, @35, @36, @37, @38) */
  rr=w39;
  *rr++ = w7;
  *rr++ = w6;
  /* #61: @22 = 00 */
  /* #62: @23 = 00 */
  /* #63: {NULL, NULL, @7, @6, NULL, NULL, NULL, NULL, NULL} = vertsplit(@26) */
  w7 = w26[2];
  w6 = w26[3];
  /* #64: @9 = (@5*@6) */
  w9  = (w5*w6);
  /* #65: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #66: @40 = (@8*@7) */
  w40  = (w8*w7);
  /* #67: @40 = (@10*@40) */
  w40  = (w10*w40);
  /* #68: @9 = (@9-@40) */
  w9 -= w40;
  /* #69: @40 = (@11*@7) */
  w40  = (w11*w7);
  /* #70: @40 = (@2*@40) */
  w40  = (w2*w40);
  /* #71: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #72: @6 = (@12*@6) */
  w6  = (w12*w6);
  /* #73: @40 = (@40+@6) */
  w40 += w6;
  /* #74: @9 = (@9-@40) */
  w9 -= w40;
  /* #75: @40 = (@13*@7) */
  w40  = (w13*w7);
  /* #76: @40 = (@5*@40) */
  w40  = (w5*w40);
  /* #77: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #78: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #79: @40 = (@40-@7) */
  w40 -= w7;
  /* #80: @34 = 00 */
  /* #81: @35 = 00 */
  /* #82: @36 = 00 */
  /* #83: @37 = 00 */
  /* #84: @38 = 00 */
  /* #85: @41 = vertcat(@22, @23, @9, @40, @34, @35, @36, @37, @38) */
  rr=w41;
  *rr++ = w9;
  *rr++ = w40;
  /* #86: @22 = 00 */
  /* #87: @23 = 00 */
  /* #88: {NULL, NULL, @9, @40, NULL, NULL, NULL, NULL, NULL} = vertsplit(@27) */
  w9 = w27[2];
  w40 = w27[3];
  /* #89: @7 = (@5*@40) */
  w7  = (w5*w40);
  /* #90: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #91: @6 = (@8*@9) */
  w6  = (w8*w9);
  /* #92: @6 = (@10*@6) */
  w6  = (w10*w6);
  /* #93: @7 = (@7-@6) */
  w7 -= w6;
  /* #94: @6 = (@11*@9) */
  w6  = (w11*w9);
  /* #95: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #96: @40 = (@4*@40) */
  w40  = (w4*w40);
  /* #97: @40 = (@12*@40) */
  w40  = (w12*w40);
  /* #98: @6 = (@6+@40) */
  w6 += w40;
  /* #99: @7 = (@7-@6) */
  w7 -= w6;
  /* #100: @6 = (@13*@9) */
  w6  = (w13*w9);
  /* #101: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #102: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #103: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #104: @6 = (@6-@9) */
  w6 -= w9;
  /* #105: @34 = 00 */
  /* #106: @35 = 00 */
  /* #107: @36 = 00 */
  /* #108: @37 = 00 */
  /* #109: @38 = 00 */
  /* #110: @42 = vertcat(@22, @23, @7, @6, @34, @35, @36, @37, @38) */
  rr=w42;
  *rr++ = w7;
  *rr++ = w6;
  /* #111: @22 = 00 */
  /* #112: @23 = 00 */
  /* #113: {NULL, NULL, @7, @6, NULL, NULL, NULL, NULL, NULL} = vertsplit(@28) */
  w7 = w28[2];
  w6 = w28[3];
  /* #114: @9 = (@5*@6) */
  w9  = (w5*w6);
  /* #115: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #116: @40 = (@8*@7) */
  w40  = (w8*w7);
  /* #117: @40 = (@10*@40) */
  w40  = (w10*w40);
  /* #118: @9 = (@9-@40) */
  w9 -= w40;
  /* #119: @40 = (@11*@7) */
  w40  = (w11*w7);
  /* #120: @40 = (@2*@40) */
  w40  = (w2*w40);
  /* #121: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #122: @6 = (@12*@6) */
  w6  = (w12*w6);
  /* #123: @40 = (@40+@6) */
  w40 += w6;
  /* #124: @9 = (@9-@40) */
  w9 -= w40;
  /* #125: @40 = (@13*@7) */
  w40  = (w13*w7);
  /* #126: @40 = (@5*@40) */
  w40  = (w5*w40);
  /* #127: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #128: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #129: @40 = (@40-@7) */
  w40 -= w7;
  /* #130: @34 = 00 */
  /* #131: @35 = 00 */
  /* #132: @36 = 00 */
  /* #133: @37 = 00 */
  /* #134: @38 = 00 */
  /* #135: @43 = vertcat(@22, @23, @9, @40, @34, @35, @36, @37, @38) */
  rr=w43;
  *rr++ = w9;
  *rr++ = w40;
  /* #136: @22 = 00 */
  /* #137: @23 = 00 */
  /* #138: {NULL, NULL, @9, @40, NULL, NULL, NULL, NULL, NULL} = vertsplit(@29) */
  w9 = w29[2];
  w40 = w29[3];
  /* #139: @7 = (@5*@40) */
  w7  = (w5*w40);
  /* #140: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #141: @6 = (@8*@9) */
  w6  = (w8*w9);
  /* #142: @6 = (@10*@6) */
  w6  = (w10*w6);
  /* #143: @7 = (@7-@6) */
  w7 -= w6;
  /* #144: @6 = (@11*@9) */
  w6  = (w11*w9);
  /* #145: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #146: @40 = (@4*@40) */
  w40  = (w4*w40);
  /* #147: @40 = (@12*@40) */
  w40  = (w12*w40);
  /* #148: @6 = (@6+@40) */
  w6 += w40;
  /* #149: @7 = (@7-@6) */
  w7 -= w6;
  /* #150: @6 = (@13*@9) */
  w6  = (w13*w9);
  /* #151: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #152: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #153: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #154: @6 = (@6-@9) */
  w6 -= w9;
  /* #155: @34 = 00 */
  /* #156: @35 = 00 */
  /* #157: @36 = 00 */
  /* #158: @37 = 00 */
  /* #159: @38 = 00 */
  /* #160: @44 = vertcat(@22, @23, @7, @6, @34, @35, @36, @37, @38) */
  rr=w44;
  *rr++ = w7;
  *rr++ = w6;
  /* #161: @22 = 00 */
  /* #162: @23 = 00 */
  /* #163: {NULL, NULL, @7, @6, NULL, NULL, NULL, NULL, NULL} = vertsplit(@30) */
  w7 = w30[2];
  w6 = w30[3];
  /* #164: @9 = (@5*@6) */
  w9  = (w5*w6);
  /* #165: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #166: @40 = (@8*@7) */
  w40  = (w8*w7);
  /* #167: @40 = (@10*@40) */
  w40  = (w10*w40);
  /* #168: @9 = (@9-@40) */
  w9 -= w40;
  /* #169: @40 = (@11*@7) */
  w40  = (w11*w7);
  /* #170: @40 = (@2*@40) */
  w40  = (w2*w40);
  /* #171: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #172: @6 = (@12*@6) */
  w6  = (w12*w6);
  /* #173: @40 = (@40+@6) */
  w40 += w6;
  /* #174: @9 = (@9-@40) */
  w9 -= w40;
  /* #175: @40 = (@13*@7) */
  w40  = (w13*w7);
  /* #176: @40 = (@5*@40) */
  w40  = (w5*w40);
  /* #177: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #178: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #179: @40 = (@40-@7) */
  w40 -= w7;
  /* #180: @34 = 00 */
  /* #181: @35 = 00 */
  /* #182: @36 = 00 */
  /* #183: @37 = 00 */
  /* #184: @38 = 00 */
  /* #185: @45 = vertcat(@22, @23, @9, @40, @34, @35, @36, @37, @38) */
  rr=w45;
  *rr++ = w9;
  *rr++ = w40;
  /* #186: @22 = 00 */
  /* #187: @23 = 00 */
  /* #188: {NULL, NULL, @9, @40, NULL, NULL, NULL, NULL, NULL} = vertsplit(@31) */
  w9 = w31[2];
  w40 = w31[3];
  /* #189: @7 = (@5*@40) */
  w7  = (w5*w40);
  /* #190: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #191: @6 = (@8*@9) */
  w6  = (w8*w9);
  /* #192: @6 = (@10*@6) */
  w6  = (w10*w6);
  /* #193: @7 = (@7-@6) */
  w7 -= w6;
  /* #194: @6 = (@11*@9) */
  w6  = (w11*w9);
  /* #195: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #196: @40 = (@4*@40) */
  w40  = (w4*w40);
  /* #197: @40 = (@12*@40) */
  w40  = (w12*w40);
  /* #198: @6 = (@6+@40) */
  w6 += w40;
  /* #199: @7 = (@7-@6) */
  w7 -= w6;
  /* #200: @6 = (@13*@9) */
  w6  = (w13*w9);
  /* #201: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #202: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #203: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #204: @6 = (@6-@9) */
  w6 -= w9;
  /* #205: @34 = 00 */
  /* #206: @35 = 00 */
  /* #207: @36 = 00 */
  /* #208: @37 = 00 */
  /* #209: @38 = 00 */
  /* #210: @46 = vertcat(@22, @23, @7, @6, @34, @35, @36, @37, @38) */
  rr=w46;
  *rr++ = w7;
  *rr++ = w6;
  /* #211: @22 = 00 */
  /* #212: @23 = 00 */
  /* #213: {NULL, NULL, @7, @6, NULL, NULL, NULL, NULL, NULL} = vertsplit(@32) */
  w7 = w32[2];
  w6 = w32[3];
  /* #214: @9 = (@5*@6) */
  w9  = (w5*w6);
  /* #215: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #216: @40 = (@8*@7) */
  w40  = (w8*w7);
  /* #217: @40 = (@10*@40) */
  w40  = (w10*w40);
  /* #218: @9 = (@9-@40) */
  w9 -= w40;
  /* #219: @40 = (@11*@7) */
  w40  = (w11*w7);
  /* #220: @40 = (@2*@40) */
  w40  = (w2*w40);
  /* #221: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #222: @6 = (@12*@6) */
  w6  = (w12*w6);
  /* #223: @40 = (@40+@6) */
  w40 += w6;
  /* #224: @9 = (@9-@40) */
  w9 -= w40;
  /* #225: @40 = (@13*@7) */
  w40  = (w13*w7);
  /* #226: @40 = (@5*@40) */
  w40  = (w5*w40);
  /* #227: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #228: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #229: @40 = (@40-@7) */
  w40 -= w7;
  /* #230: @34 = 00 */
  /* #231: @35 = 00 */
  /* #232: @36 = 00 */
  /* #233: @37 = 00 */
  /* #234: @38 = 00 */
  /* #235: @47 = vertcat(@22, @23, @9, @40, @34, @35, @36, @37, @38) */
  rr=w47;
  *rr++ = w9;
  *rr++ = w40;
  /* #236: @22 = 00 */
  /* #237: @23 = 00 */
  /* #238: {NULL, NULL, @9, @40, NULL, NULL, NULL, NULL, NULL} = vertsplit(@33) */
  w9 = w33[2];
  w40 = w33[3];
  /* #239: @7 = (@5*@40) */
  w7  = (w5*w40);
  /* #240: @1 = (@1*@7) */
  w1 *= w7;
  /* #241: @8 = (@8*@9) */
  w8 *= w9;
  /* #242: @10 = (@10*@8) */
  w10 *= w8;
  /* #243: @1 = (@1-@10) */
  w1 -= w10;
  /* #244: @11 = (@11*@9) */
  w11 *= w9;
  /* #245: @2 = (@2*@11) */
  w2 *= w11;
  /* #246: @40 = (@4*@40) */
  w40  = (w4*w40);
  /* #247: @12 = (@12*@40) */
  w12 *= w40;
  /* #248: @2 = (@2+@12) */
  w2 += w12;
  /* #249: @1 = (@1-@2) */
  w1 -= w2;
  /* #250: @13 = (@13*@9) */
  w13 *= w9;
  /* #251: @5 = (@5*@13) */
  w5 *= w13;
  /* #252: @0 = (@0*@9) */
  w0 *= w9;
  /* #253: @4 = (@4*@0) */
  w4 *= w0;
  /* #254: @5 = (@5-@4) */
  w5 -= w4;
  /* #255: @34 = 00 */
  /* #256: @35 = 00 */
  /* #257: @36 = 00 */
  /* #258: @37 = 00 */
  /* #259: @38 = 00 */
  /* #260: @48 = vertcat(@22, @23, @1, @5, @34, @35, @36, @37, @38) */
  rr=w48;
  *rr++ = w1;
  *rr++ = w5;
  /* #261: @16 = horzcat(@39, @41, @42, @43, @44, @45, @46, @47, @48) */
  rr=w16;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<2; ++i) *rr++ = *cs++;
  /* #262: @14 = mac(@21,@16,@14) */
  casadi_mtimes(w21, casadi_s2, w16, casadi_s4, w14, casadi_s3, w, 0);
  /* #263: @1 = @14[0] */
  for (rr=(&w1), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #264: output[1][0] = @1 */
  if (res[1]) res[1][0] = w1;
  /* #265: @1 = @14[1] */
  for (rr=(&w1), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #266: output[1][1] = @1 */
  if (res[1]) res[1][1] = w1;
  /* #267: @1 = @14[2] */
  for (rr=(&w1), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #268: output[1][2] = @1 */
  if (res[1]) res[1][2] = w1;
  /* #269: @1 = @14[3] */
  for (rr=(&w1), ss=w14+3; ss!=w14+4; ss+=1) *rr++ = *ss;
  /* #270: output[1][3] = @1 */
  if (res[1]) res[1][3] = w1;
  /* #271: @1 = @14[4] */
  for (rr=(&w1), ss=w14+4; ss!=w14+5; ss+=1) *rr++ = *ss;
  /* #272: output[1][4] = @1 */
  if (res[1]) res[1][4] = w1;
  /* #273: @1 = @14[5] */
  for (rr=(&w1), ss=w14+5; ss!=w14+6; ss+=1) *rr++ = *ss;
  /* #274: output[1][5] = @1 */
  if (res[1]) res[1][5] = w1;
  /* #275: @1 = @14[6] */
  for (rr=(&w1), ss=w14+6; ss!=w14+7; ss+=1) *rr++ = *ss;
  /* #276: output[1][6] = @1 */
  if (res[1]) res[1][6] = w1;
  /* #277: @1 = @14[7] */
  for (rr=(&w1), ss=w14+7; ss!=w14+8; ss+=1) *rr++ = *ss;
  /* #278: output[1][7] = @1 */
  if (res[1]) res[1][7] = w1;
  /* #279: @1 = @14[8] */
  for (rr=(&w1), ss=w14+8; ss!=w14+9; ss+=1) *rr++ = *ss;
  /* #280: output[1][8] = @1 */
  if (res[1]) res[1][8] = w1;
  /* #281: @1 = @14[10] */
  for (rr=(&w1), ss=w14+10; ss!=w14+11; ss+=1) *rr++ = *ss;
  /* #282: output[1][9] = @1 */
  if (res[1]) res[1][9] = w1;
  /* #283: @1 = @14[11] */
  for (rr=(&w1), ss=w14+11; ss!=w14+12; ss+=1) *rr++ = *ss;
  /* #284: output[1][10] = @1 */
  if (res[1]) res[1][10] = w1;
  /* #285: @1 = @14[12] */
  for (rr=(&w1), ss=w14+12; ss!=w14+13; ss+=1) *rr++ = *ss;
  /* #286: output[1][11] = @1 */
  if (res[1]) res[1][11] = w1;
  /* #287: @1 = @14[13] */
  for (rr=(&w1), ss=w14+13; ss!=w14+14; ss+=1) *rr++ = *ss;
  /* #288: output[1][12] = @1 */
  if (res[1]) res[1][12] = w1;
  /* #289: @1 = @14[14] */
  for (rr=(&w1), ss=w14+14; ss!=w14+15; ss+=1) *rr++ = *ss;
  /* #290: output[1][13] = @1 */
  if (res[1]) res[1][13] = w1;
  /* #291: @1 = @14[15] */
  for (rr=(&w1), ss=w14+15; ss!=w14+16; ss+=1) *rr++ = *ss;
  /* #292: output[1][14] = @1 */
  if (res[1]) res[1][14] = w1;
  /* #293: @1 = @14[16] */
  for (rr=(&w1), ss=w14+16; ss!=w14+17; ss+=1) *rr++ = *ss;
  /* #294: output[1][15] = @1 */
  if (res[1]) res[1][15] = w1;
  /* #295: @1 = @14[17] */
  for (rr=(&w1), ss=w14+17; ss!=w14+18; ss+=1) *rr++ = *ss;
  /* #296: output[1][16] = @1 */
  if (res[1]) res[1][16] = w1;
  /* #297: @1 = @14[20] */
  for (rr=(&w1), ss=w14+20; ss!=w14+21; ss+=1) *rr++ = *ss;
  /* #298: output[1][17] = @1 */
  if (res[1]) res[1][17] = w1;
  /* #299: @1 = @14[21] */
  for (rr=(&w1), ss=w14+21; ss!=w14+22; ss+=1) *rr++ = *ss;
  /* #300: output[1][18] = @1 */
  if (res[1]) res[1][18] = w1;
  /* #301: @1 = @14[22] */
  for (rr=(&w1), ss=w14+22; ss!=w14+23; ss+=1) *rr++ = *ss;
  /* #302: output[1][19] = @1 */
  if (res[1]) res[1][19] = w1;
  /* #303: @1 = @14[23] */
  for (rr=(&w1), ss=w14+23; ss!=w14+24; ss+=1) *rr++ = *ss;
  /* #304: output[1][20] = @1 */
  if (res[1]) res[1][20] = w1;
  /* #305: @1 = @14[24] */
  for (rr=(&w1), ss=w14+24; ss!=w14+25; ss+=1) *rr++ = *ss;
  /* #306: output[1][21] = @1 */
  if (res[1]) res[1][21] = w1;
  /* #307: @1 = @14[25] */
  for (rr=(&w1), ss=w14+25; ss!=w14+26; ss+=1) *rr++ = *ss;
  /* #308: output[1][22] = @1 */
  if (res[1]) res[1][22] = w1;
  /* #309: @1 = @14[26] */
  for (rr=(&w1), ss=w14+26; ss!=w14+27; ss+=1) *rr++ = *ss;
  /* #310: output[1][23] = @1 */
  if (res[1]) res[1][23] = w1;
  /* #311: @1 = @14[30] */
  for (rr=(&w1), ss=w14+30; ss!=w14+31; ss+=1) *rr++ = *ss;
  /* #312: output[1][24] = @1 */
  if (res[1]) res[1][24] = w1;
  /* #313: @1 = @14[31] */
  for (rr=(&w1), ss=w14+31; ss!=w14+32; ss+=1) *rr++ = *ss;
  /* #314: output[1][25] = @1 */
  if (res[1]) res[1][25] = w1;
  /* #315: @1 = @14[32] */
  for (rr=(&w1), ss=w14+32; ss!=w14+33; ss+=1) *rr++ = *ss;
  /* #316: output[1][26] = @1 */
  if (res[1]) res[1][26] = w1;
  /* #317: @1 = @14[33] */
  for (rr=(&w1), ss=w14+33; ss!=w14+34; ss+=1) *rr++ = *ss;
  /* #318: output[1][27] = @1 */
  if (res[1]) res[1][27] = w1;
  /* #319: @1 = @14[34] */
  for (rr=(&w1), ss=w14+34; ss!=w14+35; ss+=1) *rr++ = *ss;
  /* #320: output[1][28] = @1 */
  if (res[1]) res[1][28] = w1;
  /* #321: @1 = @14[35] */
  for (rr=(&w1), ss=w14+35; ss!=w14+36; ss+=1) *rr++ = *ss;
  /* #322: output[1][29] = @1 */
  if (res[1]) res[1][29] = w1;
  /* #323: @1 = @14[40] */
  for (rr=(&w1), ss=w14+40; ss!=w14+41; ss+=1) *rr++ = *ss;
  /* #324: output[1][30] = @1 */
  if (res[1]) res[1][30] = w1;
  /* #325: @1 = @14[41] */
  for (rr=(&w1), ss=w14+41; ss!=w14+42; ss+=1) *rr++ = *ss;
  /* #326: output[1][31] = @1 */
  if (res[1]) res[1][31] = w1;
  /* #327: @1 = @14[42] */
  for (rr=(&w1), ss=w14+42; ss!=w14+43; ss+=1) *rr++ = *ss;
  /* #328: output[1][32] = @1 */
  if (res[1]) res[1][32] = w1;
  /* #329: @1 = @14[43] */
  for (rr=(&w1), ss=w14+43; ss!=w14+44; ss+=1) *rr++ = *ss;
  /* #330: output[1][33] = @1 */
  if (res[1]) res[1][33] = w1;
  /* #331: @1 = @14[44] */
  for (rr=(&w1), ss=w14+44; ss!=w14+45; ss+=1) *rr++ = *ss;
  /* #332: output[1][34] = @1 */
  if (res[1]) res[1][34] = w1;
  /* #333: @1 = @14[50] */
  for (rr=(&w1), ss=w14+50; ss!=w14+51; ss+=1) *rr++ = *ss;
  /* #334: output[1][35] = @1 */
  if (res[1]) res[1][35] = w1;
  /* #335: @1 = @14[51] */
  for (rr=(&w1), ss=w14+51; ss!=w14+52; ss+=1) *rr++ = *ss;
  /* #336: output[1][36] = @1 */
  if (res[1]) res[1][36] = w1;
  /* #337: @1 = @14[52] */
  for (rr=(&w1), ss=w14+52; ss!=w14+53; ss+=1) *rr++ = *ss;
  /* #338: output[1][37] = @1 */
  if (res[1]) res[1][37] = w1;
  /* #339: @1 = @14[53] */
  for (rr=(&w1), ss=w14+53; ss!=w14+54; ss+=1) *rr++ = *ss;
  /* #340: output[1][38] = @1 */
  if (res[1]) res[1][38] = w1;
  /* #341: @1 = @14[60] */
  for (rr=(&w1), ss=w14+60; ss!=w14+61; ss+=1) *rr++ = *ss;
  /* #342: output[1][39] = @1 */
  if (res[1]) res[1][39] = w1;
  /* #343: @1 = @14[61] */
  for (rr=(&w1), ss=w14+61; ss!=w14+62; ss+=1) *rr++ = *ss;
  /* #344: output[1][40] = @1 */
  if (res[1]) res[1][40] = w1;
  /* #345: @1 = @14[62] */
  for (rr=(&w1), ss=w14+62; ss!=w14+63; ss+=1) *rr++ = *ss;
  /* #346: output[1][41] = @1 */
  if (res[1]) res[1][41] = w1;
  /* #347: @1 = @14[70] */
  for (rr=(&w1), ss=w14+70; ss!=w14+71; ss+=1) *rr++ = *ss;
  /* #348: output[1][42] = @1 */
  if (res[1]) res[1][42] = w1;
  /* #349: @1 = @14[71] */
  for (rr=(&w1), ss=w14+71; ss!=w14+72; ss+=1) *rr++ = *ss;
  /* #350: output[1][43] = @1 */
  if (res[1]) res[1][43] = w1;
  /* #351: @1 = @14[80] */
  for (rr=(&w1), ss=w14+80; ss!=w14+81; ss+=1) *rr++ = *ss;
  /* #352: output[1][44] = @1 */
  if (res[1]) res[1][44] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_model_mpcc_expl_ode_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_expl_ode_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_expl_ode_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s5;
    case 4: return casadi_s8;
    case 5: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 10;
  if (sz_w) *sz_w = 557;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
