/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_model_mpcc_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[9] = {6, 3, 0, 1, 2, 3, 3, 2, 5};
static const casadi_int casadi_s1[12] = {3, 6, 0, 0, 0, 1, 2, 2, 3, 1, 0, 2};
static const casadi_int casadi_s2[18] = {6, 3, 0, 4, 8, 12, 0, 1, 3, 4, 0, 1, 2, 4, 0, 1, 4, 5};
static const casadi_int casadi_s3[15] = {6, 3, 0, 3, 6, 9, 0, 1, 4, 0, 1, 4, 0, 1, 4};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s8[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s9[27] = {6, 6, 0, 3, 6, 9, 12, 15, 18, 0, 1, 4, 0, 1, 4, 0, 1, 4, 0, 1, 4, 0, 1, 4, 0, 1, 4};

/* unicycle_model_mpcc_expl_vde_forw:(i0[6],i1[6x6],i2[6x3],i3[3],i4[46])->(o0[6],o1[6x6,18nz],o2[6x3,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, *w5=w+11, *w6=w+47, *w7=w+53, *w8=w+59, *w9=w+65, *w10=w+71, *w11=w+77, w12, w13, w14, w15, w16, w17, *w18=w+89, *w21=w+92, *w23=w+95, *w24=w+98, *w25=w+110, *w26=w+128, *w27=w+137;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #8: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #9: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #10: @4 = input[3][0] */
  w4 = arg[3] ? arg[3][0] : 0;
  /* #11: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  /* #12: @4 = input[0][5] */
  w4 = arg[0] ? arg[0][5] : 0;
  /* #13: output[0][4] = @4 */
  if (res[0]) res[0][4] = w4;
  /* #14: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #15: output[0][5] = @4 */
  if (res[0]) res[0][5] = w4;
  /* #16: @5 = input[1][0] */
  casadi_copy(arg[1], 36, w5);
  /* #17: {@6, @7, @8, @9, @10, @11} = horzsplit(@5) */
  casadi_copy(w5, 6, w6);
  casadi_copy(w5+6, 6, w7);
  casadi_copy(w5+12, 6, w8);
  casadi_copy(w5+18, 6, w9);
  casadi_copy(w5+24, 6, w10);
  casadi_copy(w5+30, 6, w11);
  /* #18: {NULL, NULL, @4, @12, NULL, @13} = vertsplit(@6) */
  w4 = w6[2];
  w12 = w6[3];
  w13 = w6[5];
  /* #19: @14 = (@2*@12) */
  w14  = (w2*w12);
  /* #20: @15 = sin(@1) */
  w15 = sin( w1 );
  /* #21: @16 = (@15*@4) */
  w16  = (w15*w4);
  /* #22: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #23: @14 = (@14-@16) */
  w14 -= w16;
  /* #24: output[1][0] = @14 */
  if (res[1]) res[1][0] = w14;
  /* #25: @12 = (@3*@12) */
  w12  = (w3*w12);
  /* #26: @14 = cos(@1) */
  w14 = cos( w1 );
  /* #27: @4 = (@14*@4) */
  w4  = (w14*w4);
  /* #28: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #29: @12 = (@12+@4) */
  w12 += w4;
  /* #30: output[1][1] = @12 */
  if (res[1]) res[1][1] = w12;
  /* #31: output[1][2] = @13 */
  if (res[1]) res[1][2] = w13;
  /* #32: {NULL, NULL, @13, @12, NULL, @4} = vertsplit(@7) */
  w13 = w7[2];
  w12 = w7[3];
  w4 = w7[5];
  /* #33: @16 = (@2*@12) */
  w16  = (w2*w12);
  /* #34: @17 = (@15*@13) */
  w17  = (w15*w13);
  /* #35: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #36: @16 = (@16-@17) */
  w16 -= w17;
  /* #37: output[1][3] = @16 */
  if (res[1]) res[1][3] = w16;
  /* #38: @12 = (@3*@12) */
  w12  = (w3*w12);
  /* #39: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #40: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #41: @12 = (@12+@13) */
  w12 += w13;
  /* #42: output[1][4] = @12 */
  if (res[1]) res[1][4] = w12;
  /* #43: output[1][5] = @4 */
  if (res[1]) res[1][5] = w4;
  /* #44: {NULL, NULL, @4, @12, NULL, @13} = vertsplit(@8) */
  w4 = w8[2];
  w12 = w8[3];
  w13 = w8[5];
  /* #45: @16 = (@2*@12) */
  w16  = (w2*w12);
  /* #46: @17 = (@15*@4) */
  w17  = (w15*w4);
  /* #47: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #48: @16 = (@16-@17) */
  w16 -= w17;
  /* #49: output[1][6] = @16 */
  if (res[1]) res[1][6] = w16;
  /* #50: @12 = (@3*@12) */
  w12  = (w3*w12);
  /* #51: @4 = (@14*@4) */
  w4  = (w14*w4);
  /* #52: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #53: @12 = (@12+@4) */
  w12 += w4;
  /* #54: output[1][7] = @12 */
  if (res[1]) res[1][7] = w12;
  /* #55: output[1][8] = @13 */
  if (res[1]) res[1][8] = w13;
  /* #56: {NULL, NULL, @13, @12, NULL, @4} = vertsplit(@9) */
  w13 = w9[2];
  w12 = w9[3];
  w4 = w9[5];
  /* #57: @16 = (@2*@12) */
  w16  = (w2*w12);
  /* #58: @17 = (@15*@13) */
  w17  = (w15*w13);
  /* #59: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #60: @16 = (@16-@17) */
  w16 -= w17;
  /* #61: output[1][9] = @16 */
  if (res[1]) res[1][9] = w16;
  /* #62: @12 = (@3*@12) */
  w12  = (w3*w12);
  /* #63: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #64: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #65: @12 = (@12+@13) */
  w12 += w13;
  /* #66: output[1][10] = @12 */
  if (res[1]) res[1][10] = w12;
  /* #67: output[1][11] = @4 */
  if (res[1]) res[1][11] = w4;
  /* #68: {NULL, NULL, @4, @12, NULL, @13} = vertsplit(@10) */
  w4 = w10[2];
  w12 = w10[3];
  w13 = w10[5];
  /* #69: @16 = (@2*@12) */
  w16  = (w2*w12);
  /* #70: @17 = (@15*@4) */
  w17  = (w15*w4);
  /* #71: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #72: @16 = (@16-@17) */
  w16 -= w17;
  /* #73: output[1][12] = @16 */
  if (res[1]) res[1][12] = w16;
  /* #74: @12 = (@3*@12) */
  w12  = (w3*w12);
  /* #75: @4 = (@14*@4) */
  w4  = (w14*w4);
  /* #76: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #77: @12 = (@12+@4) */
  w12 += w4;
  /* #78: output[1][13] = @12 */
  if (res[1]) res[1][13] = w12;
  /* #79: output[1][14] = @13 */
  if (res[1]) res[1][14] = w13;
  /* #80: {NULL, NULL, @13, @12, NULL, @4} = vertsplit(@11) */
  w13 = w11[2];
  w12 = w11[3];
  w4 = w11[5];
  /* #81: @16 = (@2*@12) */
  w16  = (w2*w12);
  /* #82: @15 = (@15*@13) */
  w15 *= w13;
  /* #83: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #84: @16 = (@16-@15) */
  w16 -= w15;
  /* #85: output[1][15] = @16 */
  if (res[1]) res[1][15] = w16;
  /* #86: @12 = (@3*@12) */
  w12  = (w3*w12);
  /* #87: @14 = (@14*@13) */
  w14 *= w13;
  /* #88: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #89: @12 = (@12+@14) */
  w12 += w14;
  /* #90: output[1][16] = @12 */
  if (res[1]) res[1][16] = w12;
  /* #91: output[1][17] = @4 */
  if (res[1]) res[1][17] = w4;
  /* #92: @18 = zeros(3x6,3nz) */
  casadi_clear(w18, 3);
  /* #93: @19 = 00 */
  /* #94: @20 = 00 */
  /* #95: @21 = ones(3x1) */
  casadi_fill(w21, 3, 1.);
  /* #96: {@4, @12, @14} = vertsplit(@21) */
  w4 = w21[0];
  w12 = w21[1];
  w14 = w21[2];
  /* #97: @22 = 00 */
  /* #98: @21 = vertcat(@19, @20, @12, @4, @22, @14) */
  rr=w21;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w14;
  /* #99: @23 = @21[:3] */
  for (rr=w23, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #100: (@18[:3] = @23) */
  for (rr=w18+0, ss=w23; rr!=w18+3; rr+=1) *rr = *ss++;
  /* #101: @23 = @18' */
  casadi_trans(w18,casadi_s1, w23, casadi_s0, iw);
  /* #102: @24 = project(@23) */
  casadi_project(w23, casadi_s0, w24, casadi_s2, w);
  /* #103: @25 = input[2][0] */
  casadi_copy(arg[2], 18, w25);
  /* #104: {@11, @10, @9} = horzsplit(@25) */
  casadi_copy(w25, 6, w11);
  casadi_copy(w25+6, 6, w10);
  casadi_copy(w25+12, 6, w9);
  /* #105: {NULL, NULL, @12, @4, NULL, @14} = vertsplit(@11) */
  w12 = w11[2];
  w4 = w11[3];
  w14 = w11[5];
  /* #106: @13 = (@2*@4) */
  w13  = (w2*w4);
  /* #107: @16 = sin(@1) */
  w16 = sin( w1 );
  /* #108: @15 = (@16*@12) */
  w15  = (w16*w12);
  /* #109: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #110: @13 = (@13-@15) */
  w13 -= w15;
  /* #111: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #112: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #113: @12 = (@1*@12) */
  w12  = (w1*w12);
  /* #114: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #115: @4 = (@4+@12) */
  w4 += w12;
  /* #116: @19 = 00 */
  /* #117: @20 = 00 */
  /* #118: @22 = 00 */
  /* #119: @23 = vertcat(@13, @4, @19, @20, @14, @22) */
  rr=w23;
  *rr++ = w13;
  *rr++ = w4;
  *rr++ = w14;
  /* #120: {NULL, NULL, @13, @4, NULL, @14} = vertsplit(@10) */
  w13 = w10[2];
  w4 = w10[3];
  w14 = w10[5];
  /* #121: @12 = (@2*@4) */
  w12  = (w2*w4);
  /* #122: @15 = (@16*@13) */
  w15  = (w16*w13);
  /* #123: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #124: @12 = (@12-@15) */
  w12 -= w15;
  /* #125: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #126: @13 = (@1*@13) */
  w13  = (w1*w13);
  /* #127: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #128: @4 = (@4+@13) */
  w4 += w13;
  /* #129: @19 = 00 */
  /* #130: @20 = 00 */
  /* #131: @22 = 00 */
  /* #132: @18 = vertcat(@12, @4, @19, @20, @14, @22) */
  rr=w18;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w14;
  /* #133: {NULL, NULL, @12, @4, NULL, @14} = vertsplit(@9) */
  w12 = w9[2];
  w4 = w9[3];
  w14 = w9[5];
  /* #134: @2 = (@2*@4) */
  w2 *= w4;
  /* #135: @16 = (@16*@12) */
  w16 *= w12;
  /* #136: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #137: @2 = (@2-@16) */
  w2 -= w16;
  /* #138: @3 = (@3*@4) */
  w3 *= w4;
  /* #139: @1 = (@1*@12) */
  w1 *= w12;
  /* #140: @0 = (@0*@1) */
  w0 *= w1;
  /* #141: @3 = (@3+@0) */
  w3 += w0;
  /* #142: @19 = 00 */
  /* #143: @20 = 00 */
  /* #144: @22 = 00 */
  /* #145: @21 = vertcat(@2, @3, @19, @20, @14, @22) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w14;
  /* #146: @26 = horzcat(@23, @18, @21) */
  rr=w26;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #147: @27 = project(@26) */
  casadi_project(w26, casadi_s3, w27, casadi_s2, w);
  /* #148: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<12; ++i) (*rr++) += (*cs++);
  /* #149: output[2][0] = @24 */
  casadi_copy(w24, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_model_mpcc_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 149;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
