/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[33] = {11, 10, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10};
static const casadi_int casadi_s2[25] = {1, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[1] = {1};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[2] = {0, 13};
static const casadi_int casadi_s7[1] = {3};
static const casadi_int casadi_s8[2] = {0, 15};
static const casadi_int casadi_s9[21] = {1, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s10[30] = {10, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9};
static const casadi_int casadi_s11[2] = {0, 11};
static const casadi_int casadi_s12[19] = {1, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s13[27] = {9, 8, 0, 2, 4, 6, 8, 10, 12, 14, 16, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8};
static const casadi_int casadi_s14[2] = {0, 9};
static const casadi_int casadi_s15[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s16[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s17[12] = {1, 6, 0, 1, 2, 2, 2, 3, 3, 0, 0, 0};
static const casadi_int casadi_s18[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s19[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s20[27] = {3, 6, 0, 3, 6, 9, 12, 15, 18, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s21[7] = {6, 1, 0, 3, 0, 1, 4};
static const casadi_int casadi_s22[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s23[3] = {0, 0, 0};
static const casadi_int casadi_s24[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s25[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s26[16] = {9, 2, 0, 9, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 3, 4};
static const casadi_int casadi_s27[3] = {2, 0, 0};

static const casadi_real casadi_c0[20] = {-3.7500000000000000e+00, 3.7500000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000000e+00, 1.8750000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000004e+00, 1.8750000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -3.7500000000000009e+00, 3.7500000000000009e+00};
static const casadi_real casadi_c1[13] = {0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4.};
static const casadi_real casadi_c2[15] = {0., 0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4., 4.};
static const casadi_real casadi_c3[18] = {-2.5000000000000000e+00, 2.5000000000000000e+00, -1.6666666666666665e+00, 1.6666666666666665e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -1.6666666666666670e+00, 1.6666666666666670e+00, -2.5000000000000004e+00, 2.5000000000000004e+00};
static const casadi_real casadi_c4[11] = {0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4.};
static const casadi_real casadi_c5[16] = {-1.2500000000000000e+00, 1.2500000000000000e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.4999999999999978e+00, 2.4999999999999978e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -1.2500000000000002e+00, 1.2500000000000002e+00};
static const casadi_real casadi_c6[9] = {0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4.};
static const casadi_real casadi_c7[18] = {0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.};

/* fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* xr:(i0,i1[11])->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* yr:(i0,i1[11])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* adj1_yr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_xr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* adj1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* adj1_adj1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],out_adj_out_o0[1x1,0nz],out_adj_fwd_i0[1x1,0nz],out_adj_fwd_i1[11x1,0nz],adj_adj_i0,adj_adj_i1[11x1,0nz],adj_adj_out_o0[1x1,0nz],adj_adj_fwd_i0,adj_adj_fwd_i1[11x1,0nz])->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz],adj_out_fwd_o0[1x1,0nz],adj_adj_fwd_o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8, w9, *w10=w+80, *w11=w+88, w12, w13, w14, w15;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[6][0] */
  w7 = arg[6] ? arg[6][0] : 0;
  /* #11: @8 = input[15][0] */
  w8 = arg[15] ? arg[15][0] : 0;
  /* #12: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #13: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #14: @10 = zeros(1x8) */
  casadi_clear(w10, 8);
  /* #15: @11 = 
  [[-1.25, 00, 00, 00, 00, 00, 00, 00], 
   [1.25, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.25], 
   [00, 00, 00, 00, 00, 00, 00, 1.25]] */
  casadi_copy(casadi_c5, 16, w11);
  /* #16: @10 = mac(@1,@11,@10) */
  casadi_mtimes(w1, casadi_s9, w11, casadi_s13, w10, casadi_s12, w, 0);
  /* #17: @12 = BSplineParametric(@0) */
  casadi_clear((&w12), 1);
  CASADI_PREFIX(nd_boor_eval)((&w12),1,casadi_c6,casadi_s14,casadi_s3,casadi_s4,w10,1,(&w0),casadi_s3, iw, w);
  /* #18: @13 = input[3][0] */
  w13 = arg[3] ? arg[3][0] : 0;
  /* #19: @14 = (@13*@7) */
  w14  = (w13*w7);
  /* #20: @15 = input[12][0] */
  w15 = arg[12] ? arg[12][0] : 0;
  /* #21: @14 = (@14*@15) */
  w14 *= w15;
  /* #22: @12 = (@12*@14) */
  w12 *= w14;
  /* #23: @9 = (@9+@12) */
  w9 += w12;
  /* #24: output[0][0] = @9 */
  if (res[0]) res[0][0] = w9;
  /* #25: @6 = (@6*@15) */
  w6 *= w15;
  /* #26: @7 = (@7*@6) */
  w7 *= w6;
  /* #27: output[3][0] = @7 */
  if (res[3]) res[3][0] = w7;
  /* #28: @7 = BSplineParametric(@0) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #29: @7 = (@7*@8) */
  w7 *= w8;
  /* #30: @13 = (@13*@6) */
  w13 *= w6;
  /* #31: @7 = (@7+@13) */
  w7 += w13;
  /* #32: output[6][0] = @7 */
  if (res[6]) res[6][0] = w7;
  return 0;
}

/* adj1_adj1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],out_adj_out_o0[1x1,0nz],out_adj_fwd_i0[1x1,0nz],out_adj_fwd_i1[11x1,0nz],adj_adj_i0,adj_adj_i1[11x1,0nz],adj_adj_out_o0[1x1,0nz],adj_adj_fwd_i0,adj_adj_fwd_i1[11x1,0nz])->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz],adj_out_fwd_o0[1x1,0nz],adj_adj_fwd_o0) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8, w9, *w10=w+80, *w11=w+88, w12, w13, w14, w15;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[6][0] */
  w7 = arg[6] ? arg[6][0] : 0;
  /* #11: @8 = input[15][0] */
  w8 = arg[15] ? arg[15][0] : 0;
  /* #12: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #13: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #14: @10 = zeros(1x8) */
  casadi_clear(w10, 8);
  /* #15: @11 = 
  [[-1.25, 00, 00, 00, 00, 00, 00, 00], 
   [1.25, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.25], 
   [00, 00, 00, 00, 00, 00, 00, 1.25]] */
  casadi_copy(casadi_c5, 16, w11);
  /* #16: @10 = mac(@1,@11,@10) */
  casadi_mtimes(w1, casadi_s9, w11, casadi_s13, w10, casadi_s12, w, 0);
  /* #17: @12 = BSplineParametric(@0) */
  casadi_clear((&w12), 1);
  CASADI_PREFIX(nd_boor_eval)((&w12),1,casadi_c6,casadi_s14,casadi_s3,casadi_s4,w10,1,(&w0),casadi_s3, iw, w);
  /* #18: @13 = input[3][0] */
  w13 = arg[3] ? arg[3][0] : 0;
  /* #19: @14 = (@13*@7) */
  w14  = (w13*w7);
  /* #20: @15 = input[12][0] */
  w15 = arg[12] ? arg[12][0] : 0;
  /* #21: @14 = (@14*@15) */
  w14 *= w15;
  /* #22: @12 = (@12*@14) */
  w12 *= w14;
  /* #23: @9 = (@9+@12) */
  w9 += w12;
  /* #24: output[0][0] = @9 */
  if (res[0]) res[0][0] = w9;
  /* #25: @6 = (@6*@15) */
  w6 *= w15;
  /* #26: @7 = (@7*@6) */
  w7 *= w6;
  /* #27: output[3][0] = @7 */
  if (res[3]) res[3][0] = w7;
  /* #28: @7 = BSplineParametric(@0) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #29: @7 = (@7*@8) */
  w7 *= w8;
  /* #30: @13 = (@13*@6) */
  w13 *= w6;
  /* #31: @7 = (@7+@13) */
  w7 += w13;
  /* #32: output[6][0] = @7 */
  if (res[6]) res[6][0] = w7;
  return 0;
}

/* adj1_adj1_yr:(i0,i1[11],out_o0[1x1,0nz],adj_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],adj_adj_i0,adj_adj_i1[11x1,0nz])->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_adj_o0) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* adj1_adj1_xr:(i0,i1[11],out_o0[1x1,0nz],adj_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],adj_adj_i0,adj_adj_i1[11x1,0nz])->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_adj_o0) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* unicycle_model_mpcc_constr_h_fun_jac_uxt_zt:(i0[6],i1[3],i2[],i3[46])->(o0[2],o1[9x2,11nz],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+3, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real w0, *w1=w+109, w2, *w3=w+113, w5, *w6=w+125, w7, *w8=w+137, w10, *w11=w+149, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w55, w56, *w60=w+196, w61, w62, w63, w64, w65, w66, w67, w68, *w69=w+207, *w70=w+213, w71, w72, w78, w79, w80, w81, w82, w83, w84, w85, w86, w87, w88, w93, w94, *w98=w+231, w99, *w100=w+250, *w103=w+261, w107, w108, w109, w110, w111, w112, w113, w114, w115, w116, w117, w118, w119, w120, w121, w122;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(6x1,3nz) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = input[3][0] */
  casadi_copy(arg[3], 11, w3);
  /* #4: @4 = 00 */
  /* #5: @5 = 1 */
  w5 = 1.;
  /* #6: @6 = zeros(11x1) */
  casadi_clear(w6, 11);
  /* #7: @7 = fwd1_xr(@2, @3, @4, @5, @6) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  res1[0]=(&w7);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: @8 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+11 : 0, 11, w8);
  /* #9: @9 = 00 */
  /* #10: @10 = 1 */
  w10 = 1.;
  /* #11: @11 = zeros(11x1) */
  casadi_clear(w11, 11);
  /* #12: @12 = fwd1_yr(@2, @8, @9, @10, @11) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  res1[0]=(&w12);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #13: @13 = atan2(@7,@12) */
  w13  = atan2(w7,w12);
  /* #14: @14 = sin(@13) */
  w14 = sin( w13 );
  /* #15: @15 = input[0][0] */
  w15 = arg[0] ? arg[0][0] : 0;
  /* #16: @16 = xr(@2, @3) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  res1[0]=(&w16);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #17: @17 = (@15-@16) */
  w17  = (w15-w16);
  /* #18: @18 = (@14*@17) */
  w18  = (w14*w17);
  /* #19: @19 = cos(@13) */
  w19 = cos( w13 );
  /* #20: @20 = input[0][1] */
  w20 = arg[0] ? arg[0][1] : 0;
  /* #21: @21 = yr(@2, @8) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  res1[0]=(&w21);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #22: @22 = (@20-@21) */
  w22  = (w20-w21);
  /* #23: @23 = (@19*@22) */
  w23  = (w19*w22);
  /* #24: @18 = (@18-@23) */
  w18 -= w23;
  /* #25: @23 = (2.*@18) */
  w23 = (2.* w18 );
  /* #26: @24 = input[3][9] */
  w24 = arg[3] ? arg[3][41] : 0;
  /* #27: @23 = (@23*@24) */
  w23 *= w24;
  /* #28: @25 = (@14*@23) */
  w25  = (w14*w23);
  /* #29: @26 = cos(@13) */
  w26 = cos( w13 );
  /* #30: @16 = (@15-@16) */
  w16  = (w15-w16);
  /* #31: @27 = (@26*@16) */
  w27  = (w26*w16);
  /* #32: @27 = (-@27) */
  w27 = (- w27 );
  /* #33: @28 = sin(@13) */
  w28 = sin( w13 );
  /* #34: @21 = (@20-@21) */
  w21  = (w20-w21);
  /* #35: @29 = (@28*@21) */
  w29  = (w28*w21);
  /* #36: @27 = (@27-@29) */
  w27 -= w29;
  /* #37: @29 = (2.*@27) */
  w29 = (2.* w27 );
  /* #38: @30 = input[3][10] */
  w30 = arg[3] ? arg[3][42] : 0;
  /* #39: @29 = (@29*@30) */
  w29 *= w30;
  /* #40: @31 = (@26*@29) */
  w31  = (w26*w29);
  /* #41: @32 = (@25-@31) */
  w32  = (w25-w31);
  /* #42: (@1[0] = @32) */
  for (rr=w1+0, ss=(&w32); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #43: @32 = (@19*@23) */
  w32  = (w19*w23);
  /* #44: @33 = (-@32) */
  w33 = (- w32 );
  /* #45: @34 = (@28*@29) */
  w34  = (w28*w29);
  /* #46: @33 = (@33-@34) */
  w33 -= w34;
  /* #47: (@1[1] = @33) */
  for (rr=w1+1, ss=(&w33); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #48: @35 = 00 */
  /* #49: @34 = (@34+@32) */
  w34 += w32;
  /* #50: {@32, @36} = adj1_yr(@2, @8, @35, @34) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w34);
  res1[0]=(&w32);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #51: @37 = 00 */
  /* #52: @31 = (@31-@25) */
  w31 -= w25;
  /* #53: {@25, @38} = adj1_xr(@2, @3, @37, @31) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w31);
  res1[0]=(&w25);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #54: @32 = (@32+@25) */
  w32 += w25;
  /* #55: @39 = 00 */
  /* #56: @25 = sq(@7) */
  w25 = casadi_sq( w7 );
  /* #57: @33 = sq(@12) */
  w33 = casadi_sq( w12 );
  /* #58: @25 = (@25+@33) */
  w25 += w33;
  /* #59: @33 = (@7/@25) */
  w33  = (w7/w25);
  /* #60: @40 = sin(@13) */
  w40 = sin( w13 );
  /* #61: @41 = (@16*@29) */
  w41  = (w16*w29);
  /* #62: @42 = (@40*@41) */
  w42  = (w40*w41);
  /* #63: @43 = cos(@13) */
  w43 = cos( w13 );
  /* #64: @44 = (@21*@29) */
  w44  = (w21*w29);
  /* #65: @45 = (@43*@44) */
  w45  = (w43*w44);
  /* #66: @42 = (@42-@45) */
  w42 -= w45;
  /* #67: @45 = sin(@13) */
  w45 = sin( w13 );
  /* #68: @46 = (@22*@23) */
  w46  = (w22*w23);
  /* #69: @47 = (@45*@46) */
  w47  = (w45*w46);
  /* #70: @42 = (@42+@47) */
  w42 += w47;
  /* #71: @47 = cos(@13) */
  w47 = cos( w13 );
  /* #72: @48 = (@17*@23) */
  w48  = (w17*w23);
  /* #73: @49 = (@47*@48) */
  w49  = (w47*w48);
  /* #74: @42 = (@42+@49) */
  w42 += w49;
  /* #75: @49 = (@33*@42) */
  w49  = (w33*w42);
  /* #76: @49 = (-@49) */
  w49 = (- w49 );
  /* #77: {@50, @51, @52, NULL, @53} = adj1_fwd1_yr(@2, @8, @9, @10, @11, @39, @49) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  arg1[5]=0;
  arg1[6]=(&w49);
  res1[0]=(&w50);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #78: @32 = (@32+@50) */
  w32 += w50;
  /* #79: @54 = 00 */
  /* #80: @50 = (@12/@25) */
  w50  = (w12/w25);
  /* #81: @55 = (@50*@42) */
  w55  = (w50*w42);
  /* #82: {@56, @57, @58, NULL, @59} = adj1_fwd1_xr(@2, @3, @4, @5, @6, @54, @55) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  arg1[5]=0;
  arg1[6]=(&w55);
  res1[0]=(&w56);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #83: @32 = (@32+@56) */
  w32 += w56;
  /* #84: (@1[2] = @32) */
  for (rr=w1+2, ss=(&w32); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #85: @60 = @1' */
  casadi_copy(w1, 3, w60);
  /* #86: @32 = input[0][3] */
  w32 = arg[0] ? arg[0][3] : 0;
  /* #87: @56 = input[0][2] */
  w56 = arg[0] ? arg[0][2] : 0;
  /* #88: @61 = cos(@56) */
  w61 = cos( w56 );
  /* #89: @62 = (@32*@61) */
  w62  = (w32*w61);
  /* #90: @63 = sin(@56) */
  w63 = sin( w56 );
  /* #91: @64 = (@32*@63) */
  w64  = (w32*w63);
  /* #92: @65 = 0 */
  w65 = 0.;
  /* #93: @66 = 0 */
  w66 = 0.;
  /* #94: @67 = input[0][5] */
  w67 = arg[0] ? arg[0][5] : 0;
  /* #95: @68 = 0 */
  w68 = 0.;
  /* #96: @69 = vertcat(@62, @64, @65, @66, @67, @68) */
  rr=w69;
  *rr++ = w62;
  *rr++ = w64;
  *rr++ = w65;
  *rr++ = w66;
  *rr++ = w67;
  *rr++ = w68;
  /* #97: @0 = mac(@60,@69,@0) */
  casadi_mtimes(w60, casadi_s17, w69, casadi_s16, (&w0), casadi_s15, w, 0);
  /* #98: @62 = 0 */
  w62 = 0.;
  /* #99: @60 = zeros(1x3) */
  casadi_clear(w60, 3);
  /* #100: @70 = zeros(6x1,3nz) */
  casadi_clear(w70, 3);
  /* #101: @64 = (2.*@18) */
  w64 = (2.* w18 );
  /* #102: @64 = (@64*@24) */
  w64 *= w24;
  /* #103: @65 = (@14*@64) */
  w65  = (w14*w64);
  /* #104: @66 = (2.*@27) */
  w66 = (2.* w27 );
  /* #105: @66 = (@66*@30) */
  w66 *= w30;
  /* #106: @67 = (@26*@66) */
  w67  = (w26*w66);
  /* #107: @68 = (@65-@67) */
  w68  = (w65-w67);
  /* #108: (@70[0] = @68) */
  for (rr=w70+0, ss=(&w68); rr!=w70+1; rr+=1) *rr = *ss++;
  /* #109: @68 = (@19*@64) */
  w68  = (w19*w64);
  /* #110: @71 = (-@68) */
  w71 = (- w68 );
  /* #111: @72 = (@28*@66) */
  w72  = (w28*w66);
  /* #112: @71 = (@71-@72) */
  w71 -= w72;
  /* #113: (@70[1] = @71) */
  for (rr=w70+1, ss=(&w71); rr!=w70+2; rr+=1) *rr = *ss++;
  /* #114: @73 = 00 */
  /* #115: @72 = (@72+@68) */
  w72 += w68;
  /* #116: {@68, @74} = adj1_yr(@2, @8, @73, @72) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w72);
  res1[0]=(&w68);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #117: @75 = 00 */
  /* #118: @67 = (@67-@65) */
  w67 -= w65;
  /* #119: {@65, @76} = adj1_xr(@2, @3, @75, @67) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w67);
  res1[0]=(&w65);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #120: @68 = (@68+@65) */
  w68 += w65;
  /* #121: @77 = 00 */
  /* #122: @65 = sq(@7) */
  w65 = casadi_sq( w7 );
  /* #123: @71 = sq(@12) */
  w71 = casadi_sq( w12 );
  /* #124: @65 = (@65+@71) */
  w65 += w71;
  /* #125: @71 = (@7/@65) */
  w71  = (w7/w65);
  /* #126: @78 = sin(@13) */
  w78 = sin( w13 );
  /* #127: @79 = (@16*@66) */
  w79  = (w16*w66);
  /* #128: @80 = (@78*@79) */
  w80  = (w78*w79);
  /* #129: @81 = cos(@13) */
  w81 = cos( w13 );
  /* #130: @82 = (@21*@66) */
  w82  = (w21*w66);
  /* #131: @83 = (@81*@82) */
  w83  = (w81*w82);
  /* #132: @80 = (@80-@83) */
  w80 -= w83;
  /* #133: @83 = sin(@13) */
  w83 = sin( w13 );
  /* #134: @84 = (@22*@64) */
  w84  = (w22*w64);
  /* #135: @85 = (@83*@84) */
  w85  = (w83*w84);
  /* #136: @80 = (@80+@85) */
  w80 += w85;
  /* #137: @85 = cos(@13) */
  w85 = cos( w13 );
  /* #138: @86 = (@17*@64) */
  w86  = (w17*w64);
  /* #139: @87 = (@85*@86) */
  w87  = (w85*w86);
  /* #140: @80 = (@80+@87) */
  w80 += w87;
  /* #141: @87 = (@71*@80) */
  w87  = (w71*w80);
  /* #142: @87 = (-@87) */
  w87 = (- w87 );
  /* #143: {@88, @89, @90, NULL, @91} = adj1_fwd1_yr(@2, @8, @9, @10, @11, @77, @87) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  arg1[5]=0;
  arg1[6]=(&w87);
  res1[0]=(&w88);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #144: @68 = (@68+@88) */
  w68 += w88;
  /* #145: @92 = 00 */
  /* #146: @88 = (@12/@65) */
  w88  = (w12/w65);
  /* #147: @93 = (@88*@80) */
  w93  = (w88*w80);
  /* #148: {@94, @95, @96, NULL, @97} = adj1_fwd1_xr(@2, @3, @4, @5, @6, @92, @93) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  arg1[5]=0;
  arg1[6]=(&w93);
  res1[0]=(&w94);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #149: @68 = (@68+@94) */
  w68 += w94;
  /* #150: (@70[2] = @68) */
  for (rr=w70+2, ss=(&w68); rr!=w70+3; rr+=1) *rr = *ss++;
  /* #151: @70 = @70' */
  /* #152: @98 = 
  [[0, 0, 0], 
   [0, 0, 0], 
   [0, 1, 0], 
   [1, 0, 0], 
   [0, 0, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c7, 18, w98);
  /* #153: @60 = mac(@70,@98,@60) */
  casadi_mtimes(w70, casadi_s17, w98, casadi_s19, w60, casadi_s18, w, 0);
  /* #154: @68 = input[1][0] */
  w68 = arg[1] ? arg[1][0] : 0;
  /* #155: @94 = input[1][1] */
  w94 = arg[1] ? arg[1][1] : 0;
  /* #156: @99 = input[1][2] */
  w99 = arg[1] ? arg[1][2] : 0;
  /* #157: @70 = vertcat(@68, @94, @99) */
  rr=w70;
  *rr++ = w68;
  *rr++ = w94;
  *rr++ = w99;
  /* #158: @62 = mac(@60,@70,@62) */
  for (i=0, rr=(&w62); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w60+j, tt=w70+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #159: @0 = (@0+@62) */
  w0 += w62;
  /* #160: @62 = input[3][11] */
  w62 = arg[3] ? arg[3][43] : 0;
  /* #161: @68 = sq(@18) */
  w68 = casadi_sq( w18 );
  /* #162: @68 = (@24*@68) */
  w68  = (w24*w68);
  /* #163: @94 = sq(@27) */
  w94 = casadi_sq( w27 );
  /* #164: @94 = (@30*@94) */
  w94  = (w30*w94);
  /* #165: @68 = (@68+@94) */
  w68 += w94;
  /* #166: @68 = (@62*@68) */
  w68  = (w62*w68);
  /* #167: @0 = (@0+@68) */
  w0 += w68;
  /* #168: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #169: @0 = input[3][12] */
  w0 = arg[3] ? arg[3][44] : 0;
  /* #170: @15 = (@15-@0) */
  w15 -= w0;
  /* #171: @0 = sq(@15) */
  w0 = casadi_sq( w15 );
  /* #172: @68 = input[3][13] */
  w68 = arg[3] ? arg[3][45] : 0;
  /* #173: @20 = (@20-@68) */
  w20 -= w68;
  /* #174: @68 = sq(@20) */
  w68 = casadi_sq( w20 );
  /* #175: @0 = (@0+@68) */
  w0 += w68;
  /* #176: @68 = 0.140625 */
  w68 = 1.4062500000000000e-01;
  /* #177: @0 = (@0-@68) */
  w0 -= w68;
  /* #178: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #179: @100 = zeros(9x2,11nz) */
  casadi_clear(w100, 11);
  /* #180: @60 = @60' */
  /* #181: @0 = ones(2x1,1nz) */
  w0 = 1.;
  /* #182: {@68, NULL} = vertsplit(@0) */
  w68 = w0;
  /* #183: @60 = (@60*@68) */
  for (i=0, rr=w60; i<3; ++i) (*rr++) *= w68;
  /* #184: {@0, @94, @99} = vertsplit(@60) */
  w0 = w60[0];
  w94 = w60[1];
  w99 = w60[2];
  /* #185: (@100[0] = @0) */
  for (rr=w100+0, ss=(&w0); rr!=w100+1; rr+=1) *rr = *ss++;
  /* #186: (@100[1] = @94) */
  for (rr=w100+1, ss=(&w94); rr!=w100+2; rr+=1) *rr = *ss++;
  /* #187: (@100[2] = @99) */
  for (rr=w100+2, ss=(&w99); rr!=w100+3; rr+=1) *rr = *ss++;
  /* #188: @101 = 00 */
  /* #189: @102 = 00 */
  /* #190: @60 = zeros(1x6,3nz) */
  casadi_clear(w60, 3);
  /* #191: @70 = @70' */
  /* #192: @70 = (@68*@70) */
  for (i=0, rr=w70, cs=w70; i<3; ++i) (*rr++)  = (w68*(*cs++));
  /* #193: @103 = @98' */
  for (i=0, rr=w103, cs=w98; i<3; ++i) for (j=0; j<6; ++j) rr[i+j*3] = *cs++;
  /* #194: @60 = mac(@70,@103,@60) */
  casadi_mtimes(w70, casadi_s18, w103, casadi_s20, w60, casadi_s17, w, 0);
  /* #195: @60 = @60' */
  /* #196: @99 = @60[2] */
  for (rr=(&w99), ss=w60+2; ss!=w60+3; ss+=1) *rr++ = *ss;
  /* #197: @104 = zeros(11x1,0nz) */
  /* #198: @105 = 00 */
  /* #199: @94 = 0 */
  w94 = 0.;
  /* #200: @106 = zeros(11x1,0nz) */
  /* #201: {@0, NULL, NULL, NULL, NULL, NULL, @107} = adj1_adj1_fwd1_xr(@2, @3, @4, @5, @6, @92, @93, @101, @95, @96, @102, @97, @99, @104, @105, @94, @106) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  arg1[5]=0;
  arg1[6]=(&w93);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w99);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w94);
  arg1[16]=0;
  res1[0]=(&w0);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  res1[6]=(&w107);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #202: @93 = (@88*@107) */
  w93  = (w88*w107);
  /* #203: @92 = 00 */
  /* #204: @101 = 00 */
  /* #205: @95 = zeros(11x1,0nz) */
  /* #206: @96 = 00 */
  /* #207: @94 = 0 */
  w94 = 0.;
  /* #208: @102 = zeros(11x1,0nz) */
  /* #209: {@108, NULL, NULL, NULL, NULL, NULL, @109} = adj1_adj1_fwd1_yr(@2, @8, @9, @10, @11, @77, @87, @92, @89, @90, @101, @91, @99, @95, @96, @94, @102) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  arg1[5]=0;
  arg1[6]=(&w87);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w99);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w94);
  arg1[16]=0;
  res1[0]=(&w108);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  res1[6]=(&w109);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #210: @87 = (@71*@109) */
  w87  = (w71*w109);
  /* #211: @93 = (@93-@87) */
  w93 -= w87;
  /* #212: @78 = (@78*@93) */
  w78 *= w93;
  /* #213: @87 = (@66*@78) */
  w87  = (w66*w78);
  /* #214: @77 = 00 */
  /* #215: @92 = 00 */
  /* #216: @69 = @69' */
  /* #217: @69 = (@68*@69) */
  for (i=0, rr=w69, cs=w69; i<6; ++i) (*rr++)  = (w68*(*cs++));
  /* #218: @69 = @69' */
  /* #219: @94 = @69[4] */
  for (rr=(&w94), ss=w69+4; ss!=w69+5; ss+=1) *rr++ = *ss;
  /* #220: @89 = zeros(11x1,0nz) */
  /* #221: @90 = 00 */
  /* #222: @110 = 0 */
  w110 = 0.;
  /* #223: @101 = zeros(11x1,0nz) */
  /* #224: {@111, NULL, NULL, NULL, NULL, NULL, @112} = adj1_adj1_fwd1_xr(@2, @3, @4, @5, @6, @54, @55, @77, @57, @58, @92, @59, @94, @89, @90, @110, @101) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  arg1[5]=0;
  arg1[6]=(&w55);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w94);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w110);
  arg1[16]=0;
  res1[0]=(&w111);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  res1[6]=(&w112);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #225: @55 = (@50*@112) */
  w55  = (w50*w112);
  /* #226: @54 = 00 */
  /* #227: @77 = 00 */
  /* #228: @57 = zeros(11x1,0nz) */
  /* #229: @58 = 00 */
  /* #230: @110 = 0 */
  w110 = 0.;
  /* #231: @92 = zeros(11x1,0nz) */
  /* #232: {@113, NULL, NULL, NULL, NULL, NULL, @114} = adj1_adj1_fwd1_yr(@2, @8, @9, @10, @11, @39, @49, @54, @51, @52, @77, @53, @94, @57, @58, @110, @92) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  arg1[5]=0;
  arg1[6]=(&w49);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=(&w94);
  arg1[13]=0;
  arg1[14]=0;
  arg1[15]=(&w110);
  arg1[16]=0;
  res1[0]=(&w113);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  res1[6]=(&w114);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #233: @49 = (@33*@114) */
  w49  = (w33*w114);
  /* #234: @55 = (@55-@49) */
  w55 -= w49;
  /* #235: @40 = (@40*@55) */
  w40 *= w55;
  /* #236: @49 = (@29*@40) */
  w49  = (w29*w40);
  /* #237: @87 = (@87+@49) */
  w87 += w49;
  /* #238: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #239: @62 = (@62*@68) */
  w62 *= w68;
  /* #240: @49 = (@30*@62) */
  w49  = (w30*w62);
  /* #241: @27 = (@27*@49) */
  w27 *= w49;
  /* #242: @78 = (@16*@78) */
  w78  = (w16*w78);
  /* #243: @81 = (@81*@93) */
  w81 *= w93;
  /* #244: @49 = (@21*@81) */
  w49  = (w21*w81);
  /* #245: @78 = (@78-@49) */
  w78 -= w49;
  /* #246: @39 = 00 */
  /* #247: @54 = zeros(11x1,0nz) */
  /* #248: {@49, NULL, NULL, @110} = adj1_adj1_yr(@2, @8, @73, @72, @39, @74, @99, @54) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w72);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w99);
  arg1[7]=0;
  res1[0]=(&w49);
  res1[1]=0;
  res1[2]=0;
  res1[3]=(&w110);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #249: @72 = 0 */
  w72 = 0.;
  /* #250: (@60[2] = @72) */
  for (rr=w60+2, ss=(&w72); rr!=w60+3; rr+=1) *rr = *ss++;
  /* #251: @72 = @60[1] */
  for (rr=(&w72), ss=w60+1; ss!=w60+2; ss+=1) *rr++ = *ss;
  /* #252: @115 = (@110-@72) */
  w115  = (w110-w72);
  /* #253: @116 = (@28*@115) */
  w116  = (w28*w115);
  /* #254: @78 = (@78+@116) */
  w78 += w116;
  /* #255: @73 = 00 */
  /* #256: @39 = zeros(11x1,0nz) */
  /* #257: {@116, NULL, NULL, @117} = adj1_adj1_xr(@2, @3, @75, @67, @73, @76, @99, @39) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w67);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w99);
  arg1[7]=0;
  res1[0]=(&w116);
  res1[1]=0;
  res1[2]=0;
  res1[3]=(&w117);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #258: @67 = 0 */
  w67 = 0.;
  /* #259: (@60[1] = @67) */
  for (rr=w60+1, ss=(&w67); rr!=w60+2; rr+=1) *rr = *ss++;
  /* #260: @67 = @60[0] */
  for (rr=(&w67), ss=w60+0; ss!=w60+1; ss+=1) *rr++ = *ss;
  /* #261: @99 = (@117-@67) */
  w99  = (w117-w67);
  /* #262: @118 = (@26*@99) */
  w118  = (w26*w99);
  /* #263: @78 = (@78+@118) */
  w78 += w118;
  /* #264: @78 = (@30*@78) */
  w78  = (w30*w78);
  /* #265: @78 = (2.*@78) */
  w78 = (2.* w78 );
  /* #266: @27 = (@27+@78) */
  w27 += w78;
  /* #267: @40 = (@16*@40) */
  w40  = (w16*w40);
  /* #268: @43 = (@43*@55) */
  w43 *= w55;
  /* #269: @78 = (@21*@43) */
  w78  = (w21*w43);
  /* #270: @40 = (@40-@78) */
  w40 -= w78;
  /* #271: @75 = 00 */
  /* #272: @73 = zeros(11x1,0nz) */
  /* #273: {@78, NULL, NULL, @118} = adj1_adj1_yr(@2, @8, @35, @34, @75, @36, @94, @73) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w34);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w94);
  arg1[7]=0;
  res1[0]=(&w78);
  res1[1]=0;
  res1[2]=0;
  res1[3]=(&w118);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #274: @34 = 0 */
  w34 = 0.;
  /* #275: (@69[4] = @34) */
  for (rr=w69+4, ss=(&w34); rr!=w69+5; rr+=1) *rr = *ss++;
  /* #276: @34 = @69[1] */
  for (rr=(&w34), ss=w69+1; ss!=w69+2; ss+=1) *rr++ = *ss;
  /* #277: @119 = (@118-@34) */
  w119  = (w118-w34);
  /* #278: @120 = (@28*@119) */
  w120  = (w28*w119);
  /* #279: @40 = (@40+@120) */
  w40 += w120;
  /* #280: @35 = 00 */
  /* #281: @75 = zeros(11x1,0nz) */
  /* #282: {@120, NULL, NULL, @121} = adj1_adj1_xr(@2, @3, @37, @31, @35, @38, @94, @75) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w31);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w94);
  arg1[7]=0;
  res1[0]=(&w120);
  res1[1]=0;
  res1[2]=0;
  res1[3]=(&w121);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #283: @31 = 0 */
  w31 = 0.;
  /* #284: (@69[1] = @31) */
  for (rr=w69+1, ss=(&w31); rr!=w69+2; rr+=1) *rr = *ss++;
  /* #285: @31 = @69[0] */
  for (rr=(&w31), ss=w69+0; ss!=w69+1; ss+=1) *rr++ = *ss;
  /* #286: @94 = (@121-@31) */
  w94  = (w121-w31);
  /* #287: @122 = (@26*@94) */
  w122  = (w26*w94);
  /* #288: @40 = (@40+@122) */
  w40 += w122;
  /* #289: @30 = (@30*@40) */
  w30 *= w40;
  /* #290: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #291: @27 = (@27+@30) */
  w27 += w30;
  /* #292: @26 = (@26*@27) */
  w26 *= w27;
  /* #293: @87 = (@87-@26) */
  w87 -= w26;
  /* #294: @85 = (@85*@93) */
  w85 *= w93;
  /* #295: @26 = (@64*@85) */
  w26  = (w64*w85);
  /* #296: @47 = (@47*@55) */
  w47 *= w55;
  /* #297: @30 = (@23*@47) */
  w30  = (w23*w47);
  /* #298: @26 = (@26+@30) */
  w26 += w30;
  /* #299: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #300: @62 = (@24*@62) */
  w62  = (w24*w62);
  /* #301: @18 = (@18*@62) */
  w18 *= w62;
  /* #302: @85 = (@17*@85) */
  w85  = (w17*w85);
  /* #303: @83 = (@83*@93) */
  w83 *= w93;
  /* #304: @62 = (@22*@83) */
  w62  = (w22*w83);
  /* #305: @85 = (@85+@62) */
  w85 += w62;
  /* #306: @110 = (@110-@72) */
  w110 -= w72;
  /* #307: @72 = (@19*@110) */
  w72  = (w19*w110);
  /* #308: @85 = (@85+@72) */
  w85 += w72;
  /* #309: @67 = (@67-@117) */
  w67 -= w117;
  /* #310: @117 = (@14*@67) */
  w117  = (w14*w67);
  /* #311: @85 = (@85+@117) */
  w85 += w117;
  /* #312: @85 = (@24*@85) */
  w85  = (w24*w85);
  /* #313: @85 = (2.*@85) */
  w85 = (2.* w85 );
  /* #314: @18 = (@18+@85) */
  w18 += w85;
  /* #315: @47 = (@17*@47) */
  w47  = (w17*w47);
  /* #316: @45 = (@45*@55) */
  w45 *= w55;
  /* #317: @85 = (@22*@45) */
  w85  = (w22*w45);
  /* #318: @47 = (@47+@85) */
  w47 += w85;
  /* #319: @118 = (@118-@34) */
  w118 -= w34;
  /* #320: @34 = (@19*@118) */
  w34  = (w19*w118);
  /* #321: @47 = (@47+@34) */
  w47 += w34;
  /* #322: @31 = (@31-@121) */
  w31 -= w121;
  /* #323: @121 = (@14*@31) */
  w121  = (w14*w31);
  /* #324: @47 = (@47+@121) */
  w47 += w121;
  /* #325: @24 = (@24*@47) */
  w24 *= w47;
  /* #326: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #327: @18 = (@18+@24) */
  w18 += w24;
  /* #328: @14 = (@14*@18) */
  w14 *= w18;
  /* #329: @26 = (@26+@14) */
  w26 += w14;
  /* #330: @14 = (@87+@26) */
  w14  = (w87+w26);
  /* #331: (@100[3] = @14) */
  for (rr=w100+3, ss=(&w14); rr!=w100+4; rr+=1) *rr = *ss++;
  /* #332: @43 = (@29*@43) */
  w43  = (w29*w43);
  /* #333: @43 = (-@43) */
  w43 = (- w43 );
  /* #334: @81 = (@66*@81) */
  w81  = (w66*w81);
  /* #335: @43 = (@43-@81) */
  w43 -= w81;
  /* #336: @28 = (@28*@27) */
  w28 *= w27;
  /* #337: @43 = (@43-@28) */
  w43 -= w28;
  /* #338: @83 = (@64*@83) */
  w83  = (w64*w83);
  /* #339: @45 = (@23*@45) */
  w45  = (w23*w45);
  /* #340: @83 = (@83+@45) */
  w83 += w45;
  /* #341: @19 = (@19*@18) */
  w19 *= w18;
  /* #342: @83 = (@83-@19) */
  w83 -= w19;
  /* #343: @19 = (@43+@83) */
  w19  = (w43+w83);
  /* #344: (@100[4] = @19) */
  for (rr=w100+4, ss=(&w19); rr!=w100+5; rr+=1) *rr = *ss++;
  /* #345: @19 = cos(@56) */
  w19 = cos( w56 );
  /* #346: @1 = (@1*@68) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) *= w68;
  /* #347: @69 = dense(@1) */
  casadi_densify(w1, casadi_s21, w69, 0);
  /* #348: {@68, @45, NULL, NULL, @28, NULL} = vertsplit(@69) */
  w68 = w69[0];
  w45 = w69[1];
  w28 = w69[4];
  /* #349: @81 = (@32*@45) */
  w81  = (w32*w45);
  /* #350: @19 = (@19*@81) */
  w19 *= w81;
  /* #351: @56 = sin(@56) */
  w56 = sin( w56 );
  /* #352: @32 = (@32*@68) */
  w32 *= w68;
  /* #353: @56 = (@56*@32) */
  w56 *= w32;
  /* #354: @19 = (@19-@56) */
  w19 -= w56;
  /* #355: (@100[5] = @19) */
  for (rr=w100+5, ss=(&w19); rr!=w100+6; rr+=1) *rr = *ss++;
  /* #356: @63 = (@63*@45) */
  w63 *= w45;
  /* #357: @61 = (@61*@68) */
  w61 *= w68;
  /* #358: @63 = (@63+@61) */
  w63 += w61;
  /* #359: (@100[6] = @63) */
  for (rr=w100+6, ss=(&w63); rr!=w100+7; rr+=1) *rr = *ss++;
  /* #360: @0 = (@0+@108) */
  w0 += w108;
  /* #361: @0 = (@0+@116) */
  w0 += w116;
  /* #362: @0 = (@0+@49) */
  w0 += w49;
  /* #363: @0 = (@0+@111) */
  w0 += w111;
  /* #364: @0 = (@0+@113) */
  w0 += w113;
  /* #365: @0 = (@0+@120) */
  w0 += w120;
  /* #366: @0 = (@0+@78) */
  w0 += w78;
  /* #367: @37 = 00 */
  /* #368: @83 = (-@83) */
  w83 = (- w83 );
  /* #369: @83 = (@83-@43) */
  w83 -= w43;
  /* #370: {@43, NULL} = adj1_yr(@2, @8, @37, @83) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w83);
  res1[0]=(&w43);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #371: @0 = (@0+@43) */
  w0 += w43;
  /* #372: @37 = 00 */
  /* #373: @26 = (-@26) */
  w26 = (- w26 );
  /* #374: @26 = (@26-@87) */
  w26 -= w87;
  /* #375: {@87, NULL} = adj1_xr(@2, @3, @37, @26) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w26);
  res1[0]=(&w87);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #376: @0 = (@0+@87) */
  w0 += w87;
  /* #377: @37 = 00 */
  /* #378: @107 = (@80*@107) */
  w107  = (w80*w107);
  /* #379: @87 = (@107/@65) */
  w87  = (w107/w65);
  /* #380: @26 = (2.*@12) */
  w26 = (2.* w12 );
  /* #381: @71 = (@71/@65) */
  w71 /= w65;
  /* #382: @80 = (@80*@109) */
  w80 *= w109;
  /* #383: @71 = (@71*@80) */
  w71 *= w80;
  /* #384: @88 = (@88/@65) */
  w88 /= w65;
  /* #385: @88 = (@88*@107) */
  w88 *= w107;
  /* #386: @71 = (@71-@88) */
  w71 -= w88;
  /* #387: @26 = (@26*@71) */
  w26 *= w71;
  /* #388: @87 = (@87+@26) */
  w87 += w26;
  /* #389: @112 = (@42*@112) */
  w112  = (w42*w112);
  /* #390: @26 = (@112/@25) */
  w26  = (w112/w25);
  /* #391: @87 = (@87+@26) */
  w87 += w26;
  /* #392: @26 = (2.*@12) */
  w26 = (2.* w12 );
  /* #393: @33 = (@33/@25) */
  w33 /= w25;
  /* #394: @42 = (@42*@114) */
  w42 *= w114;
  /* #395: @33 = (@33*@42) */
  w33 *= w42;
  /* #396: @50 = (@50/@25) */
  w50 /= w25;
  /* #397: @50 = (@50*@112) */
  w50 *= w112;
  /* #398: @33 = (@33-@50) */
  w33 -= w50;
  /* #399: @26 = (@26*@33) */
  w26 *= w33;
  /* #400: @87 = (@87+@26) */
  w87 += w26;
  /* #401: @26 = sq(@7) */
  w26 = casadi_sq( w7 );
  /* #402: @50 = sq(@12) */
  w50 = casadi_sq( w12 );
  /* #403: @26 = (@26+@50) */
  w26 += w50;
  /* #404: @50 = (@7/@26) */
  w50  = (w7/w26);
  /* #405: @112 = cos(@13) */
  w112 = cos( w13 );
  /* #406: @84 = (@84*@93) */
  w84 *= w93;
  /* #407: @112 = (@112*@84) */
  w112 *= w84;
  /* #408: @84 = sin(@13) */
  w84 = sin( w13 );
  /* #409: @86 = (@86*@93) */
  w86 *= w93;
  /* #410: @84 = (@84*@86) */
  w84 *= w86;
  /* #411: @112 = (@112-@84) */
  w112 -= w84;
  /* #412: @84 = sin(@13) */
  w84 = sin( w13 );
  /* #413: @82 = (@82*@93) */
  w82 *= w93;
  /* #414: @84 = (@84*@82) */
  w84 *= w82;
  /* #415: @112 = (@112+@84) */
  w112 += w84;
  /* #416: @84 = cos(@13) */
  w84 = cos( w13 );
  /* #417: @79 = (@79*@93) */
  w79 *= w93;
  /* #418: @84 = (@84*@79) */
  w84 *= w79;
  /* #419: @112 = (@112+@84) */
  w112 += w84;
  /* #420: @84 = sin(@13) */
  w84 = sin( w13 );
  /* #421: @48 = (@48*@55) */
  w48 *= w55;
  /* #422: @84 = (@84*@48) */
  w84 *= w48;
  /* #423: @112 = (@112-@84) */
  w112 -= w84;
  /* #424: @84 = cos(@13) */
  w84 = cos( w13 );
  /* #425: @46 = (@46*@55) */
  w46 *= w55;
  /* #426: @84 = (@84*@46) */
  w84 *= w46;
  /* #427: @112 = (@112+@84) */
  w112 += w84;
  /* #428: @84 = sin(@13) */
  w84 = sin( w13 );
  /* #429: @44 = (@44*@55) */
  w44 *= w55;
  /* #430: @84 = (@84*@44) */
  w84 *= w44;
  /* #431: @112 = (@112+@84) */
  w112 += w84;
  /* #432: @84 = cos(@13) */
  w84 = cos( w13 );
  /* #433: @41 = (@41*@55) */
  w41 *= w55;
  /* #434: @84 = (@84*@41) */
  w84 *= w41;
  /* #435: @112 = (@112+@84) */
  w112 += w84;
  /* #436: @84 = cos(@13) */
  w84 = cos( w13 );
  /* #437: @115 = (@66*@115) */
  w115  = (w66*w115);
  /* #438: @119 = (@29*@119) */
  w119  = (w29*w119);
  /* #439: @115 = (@115+@119) */
  w115 += w119;
  /* #440: @21 = (@21*@27) */
  w21 *= w27;
  /* #441: @115 = (@115-@21) */
  w115 -= w21;
  /* #442: @84 = (@84*@115) */
  w84 *= w115;
  /* #443: @112 = (@112+@84) */
  w112 += w84;
  /* #444: @84 = sin(@13) */
  w84 = sin( w13 );
  /* #445: @66 = (@66*@99) */
  w66 *= w99;
  /* #446: @29 = (@29*@94) */
  w29 *= w94;
  /* #447: @66 = (@66+@29) */
  w66 += w29;
  /* #448: @16 = (@16*@27) */
  w16 *= w27;
  /* #449: @66 = (@66-@16) */
  w66 -= w16;
  /* #450: @84 = (@84*@66) */
  w84 *= w66;
  /* #451: @112 = (@112-@84) */
  w112 -= w84;
  /* #452: @84 = sin(@13) */
  w84 = sin( w13 );
  /* #453: @110 = (@64*@110) */
  w110  = (w64*w110);
  /* #454: @118 = (@23*@118) */
  w118  = (w23*w118);
  /* #455: @110 = (@110+@118) */
  w110 += w118;
  /* #456: @22 = (@22*@18) */
  w22 *= w18;
  /* #457: @110 = (@110-@22) */
  w110 -= w22;
  /* #458: @84 = (@84*@110) */
  w84 *= w110;
  /* #459: @112 = (@112-@84) */
  w112 -= w84;
  /* #460: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #461: @64 = (@64*@67) */
  w64 *= w67;
  /* #462: @23 = (@23*@31) */
  w23 *= w31;
  /* #463: @64 = (@64+@23) */
  w64 += w23;
  /* #464: @17 = (@17*@18) */
  w17 *= w18;
  /* #465: @64 = (@64+@17) */
  w64 += w17;
  /* #466: @13 = (@13*@64) */
  w13 *= w64;
  /* #467: @112 = (@112+@13) */
  w112 += w13;
  /* #468: @50 = (@50*@112) */
  w50 *= w112;
  /* #469: @87 = (@87-@50) */
  w87 -= w50;
  /* #470: {@50, NULL, NULL, NULL, NULL} = adj1_fwd1_yr(@2, @8, @9, @10, @11, @37, @87) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  arg1[5]=0;
  arg1[6]=(&w87);
  res1[0]=(&w50);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #471: @0 = (@0+@50) */
  w0 += w50;
  /* #472: @9 = 00 */
  /* #473: @50 = (2.*@7) */
  w50 = (2.* w7 );
  /* #474: @50 = (@50*@71) */
  w50 *= w71;
  /* #475: @80 = (@80/@65) */
  w80 /= w65;
  /* #476: @50 = (@50-@80) */
  w50 -= w80;
  /* #477: @42 = (@42/@25) */
  w42 /= w25;
  /* #478: @50 = (@50-@42) */
  w50 -= w42;
  /* #479: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #480: @7 = (@7*@33) */
  w7 *= w33;
  /* #481: @50 = (@50+@7) */
  w50 += w7;
  /* #482: @12 = (@12/@26) */
  w12 /= w26;
  /* #483: @12 = (@12*@112) */
  w12 *= w112;
  /* #484: @50 = (@50+@12) */
  w50 += w12;
  /* #485: {@12, NULL, NULL, NULL, NULL} = adj1_fwd1_xr(@2, @3, @4, @5, @6, @9, @50) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  arg1[5]=0;
  arg1[6]=(&w50);
  res1[0]=(&w12);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #486: @0 = (@0+@12) */
  w0 += w12;
  /* #487: (@100[7] = @0) */
  for (rr=w100+7, ss=(&w0); rr!=w100+8; rr+=1) *rr = *ss++;
  /* #488: (@100[8] = @28) */
  for (rr=w100+8, ss=(&w28); rr!=w100+9; rr+=1) *rr = *ss++;
  /* #489: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #490: @28 = ones(2x1,1nz) */
  w28 = 1.;
  /* #491: {NULL, @0} = vertsplit(@28) */
  w0 = w28;
  /* #492: @15 = (@15*@0) */
  w15 *= w0;
  /* #493: (@100[9] = @15) */
  for (rr=w100+9, ss=(&w15); rr!=w100+10; rr+=1) *rr = *ss++;
  /* #494: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #495: @20 = (@20*@0) */
  w20 *= w0;
  /* #496: (@100[10] = @20) */
  for (rr=w100+10, ss=(&w20); rr!=w100+11; rr+=1) *rr = *ss++;
  /* #497: output[1][0] = @100 */
  casadi_copy(w100, 11, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s22;
    case 2: return casadi_s23;
    case 3: return casadi_s24;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s25;
    case 1: return casadi_s26;
    case 2: return casadi_s27;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 295;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
