/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_model_mpcc_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[33] = {11, 10, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10};
static const casadi_int casadi_s2[25] = {1, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[1] = {1};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[2] = {0, 13};
static const casadi_int casadi_s7[1] = {3};
static const casadi_int casadi_s8[2] = {0, 15};
static const casadi_int casadi_s9[21] = {1, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s10[30] = {10, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9};
static const casadi_int casadi_s11[2] = {0, 11};
static const casadi_int casadi_s12[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s13[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s14[12] = {1, 6, 0, 1, 2, 2, 2, 3, 3, 0, 0, 0};
static const casadi_int casadi_s15[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s16[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s17[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s18[3] = {0, 0, 0};
static const casadi_int casadi_s19[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s20[6] = {2, 1, 0, 2, 0, 1};

static const casadi_real casadi_c0[20] = {-3.7500000000000000e+00, 3.7500000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000000e+00, 1.8750000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000004e+00, 1.8750000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -3.7500000000000009e+00, 3.7500000000000009e+00};
static const casadi_real casadi_c1[13] = {0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4.};
static const casadi_real casadi_c2[15] = {0., 0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4., 4.};
static const casadi_real casadi_c3[18] = {-2.5000000000000000e+00, 2.5000000000000000e+00, -1.6666666666666665e+00, 1.6666666666666665e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -1.6666666666666670e+00, 1.6666666666666670e+00, -2.5000000000000004e+00, 2.5000000000000004e+00};
static const casadi_real casadi_c4[11] = {0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4.};
static const casadi_real casadi_c5[18] = {0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.};

/* fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* xr:(i0,i1[11])->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* yr:(i0,i1[11])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* adj1_yr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_xr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* adj1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* unicycle_model_mpcc_constr_h_fun:(i0[6],i1[3],i2[],i3[46])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4;
  casadi_real w0, *w1=w+80, w2, *w3=w+84, w5, *w6=w+96, w7, *w8=w+108, w10, *w11=w+120, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, *w36=w+154, *w37=w+160, *w38=w+163;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(6x1,3nz) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = input[3][0] */
  casadi_copy(arg[3], 11, w3);
  /* #4: @4 = 00 */
  /* #5: @5 = 1 */
  w5 = 1.;
  /* #6: @6 = zeros(11x1) */
  casadi_clear(w6, 11);
  /* #7: @7 = fwd1_xr(@2, @3, @4, @5, @6) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  res1[0]=(&w7);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: @8 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+11 : 0, 11, w8);
  /* #9: @9 = 00 */
  /* #10: @10 = 1 */
  w10 = 1.;
  /* #11: @11 = zeros(11x1) */
  casadi_clear(w11, 11);
  /* #12: @12 = fwd1_yr(@2, @8, @9, @10, @11) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  res1[0]=(&w12);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #13: @13 = atan2(@7,@12) */
  w13  = atan2(w7,w12);
  /* #14: @14 = sin(@13) */
  w14 = sin( w13 );
  /* #15: @15 = input[0][0] */
  w15 = arg[0] ? arg[0][0] : 0;
  /* #16: @16 = xr(@2, @3) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  res1[0]=(&w16);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #17: @17 = (@15-@16) */
  w17  = (w15-w16);
  /* #18: @18 = (@14*@17) */
  w18  = (w14*w17);
  /* #19: @19 = cos(@13) */
  w19 = cos( w13 );
  /* #20: @20 = input[0][1] */
  w20 = arg[0] ? arg[0][1] : 0;
  /* #21: @21 = yr(@2, @8) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  res1[0]=(&w21);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #22: @22 = (@20-@21) */
  w22  = (w20-w21);
  /* #23: @23 = (@19*@22) */
  w23  = (w19*w22);
  /* #24: @18 = (@18-@23) */
  w18 -= w23;
  /* #25: @23 = (2.*@18) */
  w23 = (2.* w18 );
  /* #26: @24 = input[3][9] */
  w24 = arg[3] ? arg[3][41] : 0;
  /* #27: @23 = (@23*@24) */
  w23 *= w24;
  /* #28: @25 = (@14*@23) */
  w25  = (w14*w23);
  /* #29: @26 = cos(@13) */
  w26 = cos( w13 );
  /* #30: @16 = (@15-@16) */
  w16  = (w15-w16);
  /* #31: @27 = (@26*@16) */
  w27  = (w26*w16);
  /* #32: @27 = (-@27) */
  w27 = (- w27 );
  /* #33: @28 = sin(@13) */
  w28 = sin( w13 );
  /* #34: @21 = (@20-@21) */
  w21  = (w20-w21);
  /* #35: @29 = (@28*@21) */
  w29  = (w28*w21);
  /* #36: @27 = (@27-@29) */
  w27 -= w29;
  /* #37: @29 = (2.*@27) */
  w29 = (2.* w27 );
  /* #38: @30 = input[3][10] */
  w30 = arg[3] ? arg[3][42] : 0;
  /* #39: @29 = (@29*@30) */
  w29 *= w30;
  /* #40: @31 = (@26*@29) */
  w31  = (w26*w29);
  /* #41: @32 = (@25-@31) */
  w32  = (w25-w31);
  /* #42: (@1[0] = @32) */
  for (rr=w1+0, ss=(&w32); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #43: @32 = (@19*@23) */
  w32  = (w19*w23);
  /* #44: @33 = (-@32) */
  w33 = (- w32 );
  /* #45: @34 = (@28*@29) */
  w34  = (w28*w29);
  /* #46: @33 = (@33-@34) */
  w33 -= w34;
  /* #47: (@1[1] = @33) */
  for (rr=w1+1, ss=(&w33); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #48: @35 = 00 */
  /* #49: @34 = (@34+@32) */
  w34 += w32;
  /* #50: {@32, NULL} = adj1_yr(@2, @8, @35, @34) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w34);
  res1[0]=(&w32);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #51: @35 = 00 */
  /* #52: @31 = (@31-@25) */
  w31 -= w25;
  /* #53: {@25, NULL} = adj1_xr(@2, @3, @35, @31) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w31);
  res1[0]=(&w25);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #54: @32 = (@32+@25) */
  w32 += w25;
  /* #55: @35 = 00 */
  /* #56: @25 = sq(@7) */
  w25 = casadi_sq( w7 );
  /* #57: @31 = sq(@12) */
  w31 = casadi_sq( w12 );
  /* #58: @25 = (@25+@31) */
  w25 += w31;
  /* #59: @31 = (@7/@25) */
  w31  = (w7/w25);
  /* #60: @34 = sin(@13) */
  w34 = sin( w13 );
  /* #61: @33 = (@16*@29) */
  w33  = (w16*w29);
  /* #62: @34 = (@34*@33) */
  w34 *= w33;
  /* #63: @33 = cos(@13) */
  w33 = cos( w13 );
  /* #64: @29 = (@21*@29) */
  w29  = (w21*w29);
  /* #65: @33 = (@33*@29) */
  w33 *= w29;
  /* #66: @34 = (@34-@33) */
  w34 -= w33;
  /* #67: @33 = sin(@13) */
  w33 = sin( w13 );
  /* #68: @29 = (@22*@23) */
  w29  = (w22*w23);
  /* #69: @33 = (@33*@29) */
  w33 *= w29;
  /* #70: @34 = (@34+@33) */
  w34 += w33;
  /* #71: @33 = cos(@13) */
  w33 = cos( w13 );
  /* #72: @23 = (@17*@23) */
  w23  = (w17*w23);
  /* #73: @33 = (@33*@23) */
  w33 *= w23;
  /* #74: @34 = (@34+@33) */
  w34 += w33;
  /* #75: @31 = (@31*@34) */
  w31 *= w34;
  /* #76: @31 = (-@31) */
  w31 = (- w31 );
  /* #77: {@33, NULL, NULL, NULL, NULL} = adj1_fwd1_yr(@2, @8, @9, @10, @11, @35, @31) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  arg1[5]=0;
  arg1[6]=(&w31);
  res1[0]=(&w33);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #78: @32 = (@32+@33) */
  w32 += w33;
  /* #79: @35 = 00 */
  /* #80: @25 = (@12/@25) */
  w25  = (w12/w25);
  /* #81: @25 = (@25*@34) */
  w25 *= w34;
  /* #82: {@34, NULL, NULL, NULL, NULL} = adj1_fwd1_xr(@2, @3, @4, @5, @6, @35, @25) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  arg1[5]=0;
  arg1[6]=(&w25);
  res1[0]=(&w34);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #83: @32 = (@32+@34) */
  w32 += w34;
  /* #84: (@1[2] = @32) */
  for (rr=w1+2, ss=(&w32); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #85: @1 = @1' */
  /* #86: @32 = input[0][3] */
  w32 = arg[0] ? arg[0][3] : 0;
  /* #87: @34 = input[0][2] */
  w34 = arg[0] ? arg[0][2] : 0;
  /* #88: @25 = cos(@34) */
  w25 = cos( w34 );
  /* #89: @25 = (@32*@25) */
  w25  = (w32*w25);
  /* #90: @34 = sin(@34) */
  w34 = sin( w34 );
  /* #91: @32 = (@32*@34) */
  w32 *= w34;
  /* #92: @34 = 0 */
  w34 = 0.;
  /* #93: @33 = 0 */
  w33 = 0.;
  /* #94: @31 = input[0][5] */
  w31 = arg[0] ? arg[0][5] : 0;
  /* #95: @23 = 0 */
  w23 = 0.;
  /* #96: @36 = vertcat(@25, @32, @34, @33, @31, @23) */
  rr=w36;
  *rr++ = w25;
  *rr++ = w32;
  *rr++ = w34;
  *rr++ = w33;
  *rr++ = w31;
  *rr++ = w23;
  /* #97: @0 = mac(@1,@36,@0) */
  casadi_mtimes(w1, casadi_s14, w36, casadi_s13, (&w0), casadi_s12, w, 0);
  /* #98: @25 = 0 */
  w25 = 0.;
  /* #99: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #100: @37 = zeros(6x1,3nz) */
  casadi_clear(w37, 3);
  /* #101: @32 = (2.*@18) */
  w32 = (2.* w18 );
  /* #102: @32 = (@32*@24) */
  w32 *= w24;
  /* #103: @14 = (@14*@32) */
  w14 *= w32;
  /* #104: @34 = (2.*@27) */
  w34 = (2.* w27 );
  /* #105: @34 = (@34*@30) */
  w34 *= w30;
  /* #106: @26 = (@26*@34) */
  w26 *= w34;
  /* #107: @33 = (@14-@26) */
  w33  = (w14-w26);
  /* #108: (@37[0] = @33) */
  for (rr=w37+0, ss=(&w33); rr!=w37+1; rr+=1) *rr = *ss++;
  /* #109: @19 = (@19*@32) */
  w19 *= w32;
  /* #110: @33 = (-@19) */
  w33 = (- w19 );
  /* #111: @28 = (@28*@34) */
  w28 *= w34;
  /* #112: @33 = (@33-@28) */
  w33 -= w28;
  /* #113: (@37[1] = @33) */
  for (rr=w37+1, ss=(&w33); rr!=w37+2; rr+=1) *rr = *ss++;
  /* #114: @35 = 00 */
  /* #115: @28 = (@28+@19) */
  w28 += w19;
  /* #116: {@19, NULL} = adj1_yr(@2, @8, @35, @28) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w28);
  res1[0]=(&w19);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #117: @35 = 00 */
  /* #118: @26 = (@26-@14) */
  w26 -= w14;
  /* #119: {@14, NULL} = adj1_xr(@2, @3, @35, @26) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w26);
  res1[0]=(&w14);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #120: @19 = (@19+@14) */
  w19 += w14;
  /* #121: @35 = 00 */
  /* #122: @14 = sq(@7) */
  w14 = casadi_sq( w7 );
  /* #123: @26 = sq(@12) */
  w26 = casadi_sq( w12 );
  /* #124: @14 = (@14+@26) */
  w14 += w26;
  /* #125: @7 = (@7/@14) */
  w7 /= w14;
  /* #126: @26 = sin(@13) */
  w26 = sin( w13 );
  /* #127: @16 = (@16*@34) */
  w16 *= w34;
  /* #128: @26 = (@26*@16) */
  w26 *= w16;
  /* #129: @16 = cos(@13) */
  w16 = cos( w13 );
  /* #130: @21 = (@21*@34) */
  w21 *= w34;
  /* #131: @16 = (@16*@21) */
  w16 *= w21;
  /* #132: @26 = (@26-@16) */
  w26 -= w16;
  /* #133: @16 = sin(@13) */
  w16 = sin( w13 );
  /* #134: @22 = (@22*@32) */
  w22 *= w32;
  /* #135: @16 = (@16*@22) */
  w16 *= w22;
  /* #136: @26 = (@26+@16) */
  w26 += w16;
  /* #137: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #138: @17 = (@17*@32) */
  w17 *= w32;
  /* #139: @13 = (@13*@17) */
  w13 *= w17;
  /* #140: @26 = (@26+@13) */
  w26 += w13;
  /* #141: @7 = (@7*@26) */
  w7 *= w26;
  /* #142: @7 = (-@7) */
  w7 = (- w7 );
  /* #143: {@13, NULL, NULL, NULL, NULL} = adj1_fwd1_yr(@2, @8, @9, @10, @11, @35, @7) */
  arg1[0]=(&w2);
  arg1[1]=w8;
  arg1[2]=0;
  arg1[3]=(&w10);
  arg1[4]=w11;
  arg1[5]=0;
  arg1[6]=(&w7);
  res1[0]=(&w13);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #144: @19 = (@19+@13) */
  w19 += w13;
  /* #145: @9 = 00 */
  /* #146: @12 = (@12/@14) */
  w12 /= w14;
  /* #147: @12 = (@12*@26) */
  w12 *= w26;
  /* #148: {@26, NULL, NULL, NULL, NULL} = adj1_fwd1_xr(@2, @3, @4, @5, @6, @9, @12) */
  arg1[0]=(&w2);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=w6;
  arg1[5]=0;
  arg1[6]=(&w12);
  res1[0]=(&w26);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #149: @19 = (@19+@26) */
  w19 += w26;
  /* #150: (@37[2] = @19) */
  for (rr=w37+2, ss=(&w19); rr!=w37+3; rr+=1) *rr = *ss++;
  /* #151: @37 = @37' */
  /* #152: @38 = 
  [[0, 0, 0], 
   [0, 0, 0], 
   [0, 1, 0], 
   [1, 0, 0], 
   [0, 0, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c5, 18, w38);
  /* #153: @1 = mac(@37,@38,@1) */
  casadi_mtimes(w37, casadi_s14, w38, casadi_s16, w1, casadi_s15, w, 0);
  /* #154: @19 = input[1][0] */
  w19 = arg[1] ? arg[1][0] : 0;
  /* #155: @26 = input[1][1] */
  w26 = arg[1] ? arg[1][1] : 0;
  /* #156: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #157: @37 = vertcat(@19, @26, @2) */
  rr=w37;
  *rr++ = w19;
  *rr++ = w26;
  *rr++ = w2;
  /* #158: @25 = mac(@1,@37,@25) */
  for (i=0, rr=(&w25); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #159: @0 = (@0+@25) */
  w0 += w25;
  /* #160: @25 = input[3][11] */
  w25 = arg[3] ? arg[3][43] : 0;
  /* #161: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #162: @24 = (@24*@18) */
  w24 *= w18;
  /* #163: @27 = sq(@27) */
  w27 = casadi_sq( w27 );
  /* #164: @30 = (@30*@27) */
  w30 *= w27;
  /* #165: @24 = (@24+@30) */
  w24 += w30;
  /* #166: @25 = (@25*@24) */
  w25 *= w24;
  /* #167: @0 = (@0+@25) */
  w0 += w25;
  /* #168: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #169: @0 = input[3][12] */
  w0 = arg[3] ? arg[3][44] : 0;
  /* #170: @15 = (@15-@0) */
  w15 -= w0;
  /* #171: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #172: @0 = input[3][13] */
  w0 = arg[3] ? arg[3][45] : 0;
  /* #173: @20 = (@20-@0) */
  w20 -= w0;
  /* #174: @20 = sq(@20) */
  w20 = casadi_sq( w20 );
  /* #175: @15 = (@15+@20) */
  w15 += w20;
  /* #176: @20 = 0.140625 */
  w20 = 1.4062500000000000e-01;
  /* #177: @15 = (@15-@20) */
  w15 -= w20;
  /* #178: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_model_mpcc_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s17;
    case 2: return casadi_s18;
    case 3: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 181;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
