/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[33] = {11, 10, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10};
static const casadi_int casadi_s2[25] = {1, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[1] = {1};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[2] = {0, 13};
static const casadi_int casadi_s7[1] = {3};
static const casadi_int casadi_s8[2] = {0, 15};
static const casadi_int casadi_s9[21] = {1, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s10[30] = {10, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9};
static const casadi_int casadi_s11[2] = {0, 11};
static const casadi_int casadi_s12[19] = {1, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s13[27] = {9, 8, 0, 2, 4, 6, 8, 10, 12, 14, 16, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8};
static const casadi_int casadi_s14[2] = {0, 9};
static const casadi_int casadi_s15[11] = {9, 1, 0, 7, 0, 1, 2, 3, 4, 7, 8};
static const casadi_int casadi_s16[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[6] = {0, 1, 2, 3, 6, 9};
static const casadi_int casadi_s18[24] = {9, 9, 0, 1, 2, 3, 6, 9, 9, 9, 12, 12, 0, 1, 2, 3, 4, 7, 3, 4, 7, 3, 4, 7};
static const casadi_int casadi_s19[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s20[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s21[4] = {0, 1, 0, 0};
static const casadi_int casadi_s22[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s23[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s24[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s25[3] = {0, 0, 0};
static const casadi_int casadi_s26[12] = {0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[20] = {-3.7500000000000000e+00, 3.7500000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000000e+00, 1.8750000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000004e+00, 1.8750000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -3.7500000000000009e+00, 3.7500000000000009e+00};
static const casadi_real casadi_c1[13] = {0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4.};
static const casadi_real casadi_c2[15] = {0., 0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4., 4.};
static const casadi_real casadi_c3[18] = {-2.5000000000000000e+00, 2.5000000000000000e+00, -1.6666666666666665e+00, 1.6666666666666665e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -1.6666666666666670e+00, 1.6666666666666670e+00, -2.5000000000000004e+00, 2.5000000000000004e+00};
static const casadi_real casadi_c4[11] = {0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4.};
static const casadi_real casadi_c5[16] = {-1.2500000000000000e+00, 1.2500000000000000e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.4999999999999978e+00, 2.4999999999999978e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -1.2500000000000002e+00, 1.2500000000000002e+00};
static const casadi_real casadi_c6[9] = {0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4.};

/* fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* xr:(i0,i1[11])->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* yr:(i0,i1[11])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* adj1_yr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_xr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* adj1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* fwd1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],fwd_i0,fwd_i1[11],fwd_out_o0[1x1,0nz],fwd_fwd_i0,fwd_fwd_i1[11])->(fwd_fwd_o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+9, *w3=w+18, *w4=w+28, *w5=w+39, *w6=w+59, w7, w8;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x9) */
  casadi_clear(w2, 9);
  /* #3: @3 = zeros(1x10) */
  casadi_clear(w3, 10);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 11, w4);
  /* #5: @4 = @4' */
  /* #6: @5 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes(w4, casadi_s2, w5, casadi_s1, w3, casadi_s0, w, 0);
  /* #8: @6 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w6);
  /* #9: @2 = mac(@3,@6,@2) */
  casadi_mtimes(w3, casadi_s0, w6, casadi_s10, w2, casadi_s9, w, 0);
  /* #10: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w2,1,(&w1),casadi_s3, iw, w);
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @0 = (@0*@7) */
  w0 *= w7;
  /* #14: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w3,1,(&w1),casadi_s3, iw, w);
  /* #15: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #16: @7 = (@7*@1) */
  w7 *= w1;
  /* #17: @0 = (@0+@7) */
  w0 += w7;
  /* #18: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],fwd_i0,fwd_i1[11],fwd_out_o0[1x1,0nz],fwd_fwd_i0,fwd_fwd_i1[11])->(fwd_fwd_o0) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+9, *w3=w+18, *w4=w+28, *w5=w+39, *w6=w+59, w7, w8;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x9) */
  casadi_clear(w2, 9);
  /* #3: @3 = zeros(1x10) */
  casadi_clear(w3, 10);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 11, w4);
  /* #5: @4 = @4' */
  /* #6: @5 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes(w4, casadi_s2, w5, casadi_s1, w3, casadi_s0, w, 0);
  /* #8: @6 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w6);
  /* #9: @2 = mac(@3,@6,@2) */
  casadi_mtimes(w3, casadi_s0, w6, casadi_s10, w2, casadi_s9, w, 0);
  /* #10: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w2,1,(&w1),casadi_s3, iw, w);
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @0 = (@0*@7) */
  w0 *= w7;
  /* #14: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w3,1,(&w1),casadi_s3, iw, w);
  /* #15: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #16: @7 = (@7*@1) */
  w7 *= w1;
  /* #17: @0 = (@0+@7) */
  w0 += w7;
  /* #18: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd3_adj1_yr:(i0,i1[11],out_o0[1x1,0nz],adj_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],fwd_i0[1x3],fwd_i1[11x3],fwd_out_o0[1x3,0nz],fwd_adj_o0[1x3])->(fwd_adj_i0[1x3],fwd_adj_i1[11x3,0nz]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+9, *w3=w+18, *w4=w+28, *w5=w+39, *w6=w+59, w7, w8, w9;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x9) */
  casadi_clear(w2, 9);
  /* #3: @3 = zeros(1x10) */
  casadi_clear(w3, 10);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 11, w4);
  /* #5: @4 = @4' */
  /* #6: @5 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes(w4, casadi_s2, w5, casadi_s1, w3, casadi_s0, w, 0);
  /* #8: @6 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w6);
  /* #9: @2 = mac(@3,@6,@2) */
  casadi_mtimes(w3, casadi_s0, w6, casadi_s10, w2, casadi_s9, w, 0);
  /* #10: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w2,1,(&w1),casadi_s3, iw, w);
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #13: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #14: @9 = BSplineParametric(@1) */
  casadi_clear((&w9), 1);
  CASADI_PREFIX(nd_boor_eval)((&w9),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w3,1,(&w1),casadi_s3, iw, w);
  /* #15: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #16: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #17: @8 = (@8+@1) */
  w8 += w1;
  /* #18: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  /* #19: @8 = input[6][1] */
  w8 = arg[6] ? arg[6][1] : 0;
  /* #20: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #21: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #22: @1 = input[9][1] */
  w1 = arg[9] ? arg[9][1] : 0;
  /* #23: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #24: @8 = (@8+@1) */
  w8 += w1;
  /* #25: output[0][1] = @8 */
  if (res[0]) res[0][1] = w8;
  /* #26: @8 = input[6][2] */
  w8 = arg[6] ? arg[6][2] : 0;
  /* #27: @7 = (@7*@8) */
  w7 *= w8;
  /* #28: @0 = (@0*@7) */
  w0 *= w7;
  /* #29: @7 = input[9][2] */
  w7 = arg[9] ? arg[9][2] : 0;
  /* #30: @9 = (@9*@7) */
  w9 *= w7;
  /* #31: @0 = (@0+@9) */
  w0 += w9;
  /* #32: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

/* fwd3_adj1_xr:(i0,i1[11],out_o0[1x1,0nz],adj_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],fwd_i0[1x3],fwd_i1[11x3],fwd_out_o0[1x3,0nz],fwd_adj_o0[1x3])->(fwd_adj_i0[1x3],fwd_adj_i1[11x3,0nz]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+9, *w3=w+18, *w4=w+28, *w5=w+39, *w6=w+59, w7, w8, w9;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x9) */
  casadi_clear(w2, 9);
  /* #3: @3 = zeros(1x10) */
  casadi_clear(w3, 10);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 11, w4);
  /* #5: @4 = @4' */
  /* #6: @5 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes(w4, casadi_s2, w5, casadi_s1, w3, casadi_s0, w, 0);
  /* #8: @6 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w6);
  /* #9: @2 = mac(@3,@6,@2) */
  casadi_mtimes(w3, casadi_s0, w6, casadi_s10, w2, casadi_s9, w, 0);
  /* #10: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w2,1,(&w1),casadi_s3, iw, w);
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #13: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #14: @9 = BSplineParametric(@1) */
  casadi_clear((&w9), 1);
  CASADI_PREFIX(nd_boor_eval)((&w9),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w3,1,(&w1),casadi_s3, iw, w);
  /* #15: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #16: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #17: @8 = (@8+@1) */
  w8 += w1;
  /* #18: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  /* #19: @8 = input[6][1] */
  w8 = arg[6] ? arg[6][1] : 0;
  /* #20: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #21: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #22: @1 = input[9][1] */
  w1 = arg[9] ? arg[9][1] : 0;
  /* #23: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #24: @8 = (@8+@1) */
  w8 += w1;
  /* #25: output[0][1] = @8 */
  if (res[0]) res[0][1] = w8;
  /* #26: @8 = input[6][2] */
  w8 = arg[6] ? arg[6][2] : 0;
  /* #27: @7 = (@7*@8) */
  w7 *= w8;
  /* #28: @0 = (@0*@7) */
  w0 *= w7;
  /* #29: @7 = input[9][2] */
  w7 = arg[9] ? arg[9][2] : 0;
  /* #30: @9 = (@9*@7) */
  w9 *= w7;
  /* #31: @0 = (@0+@9) */
  w0 += w9;
  /* #32: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

/* fwd3_adj1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],out_adj_out_o0[1x1,0nz],out_adj_fwd_i0[1x1,0nz],out_adj_fwd_i1[11x1,0nz],fwd_i0[1x3],fwd_i1[11x3],fwd_out_o0[1x3,0nz],fwd_fwd_i0[1x3],fwd_fwd_i1[11x3],fwd_out_fwd_o0[1x3,0nz],fwd_adj_fwd_o0[1x3])->(fwd_adj_i0[1x3],fwd_adj_i1[11x3,0nz],fwd_adj_out_o0[1x3,0nz],fwd_adj_fwd_i0[1x3],fwd_adj_fwd_i1[11x3,0nz]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, *w4=w+11, *w5=w+19, *w6=w+28, *w7=w+38, *w8=w+49, *w9=w+69, *w10=w+87, w11, w12, w13, w14, w15, w16, w17, w18, w19;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = zeros(1x8) */
  casadi_clear(w4, 8);
  /* #5: @5 = zeros(1x9) */
  casadi_clear(w5, 9);
  /* #6: @6 = zeros(1x10) */
  casadi_clear(w6, 10);
  /* #7: @7 = input[1][0] */
  casadi_copy(arg[1], 11, w7);
  /* #8: @7 = @7' */
  /* #9: @8 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w8);
  /* #10: @6 = mac(@7,@8,@6) */
  casadi_mtimes(w7, casadi_s2, w8, casadi_s1, w6, casadi_s0, w, 0);
  /* #11: @9 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w9);
  /* #12: @5 = mac(@6,@9,@5) */
  casadi_mtimes(w6, casadi_s0, w9, casadi_s10, w5, casadi_s9, w, 0);
  /* #13: @10 = 
  [[-1.25, 00, 00, 00, 00, 00, 00, 00], 
   [1.25, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.25], 
   [00, 00, 00, 00, 00, 00, 00, 1.25]] */
  casadi_copy(casadi_c5, 16, w10);
  /* #14: @4 = mac(@5,@10,@4) */
  casadi_mtimes(w5, casadi_s9, w10, casadi_s13, w4, casadi_s12, w, 0);
  /* #15: @11 = BSplineParametric(@3) */
  casadi_clear((&w11), 1);
  CASADI_PREFIX(nd_boor_eval)((&w11),1,casadi_c6,casadi_s14,casadi_s3,casadi_s4,w4,1,(&w3),casadi_s3, iw, w);
  /* #16: @12 = input[12][0] */
  w12 = arg[12] ? arg[12][0] : 0;
  /* #17: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #18: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #19: @14 = BSplineParametric(@3) */
  casadi_clear((&w14), 1);
  CASADI_PREFIX(nd_boor_eval)((&w14),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w5,1,(&w3),casadi_s3, iw, w);
  /* #20: @15 = input[15][0] */
  w15 = arg[15] ? arg[15][0] : 0;
  /* #21: @15 = (@1*@15) */
  w15  = (w1*w15);
  /* #22: @16 = input[18][0] */
  w16 = arg[18] ? arg[18][0] : 0;
  /* #23: @17 = (@0*@16) */
  w17  = (w0*w16);
  /* #24: @15 = (@15+@17) */
  w15 += w17;
  /* #25: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #26: @13 = (@13+@15) */
  w13 += w15;
  /* #27: output[0][0] = @13 */
  if (res[0]) res[0][0] = w13;
  /* #28: @13 = input[12][1] */
  w13 = arg[12] ? arg[12][1] : 0;
  /* #29: @15 = (@11*@13) */
  w15  = (w11*w13);
  /* #30: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #31: @17 = input[15][1] */
  w17 = arg[15] ? arg[15][1] : 0;
  /* #32: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #33: @18 = input[18][1] */
  w18 = arg[18] ? arg[18][1] : 0;
  /* #34: @19 = (@0*@18) */
  w19  = (w0*w18);
  /* #35: @17 = (@17+@19) */
  w17 += w19;
  /* #36: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #37: @15 = (@15+@17) */
  w15 += w17;
  /* #38: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  /* #39: @15 = input[12][2] */
  w15 = arg[12] ? arg[12][2] : 0;
  /* #40: @11 = (@11*@15) */
  w11 *= w15;
  /* #41: @2 = (@2*@11) */
  w2 *= w11;
  /* #42: @11 = input[15][2] */
  w11 = arg[15] ? arg[15][2] : 0;
  /* #43: @11 = (@1*@11) */
  w11  = (w1*w11);
  /* #44: @17 = input[18][2] */
  w17 = arg[18] ? arg[18][2] : 0;
  /* #45: @0 = (@0*@17) */
  w0 *= w17;
  /* #46: @11 = (@11+@0) */
  w11 += w0;
  /* #47: @11 = (@14*@11) */
  w11  = (w14*w11);
  /* #48: @2 = (@2+@11) */
  w2 += w11;
  /* #49: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #50: @12 = (@14*@12) */
  w12  = (w14*w12);
  /* #51: @12 = (@1*@12) */
  w12  = (w1*w12);
  /* #52: @2 = BSplineParametric(@3) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w6,1,(&w3),casadi_s3, iw, w);
  /* #53: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #54: @12 = (@12+@16) */
  w12 += w16;
  /* #55: output[3][0] = @12 */
  if (res[3]) res[3][0] = w12;
  /* #56: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #57: @13 = (@1*@13) */
  w13  = (w1*w13);
  /* #58: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #59: @13 = (@13+@18) */
  w13 += w18;
  /* #60: output[3][1] = @13 */
  if (res[3]) res[3][1] = w13;
  /* #61: @14 = (@14*@15) */
  w14 *= w15;
  /* #62: @1 = (@1*@14) */
  w1 *= w14;
  /* #63: @2 = (@2*@17) */
  w2 *= w17;
  /* #64: @1 = (@1+@2) */
  w1 += w2;
  /* #65: output[3][2] = @1 */
  if (res[3]) res[3][2] = w1;
  return 0;
}

/* fwd3_adj1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],out_adj_out_o0[1x1,0nz],out_adj_fwd_i0[1x1,0nz],out_adj_fwd_i1[11x1,0nz],fwd_i0[1x3],fwd_i1[11x3],fwd_out_o0[1x3,0nz],fwd_fwd_i0[1x3],fwd_fwd_i1[11x3],fwd_out_fwd_o0[1x3,0nz],fwd_adj_fwd_o0[1x3])->(fwd_adj_i0[1x3],fwd_adj_i1[11x3,0nz],fwd_adj_out_o0[1x3,0nz],fwd_adj_fwd_i0[1x3],fwd_adj_fwd_i1[11x3,0nz]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, *w4=w+11, *w5=w+19, *w6=w+28, *w7=w+38, *w8=w+49, *w9=w+69, *w10=w+87, w11, w12, w13, w14, w15, w16, w17, w18, w19;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = zeros(1x8) */
  casadi_clear(w4, 8);
  /* #5: @5 = zeros(1x9) */
  casadi_clear(w5, 9);
  /* #6: @6 = zeros(1x10) */
  casadi_clear(w6, 10);
  /* #7: @7 = input[1][0] */
  casadi_copy(arg[1], 11, w7);
  /* #8: @7 = @7' */
  /* #9: @8 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w8);
  /* #10: @6 = mac(@7,@8,@6) */
  casadi_mtimes(w7, casadi_s2, w8, casadi_s1, w6, casadi_s0, w, 0);
  /* #11: @9 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w9);
  /* #12: @5 = mac(@6,@9,@5) */
  casadi_mtimes(w6, casadi_s0, w9, casadi_s10, w5, casadi_s9, w, 0);
  /* #13: @10 = 
  [[-1.25, 00, 00, 00, 00, 00, 00, 00], 
   [1.25, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.25], 
   [00, 00, 00, 00, 00, 00, 00, 1.25]] */
  casadi_copy(casadi_c5, 16, w10);
  /* #14: @4 = mac(@5,@10,@4) */
  casadi_mtimes(w5, casadi_s9, w10, casadi_s13, w4, casadi_s12, w, 0);
  /* #15: @11 = BSplineParametric(@3) */
  casadi_clear((&w11), 1);
  CASADI_PREFIX(nd_boor_eval)((&w11),1,casadi_c6,casadi_s14,casadi_s3,casadi_s4,w4,1,(&w3),casadi_s3, iw, w);
  /* #16: @12 = input[12][0] */
  w12 = arg[12] ? arg[12][0] : 0;
  /* #17: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #18: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #19: @14 = BSplineParametric(@3) */
  casadi_clear((&w14), 1);
  CASADI_PREFIX(nd_boor_eval)((&w14),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w5,1,(&w3),casadi_s3, iw, w);
  /* #20: @15 = input[15][0] */
  w15 = arg[15] ? arg[15][0] : 0;
  /* #21: @15 = (@1*@15) */
  w15  = (w1*w15);
  /* #22: @16 = input[18][0] */
  w16 = arg[18] ? arg[18][0] : 0;
  /* #23: @17 = (@0*@16) */
  w17  = (w0*w16);
  /* #24: @15 = (@15+@17) */
  w15 += w17;
  /* #25: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #26: @13 = (@13+@15) */
  w13 += w15;
  /* #27: output[0][0] = @13 */
  if (res[0]) res[0][0] = w13;
  /* #28: @13 = input[12][1] */
  w13 = arg[12] ? arg[12][1] : 0;
  /* #29: @15 = (@11*@13) */
  w15  = (w11*w13);
  /* #30: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #31: @17 = input[15][1] */
  w17 = arg[15] ? arg[15][1] : 0;
  /* #32: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #33: @18 = input[18][1] */
  w18 = arg[18] ? arg[18][1] : 0;
  /* #34: @19 = (@0*@18) */
  w19  = (w0*w18);
  /* #35: @17 = (@17+@19) */
  w17 += w19;
  /* #36: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #37: @15 = (@15+@17) */
  w15 += w17;
  /* #38: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  /* #39: @15 = input[12][2] */
  w15 = arg[12] ? arg[12][2] : 0;
  /* #40: @11 = (@11*@15) */
  w11 *= w15;
  /* #41: @2 = (@2*@11) */
  w2 *= w11;
  /* #42: @11 = input[15][2] */
  w11 = arg[15] ? arg[15][2] : 0;
  /* #43: @11 = (@1*@11) */
  w11  = (w1*w11);
  /* #44: @17 = input[18][2] */
  w17 = arg[18] ? arg[18][2] : 0;
  /* #45: @0 = (@0*@17) */
  w0 *= w17;
  /* #46: @11 = (@11+@0) */
  w11 += w0;
  /* #47: @11 = (@14*@11) */
  w11  = (w14*w11);
  /* #48: @2 = (@2+@11) */
  w2 += w11;
  /* #49: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #50: @12 = (@14*@12) */
  w12  = (w14*w12);
  /* #51: @12 = (@1*@12) */
  w12  = (w1*w12);
  /* #52: @2 = BSplineParametric(@3) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w6,1,(&w3),casadi_s3, iw, w);
  /* #53: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #54: @12 = (@12+@16) */
  w12 += w16;
  /* #55: output[3][0] = @12 */
  if (res[3]) res[3][0] = w12;
  /* #56: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #57: @13 = (@1*@13) */
  w13  = (w1*w13);
  /* #58: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #59: @13 = (@13+@18) */
  w13 += w18;
  /* #60: output[3][1] = @13 */
  if (res[3]) res[3][1] = w13;
  /* #61: @14 = (@14*@15) */
  w14 *= w15;
  /* #62: @1 = (@1*@14) */
  w1 *= w14;
  /* #63: @2 = (@2*@17) */
  w2 *= w17;
  /* #64: @1 = (@1+@2) */
  w1 += w2;
  /* #65: output[3][2] = @1 */
  if (res[3]) res[3][2] = w1;
  return 0;
}

/* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess:(i0[6],i1[3],i2[0],i3[46])->(o0,o1[9],o2[9x9,12nz],o3[],o4[0x9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+5, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, *w2=w+114, w4, *w5=w+126, w6, *w7=w+138, w9, *w10=w+150, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w58, w59, *w63=w+199, *w64=w+206, *w65=w+215, w66, w67, w68, w72, w73, *w74=w+232, *w75=w+235, w77, w78, w79, w80, w81, w82, w83, *w85=w+275, w87, *w88=w+287, w89, w90, w91, w92, w93, w94, w95, *w96=w+305, *w97=w+308, *w98=w+311, *w99=w+344, *w100=w+347, *w101=w+353, *w102=w+359;
  /* #0: @0 = input[3][4] */
  w0 = arg[3] ? arg[3][36] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 11, w2);
  /* #3: @3 = 00 */
  /* #4: @4 = 1 */
  w4 = 1.;
  /* #5: @5 = zeros(11x1) */
  casadi_clear(w5, 11);
  /* #6: @6 = fwd1_xr(@1, @2, @3, @4, @5) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  res1[0]=(&w6);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @7 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+11 : 0, 11, w7);
  /* #8: @8 = 00 */
  /* #9: @9 = 1 */
  w9 = 1.;
  /* #10: @10 = zeros(11x1) */
  casadi_clear(w10, 11);
  /* #11: @11 = fwd1_yr(@1, @7, @8, @9, @10) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @12 = atan2(@6,@11) */
  w12  = atan2(w6,w11);
  /* #13: @13 = sin(@12) */
  w13 = sin( w12 );
  /* #14: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #15: @15 = xr(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  res1[0]=(&w15);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @16 = (@14-@15) */
  w16  = (w14-w15);
  /* #17: @17 = (@13*@16) */
  w17  = (w13*w16);
  /* #18: @18 = cos(@12) */
  w18 = cos( w12 );
  /* #19: @19 = input[0][1] */
  w19 = arg[0] ? arg[0][1] : 0;
  /* #20: @20 = yr(@1, @7) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  res1[0]=(&w20);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @21 = (@19-@20) */
  w21  = (w19-w20);
  /* #22: @22 = (@18*@21) */
  w22  = (w18*w21);
  /* #23: @17 = (@17-@22) */
  w17 -= w22;
  /* #24: @22 = sq(@17) */
  w22 = casadi_sq( w17 );
  /* #25: @22 = (@0*@22) */
  w22  = (w0*w22);
  /* #26: @23 = input[3][5] */
  w23 = arg[3] ? arg[3][37] : 0;
  /* #27: @24 = cos(@12) */
  w24 = cos( w12 );
  /* #28: @14 = (@14-@15) */
  w14 -= w15;
  /* #29: @15 = (@24*@14) */
  w15  = (w24*w14);
  /* #30: @15 = (-@15) */
  w15 = (- w15 );
  /* #31: @25 = sin(@12) */
  w25 = sin( w12 );
  /* #32: @19 = (@19-@20) */
  w19 -= w20;
  /* #33: @20 = (@25*@19) */
  w20  = (w25*w19);
  /* #34: @15 = (@15-@20) */
  w15 -= w20;
  /* #35: @20 = sq(@15) */
  w20 = casadi_sq( w15 );
  /* #36: @20 = (@23*@20) */
  w20  = (w23*w20);
  /* #37: @22 = (@22+@20) */
  w22 += w20;
  /* #38: @20 = input[1][0] */
  w20 = arg[1] ? arg[1][0] : 0;
  /* #39: @26 = sq(@20) */
  w26 = casadi_sq( w20 );
  /* #40: @22 = (@22+@26) */
  w22 += w26;
  /* #41: @26 = input[1][1] */
  w26 = arg[1] ? arg[1][1] : 0;
  /* #42: @27 = sq(@26) */
  w27 = casadi_sq( w26 );
  /* #43: @22 = (@22+@27) */
  w22 += w27;
  /* #44: @27 = 0.1 */
  w27 = 1.0000000000000001e-01;
  /* #45: @28 = input[1][2] */
  w28 = arg[1] ? arg[1][2] : 0;
  /* #46: @29 = sq(@28) */
  w29 = casadi_sq( w28 );
  /* #47: @27 = (@27*@29) */
  w27 *= w29;
  /* #48: @22 = (@22+@27) */
  w22 += w27;
  /* #49: @27 = input[3][6] */
  w27 = arg[3] ? arg[3][38] : 0;
  /* #50: @29 = input[0][5] */
  w29 = arg[0] ? arg[0][5] : 0;
  /* #51: @29 = (@27*@29) */
  w29  = (w27*w29);
  /* #52: @22 = (@22-@29) */
  w22 -= w29;
  /* #53: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  /* #54: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #55: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #56: @22 = 0.1 */
  w22 = 1.0000000000000001e-01;
  /* #57: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #58: @28 = (@22*@28) */
  w28  = (w22*w28);
  /* #59: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #60: @17 = (@17*@0) */
  w17 *= w0;
  /* #61: @29 = (@13*@17) */
  w29  = (w13*w17);
  /* #62: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #63: @15 = (@15*@23) */
  w15 *= w23;
  /* #64: @30 = (@24*@15) */
  w30  = (w24*w15);
  /* #65: @31 = (@29-@30) */
  w31  = (w29-w30);
  /* #66: @32 = (@18*@17) */
  w32  = (w18*w17);
  /* #67: @33 = (-@32) */
  w33 = (- w32 );
  /* #68: @34 = (@25*@15) */
  w34  = (w25*w15);
  /* #69: @33 = (@33-@34) */
  w33 -= w34;
  /* #70: @35 = 00 */
  /* #71: @36 = 00 */
  /* #72: @37 = 00 */
  /* #73: @34 = (@34+@32) */
  w34 += w32;
  /* #74: {@32, @38} = adj1_yr(@1, @7, @37, @34) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w34);
  res1[0]=(&w32);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #75: @39 = 00 */
  /* #76: @30 = (@30-@29) */
  w30 -= w29;
  /* #77: {@29, @40} = adj1_xr(@1, @2, @39, @30) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w30);
  res1[0]=(&w29);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #78: @32 = (@32+@29) */
  w32 += w29;
  /* #79: @41 = 00 */
  /* #80: @29 = sq(@6) */
  w29 = casadi_sq( w6 );
  /* #81: @42 = sq(@11) */
  w42 = casadi_sq( w11 );
  /* #82: @29 = (@29+@42) */
  w29 += w42;
  /* #83: @42 = (@6/@29) */
  w42  = (w6/w29);
  /* #84: @43 = sin(@12) */
  w43 = sin( w12 );
  /* #85: @44 = (@14*@15) */
  w44  = (w14*w15);
  /* #86: @45 = (@43*@44) */
  w45  = (w43*w44);
  /* #87: @46 = cos(@12) */
  w46 = cos( w12 );
  /* #88: @47 = (@19*@15) */
  w47  = (w19*w15);
  /* #89: @48 = (@46*@47) */
  w48  = (w46*w47);
  /* #90: @45 = (@45-@48) */
  w45 -= w48;
  /* #91: @48 = sin(@12) */
  w48 = sin( w12 );
  /* #92: @49 = (@21*@17) */
  w49  = (w21*w17);
  /* #93: @50 = (@48*@49) */
  w50  = (w48*w49);
  /* #94: @45 = (@45+@50) */
  w45 += w50;
  /* #95: @50 = cos(@12) */
  w50 = cos( w12 );
  /* #96: @51 = (@16*@17) */
  w51  = (w16*w17);
  /* #97: @52 = (@50*@51) */
  w52  = (w50*w51);
  /* #98: @45 = (@45+@52) */
  w45 += w52;
  /* #99: @52 = (@42*@45) */
  w52  = (w42*w45);
  /* #100: @52 = (-@52) */
  w52 = (- w52 );
  /* #101: {@53, @54, @55, NULL, @56} = adj1_fwd1_yr(@1, @7, @8, @9, @10, @41, @52) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  arg1[5]=0;
  arg1[6]=(&w52);
  res1[0]=(&w53);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #102: @32 = (@32+@53) */
  w32 += w53;
  /* #103: @57 = 00 */
  /* #104: @53 = (@11/@29) */
  w53  = (w11/w29);
  /* #105: @58 = (@53*@45) */
  w58  = (w53*w45);
  /* #106: {@59, @60, @61, NULL, @62} = adj1_fwd1_xr(@1, @2, @3, @4, @5, @57, @58) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  arg1[5]=0;
  arg1[6]=(&w58);
  res1[0]=(&w59);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #107: @32 = (@32+@59) */
  w32 += w59;
  /* #108: @27 = (-@27) */
  w27 = (- w27 );
  /* #109: @63 = vertcat(@20, @26, @28, @31, @33, @35, @36, @32, @27) */
  rr=w63;
  *rr++ = w20;
  *rr++ = w26;
  *rr++ = w28;
  *rr++ = w31;
  *rr++ = w33;
  *rr++ = w32;
  *rr++ = w27;
  /* #110: @64 = dense(@63) */
  casadi_densify(w63, casadi_s15, w64, 0);
  /* #111: output[1][0] = @64 */
  casadi_copy(w64, 9, res[1]);
  /* #112: @65 = zeros(9x9,12nz) */
  casadi_clear(w65, 12);
  /* #113: @63 = ones(9x1,7nz) */
  casadi_fill(w63, 7, 1.);
  /* #114: {@20, @26, @28, @31, NULL, NULL, NULL, NULL, NULL} = vertsplit(@63) */
  w20 = w63[0];
  w26 = w63[1];
  w28 = w63[2];
  w31 = w63[3];
  /* #115: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #116: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #117: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #118: @22 = (@22*@28) */
  w22 *= w28;
  /* #119: @28 = (@13*@31) */
  w28  = (w13*w31);
  /* #120: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #121: @28 = (@0*@28) */
  w28  = (w0*w28);
  /* #122: @33 = (@13*@28) */
  w33  = (w13*w28);
  /* #123: @32 = (@24*@31) */
  w32  = (w24*w31);
  /* #124: @32 = (-@32) */
  w32 = (- w32 );
  /* #125: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #126: @32 = (@23*@32) */
  w32  = (w23*w32);
  /* #127: @27 = (@24*@32) */
  w27  = (w24*w32);
  /* #128: @59 = (@33-@27) */
  w59  = (w33-w27);
  /* #129: @66 = (@25*@32) */
  w66  = (w25*w32);
  /* #130: @67 = (-@66) */
  w67 = (- w66 );
  /* #131: @68 = (@18*@28) */
  w68  = (w18*w28);
  /* #132: @67 = (@67-@68) */
  w67 -= w68;
  /* #133: @35 = 00 */
  /* #134: @36 = 00 */
  /* #135: @69 = 00 */
  /* #136: @70 = 00 */
  /* #137: @71 = 00 */
  /* #138: @72 = ones(9x1,1nz) */
  w72 = 1.;
  /* #139: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @73, NULL} = vertsplit(@72) */
  w73 = w72;
  /* #140: @72 = horzcat(@70, @71, @73) */
  rr=(&w72);
  *rr++ = w73;
  /* #141: @74 = dense(@72) */
  casadi_densify((&w72), casadi_s16, w74, 0);
  /* #142: @75 = zeros(11x3) */
  casadi_clear(w75, 33);
  /* #143: @76 = zeros(1x3,0nz) */
  /* #144: @66 = (@66+@68) */
  w66 += w68;
  /* #145: @68 = ones(9x1,1nz) */
  w68 = 1.;
  /* #146: {NULL, NULL, NULL, NULL, @72, NULL, NULL, NULL, NULL} = vertsplit(@68) */
  w72 = w68;
  /* #147: @68 = (@25*@72) */
  w68  = (w25*w72);
  /* #148: @68 = (-@68) */
  w68 = (- w68 );
  /* #149: @68 = (2.*@68) */
  w68 = (2.* w68 );
  /* #150: @68 = (@23*@68) */
  w68  = (w23*w68);
  /* #151: @77 = (@25*@68) */
  w77  = (w25*w68);
  /* #152: @78 = (@18*@72) */
  w78  = (w18*w72);
  /* #153: @78 = (-@78) */
  w78 = (- w78 );
  /* #154: @78 = (2.*@78) */
  w78 = (2.* w78 );
  /* #155: @78 = (@0*@78) */
  w78  = (w0*w78);
  /* #156: @79 = (@18*@78) */
  w79  = (w18*w78);
  /* #157: @80 = (@77+@79) */
  w80  = (w77+w79);
  /* #158: @81 = cos(@12) */
  w81 = cos( w12 );
  /* #159: @82 = sq(@6) */
  w82 = casadi_sq( w6 );
  /* #160: @83 = sq(@11) */
  w83 = casadi_sq( w11 );
  /* #161: @82 = (@82+@83) */
  w82 += w83;
  /* #162: @83 = (@11/@82) */
  w83  = (w11/w82);
  /* #163: @84 = 00 */
  /* #164: @85 = zeros(11x1) */
  casadi_clear(w85, 11);
  /* #165: @86 = 00 */
  /* #166: @87 = 0 */
  w87 = 0.;
  /* #167: @88 = zeros(11x1) */
  casadi_clear(w88, 11);
  /* #168: @89 = fwd1_fwd1_xr(@1, @2, @3, @4, @5, @84, @73, @85, @86, @87, @88) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  arg1[5]=0;
  arg1[6]=(&w73);
  arg1[7]=w85;
  arg1[8]=0;
  arg1[9]=(&w87);
  arg1[10]=w88;
  res1[0]=(&w89);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #169: @83 = (@83*@89) */
  w83 *= w89;
  /* #170: @82 = (@6/@82) */
  w82  = (w6/w82);
  /* #171: @84 = 00 */
  /* #172: @85 = zeros(11x1) */
  casadi_clear(w85, 11);
  /* #173: @86 = 00 */
  /* #174: @87 = 0 */
  w87 = 0.;
  /* #175: @88 = zeros(11x1) */
  casadi_clear(w88, 11);
  /* #176: @90 = fwd1_fwd1_yr(@1, @7, @8, @9, @10, @84, @73, @85, @86, @87, @88) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  arg1[5]=0;
  arg1[6]=(&w73);
  arg1[7]=w85;
  arg1[8]=0;
  arg1[9]=(&w87);
  arg1[10]=w88;
  res1[0]=(&w90);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #177: @82 = (@82*@90) */
  w82 *= w90;
  /* #178: @83 = (@83-@82) */
  w83 -= w82;
  /* #179: @81 = (@81*@83) */
  w81 *= w83;
  /* #180: @82 = (@15*@81) */
  w82  = (w15*w81);
  /* #181: @81 = (@19*@81) */
  w81  = (w19*w81);
  /* #182: @84 = 00 */
  /* #183: @85 = zeros(11x1) */
  casadi_clear(w85, 11);
  /* #184: @87 = fwd1_yr(@1, @7, @84, @73, @85) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w73);
  arg1[4]=w85;
  res1[0]=(&w87);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #185: @91 = (@25*@87) */
  w91  = (w25*w87);
  /* #186: @81 = (@81-@91) */
  w81 -= w91;
  /* #187: @81 = (-@81) */
  w81 = (- w81 );
  /* #188: @84 = 00 */
  /* #189: @85 = zeros(11x1) */
  casadi_clear(w85, 11);
  /* #190: @91 = fwd1_xr(@1, @2, @84, @73, @85) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w73);
  arg1[4]=w85;
  res1[0]=(&w91);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #191: @92 = (@24*@91) */
  w92  = (w24*w91);
  /* #192: @92 = (-@92) */
  w92 = (- w92 );
  /* #193: @93 = sin(@12) */
  w93 = sin( w12 );
  /* #194: @93 = (@93*@83) */
  w93 *= w83;
  /* #195: @94 = (@14*@93) */
  w94  = (w14*w93);
  /* #196: @92 = (@92-@94) */
  w92 -= w94;
  /* #197: @81 = (@81-@92) */
  w81 -= w92;
  /* #198: @81 = (2.*@81) */
  w81 = (2.* w81 );
  /* #199: @23 = (@23*@81) */
  w23 *= w81;
  /* #200: @25 = (@25*@23) */
  w25 *= w23;
  /* #201: @82 = (@82+@25) */
  w82 += w25;
  /* #202: @25 = cos(@12) */
  w25 = cos( w12 );
  /* #203: @25 = (@25*@83) */
  w25 *= w83;
  /* #204: @81 = (@16*@25) */
  w81  = (w16*w25);
  /* #205: @92 = (@13*@91) */
  w92  = (w13*w91);
  /* #206: @81 = (@81-@92) */
  w81 -= w92;
  /* #207: @92 = (@18*@87) */
  w92  = (w18*w87);
  /* #208: @92 = (-@92) */
  w92 = (- w92 );
  /* #209: @94 = sin(@12) */
  w94 = sin( w12 );
  /* #210: @94 = (@94*@83) */
  w94 *= w83;
  /* #211: @95 = (@21*@94) */
  w95  = (w21*w94);
  /* #212: @92 = (@92-@95) */
  w92 -= w95;
  /* #213: @81 = (@81-@92) */
  w81 -= w92;
  /* #214: @81 = (2.*@81) */
  w81 = (2.* w81 );
  /* #215: @0 = (@0*@81) */
  w0 *= w81;
  /* #216: @18 = (@18*@0) */
  w18 *= w0;
  /* #217: @94 = (@17*@94) */
  w94  = (w17*w94);
  /* #218: @18 = (@18-@94) */
  w18 -= w94;
  /* #219: @94 = (@82+@18) */
  w94  = (w82+w18);
  /* #220: @96 = horzcat(@66, @80, @94) */
  rr=w96;
  *rr++ = w66;
  *rr++ = w80;
  *rr++ = w94;
  /* #221: {@97, NULL} = fwd3_adj1_yr(@1, @7, @37, @34, @69, @38, @74, @75, @76, @96) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w34);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=w74;
  arg1[7]=w75;
  arg1[8]=0;
  arg1[9]=w96;
  res1[0]=w97;
  res1[1]=0;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #222: {@34, @66, @80} = horzsplit(@97) */
  w34 = w97[0];
  w66 = w97[1];
  w80 = w97[2];
  /* #223: @37 = 00 */
  /* #224: @94 = horzcat(@70, @71, @73) */
  rr=(&w94);
  *rr++ = w73;
  /* #225: @97 = dense(@94) */
  casadi_densify((&w94), casadi_s16, w97, 0);
  /* #226: @75 = zeros(11x3) */
  casadi_clear(w75, 33);
  /* #227: @69 = zeros(1x3,0nz) */
  /* #228: @27 = (@27-@33) */
  w27 -= w33;
  /* #229: @33 = (@24*@68) */
  w33  = (w24*w68);
  /* #230: @94 = (@13*@78) */
  w94  = (w13*w78);
  /* #231: @81 = (@33-@94) */
  w81  = (w33-w94);
  /* #232: @24 = (@24*@23) */
  w24 *= w23;
  /* #233: @93 = (@15*@93) */
  w93  = (w15*w93);
  /* #234: @24 = (@24-@93) */
  w24 -= w93;
  /* #235: @25 = (@17*@25) */
  w25  = (w17*w25);
  /* #236: @13 = (@13*@0) */
  w13 *= w0;
  /* #237: @25 = (@25+@13) */
  w25 += w13;
  /* #238: @13 = (@24-@25) */
  w13  = (w24-w25);
  /* #239: @74 = horzcat(@27, @81, @13) */
  rr=w74;
  *rr++ = w27;
  *rr++ = w81;
  *rr++ = w13;
  /* #240: {@96, NULL} = fwd3_adj1_xr(@1, @2, @39, @30, @37, @40, @97, @75, @69, @74) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w30);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=w97;
  arg1[7]=w75;
  arg1[8]=0;
  arg1[9]=w74;
  res1[0]=w96;
  res1[1]=0;
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #241: {@30, @27, @81} = horzsplit(@96) */
  w30 = w96[0];
  w27 = w96[1];
  w81 = w96[2];
  /* #242: @34 = (@34+@30) */
  w34 += w30;
  /* #243: @39 = 00 */
  /* #244: @37 = 00 */
  /* #245: @30 = horzcat(@70, @71, @73) */
  rr=(&w30);
  *rr++ = w73;
  /* #246: @96 = dense(@30) */
  casadi_densify((&w30), casadi_s16, w96, 0);
  /* #247: @75 = zeros(11x3) */
  casadi_clear(w75, 33);
  /* #248: @40 = zeros(1x3,0nz) */
  /* #249: @97 = zeros(1x3) */
  casadi_clear(w97, 3);
  /* #250: @98 = zeros(11x3) */
  casadi_clear(w98, 33);
  /* #251: @69 = zeros(1x3,0nz) */
  /* #252: @30 = (@15*@31) */
  w30  = (w15*w31);
  /* #253: @13 = (@14*@32) */
  w13  = (w14*w32);
  /* #254: @30 = (@30+@13) */
  w30 += w13;
  /* #255: @30 = (@43*@30) */
  w30  = (w43*w30);
  /* #256: @32 = (@19*@32) */
  w32  = (w19*w32);
  /* #257: @32 = (@46*@32) */
  w32  = (w46*w32);
  /* #258: @30 = (@30-@32) */
  w30 -= w32;
  /* #259: @32 = (@21*@28) */
  w32  = (w21*w28);
  /* #260: @32 = (@48*@32) */
  w32  = (w48*w32);
  /* #261: @30 = (@30+@32) */
  w30 += w32;
  /* #262: @31 = (@17*@31) */
  w31  = (w17*w31);
  /* #263: @28 = (@16*@28) */
  w28  = (w16*w28);
  /* #264: @31 = (@31+@28) */
  w31 += w28;
  /* #265: @31 = (@50*@31) */
  w31  = (w50*w31);
  /* #266: @30 = (@30+@31) */
  w30 += w31;
  /* #267: @31 = (@42*@30) */
  w31  = (w42*w30);
  /* #268: @31 = (-@31) */
  w31 = (- w31 );
  /* #269: @28 = (@14*@68) */
  w28  = (w14*w68);
  /* #270: @28 = (@43*@28) */
  w28  = (w43*w28);
  /* #271: @32 = (@15*@72) */
  w32  = (w15*w72);
  /* #272: @68 = (@19*@68) */
  w68  = (w19*w68);
  /* #273: @32 = (@32+@68) */
  w32 += w68;
  /* #274: @32 = (@46*@32) */
  w32  = (w46*w32);
  /* #275: @28 = (@28-@32) */
  w28 -= w32;
  /* #276: @72 = (@17*@72) */
  w72  = (w17*w72);
  /* #277: @32 = (@21*@78) */
  w32  = (w21*w78);
  /* #278: @72 = (@72+@32) */
  w72 += w32;
  /* #279: @72 = (@48*@72) */
  w72  = (w48*w72);
  /* #280: @28 = (@28+@72) */
  w28 += w72;
  /* #281: @78 = (@16*@78) */
  w78  = (w16*w78);
  /* #282: @78 = (@50*@78) */
  w78  = (w50*w78);
  /* #283: @28 = (@28+@78) */
  w28 += w78;
  /* #284: @78 = (@42*@28) */
  w78  = (w42*w28);
  /* #285: @78 = (-@78) */
  w78 = (- w78 );
  /* #286: @72 = (@89/@29) */
  w72  = (w89/w29);
  /* #287: @32 = (@42/@29) */
  w32  = (w42/w29);
  /* #288: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #289: @6 = (@6*@89) */
  w6 *= w89;
  /* #290: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #291: @11 = (@11*@90) */
  w11 *= w90;
  /* #292: @6 = (@6+@11) */
  w6 += w11;
  /* #293: @32 = (@32*@6) */
  w32 *= w6;
  /* #294: @72 = (@72-@32) */
  w72 -= w32;
  /* #295: @72 = (@45*@72) */
  w72  = (w45*w72);
  /* #296: @32 = cos(@12) */
  w32 = cos( w12 );
  /* #297: @32 = (@32*@83) */
  w32 *= w83;
  /* #298: @44 = (@44*@32) */
  w44 *= w32;
  /* #299: @14 = (@14*@23) */
  w14 *= w23;
  /* #300: @32 = (@15*@91) */
  w32  = (w15*w91);
  /* #301: @14 = (@14-@32) */
  w14 -= w32;
  /* #302: @43 = (@43*@14) */
  w43 *= w14;
  /* #303: @44 = (@44+@43) */
  w44 += w43;
  /* #304: @19 = (@19*@23) */
  w19 *= w23;
  /* #305: @15 = (@15*@87) */
  w15 *= w87;
  /* #306: @19 = (@19-@15) */
  w19 -= w15;
  /* #307: @46 = (@46*@19) */
  w46 *= w19;
  /* #308: @19 = sin(@12) */
  w19 = sin( w12 );
  /* #309: @19 = (@19*@83) */
  w19 *= w83;
  /* #310: @47 = (@47*@19) */
  w47 *= w19;
  /* #311: @46 = (@46-@47) */
  w46 -= w47;
  /* #312: @44 = (@44-@46) */
  w44 -= w46;
  /* #313: @46 = cos(@12) */
  w46 = cos( w12 );
  /* #314: @46 = (@46*@83) */
  w46 *= w83;
  /* #315: @49 = (@49*@46) */
  w49 *= w46;
  /* #316: @21 = (@21*@0) */
  w21 *= w0;
  /* #317: @87 = (@17*@87) */
  w87  = (w17*w87);
  /* #318: @21 = (@21-@87) */
  w21 -= w87;
  /* #319: @48 = (@48*@21) */
  w48 *= w21;
  /* #320: @49 = (@49+@48) */
  w49 += w48;
  /* #321: @44 = (@44+@49) */
  w44 += w49;
  /* #322: @16 = (@16*@0) */
  w16 *= w0;
  /* #323: @17 = (@17*@91) */
  w17 *= w91;
  /* #324: @16 = (@16-@17) */
  w16 -= w17;
  /* #325: @50 = (@50*@16) */
  w50 *= w16;
  /* #326: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #327: @12 = (@12*@83) */
  w12 *= w83;
  /* #328: @51 = (@51*@12) */
  w51 *= w12;
  /* #329: @50 = (@50-@51) */
  w50 -= w51;
  /* #330: @44 = (@44+@50) */
  w44 += w50;
  /* #331: @42 = (@42*@44) */
  w42 *= w44;
  /* #332: @72 = (@72+@42) */
  w72 += w42;
  /* #333: @72 = (-@72) */
  w72 = (- w72 );
  /* #334: @74 = horzcat(@31, @78, @72) */
  rr=w74;
  *rr++ = w31;
  *rr++ = w78;
  *rr++ = w72;
  /* #335: {@99, NULL, NULL, NULL, NULL} = fwd3_adj1_fwd1_yr(@1, @7, @8, @9, @10, @41, @52, @39, @54, @55, @37, @56, @96, @75, @40, @97, @98, @69, @74) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  arg1[5]=0;
  arg1[6]=(&w52);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=w96;
  arg1[13]=w75;
  arg1[14]=0;
  arg1[15]=w97;
  arg1[16]=w98;
  arg1[17]=0;
  arg1[18]=w74;
  res1[0]=w99;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f13(arg1, res1, iw, w, 0)) return 1;
  /* #336: {@9, @52, @31} = horzsplit(@99) */
  w9 = w99[0];
  w52 = w99[1];
  w31 = w99[2];
  /* #337: @34 = (@34+@9) */
  w34 += w9;
  /* #338: @8 = 00 */
  /* #339: @41 = 00 */
  /* #340: @9 = horzcat(@70, @71, @73) */
  rr=(&w9);
  *rr++ = w73;
  /* #341: @99 = dense(@9) */
  casadi_densify((&w9), casadi_s16, w99, 0);
  /* #342: @75 = zeros(11x3) */
  casadi_clear(w75, 33);
  /* #343: @70 = zeros(1x3,0nz) */
  /* #344: @96 = zeros(1x3) */
  casadi_clear(w96, 3);
  /* #345: @98 = zeros(11x3) */
  casadi_clear(w98, 33);
  /* #346: @71 = zeros(1x3,0nz) */
  /* #347: @30 = (@53*@30) */
  w30  = (w53*w30);
  /* #348: @28 = (@53*@28) */
  w28  = (w53*w28);
  /* #349: @90 = (@90/@29) */
  w90 /= w29;
  /* #350: @29 = (@53/@29) */
  w29  = (w53/w29);
  /* #351: @29 = (@29*@6) */
  w29 *= w6;
  /* #352: @90 = (@90-@29) */
  w90 -= w29;
  /* #353: @45 = (@45*@90) */
  w45 *= w90;
  /* #354: @53 = (@53*@44) */
  w53 *= w44;
  /* #355: @45 = (@45+@53) */
  w45 += w53;
  /* #356: @97 = horzcat(@30, @28, @45) */
  rr=w97;
  *rr++ = w30;
  *rr++ = w28;
  *rr++ = w45;
  /* #357: {@74, NULL, NULL, NULL, NULL} = fwd3_adj1_fwd1_xr(@1, @2, @3, @4, @5, @57, @58, @8, @60, @61, @41, @62, @99, @75, @70, @96, @98, @71, @97) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  arg1[5]=0;
  arg1[6]=(&w58);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=w99;
  arg1[13]=w75;
  arg1[14]=0;
  arg1[15]=w96;
  arg1[16]=w98;
  arg1[17]=0;
  arg1[18]=w97;
  res1[0]=w74;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f14(arg1, res1, iw, w, 0)) return 1;
  /* #358: {@1, @4, @58} = horzsplit(@74) */
  w1 = w74[0];
  w4 = w74[1];
  w58 = w74[2];
  /* #359: @34 = (@34+@1) */
  w34 += w1;
  /* #360: @3 = 00 */
  /* #361: @100 = vertcat(@20, @26, @22, @59, @67, @35, @36, @34, @3) */
  rr=w100;
  *rr++ = w20;
  *rr++ = w26;
  *rr++ = w22;
  *rr++ = w59;
  *rr++ = w67;
  *rr++ = w34;
  /* #362: @101 = @100[:6] */
  for (rr=w101, ss=w100+0; ss!=w100+6; ss+=1) *rr++ = *ss;
  /* #363: (@65[:6] = @101) */
  for (rr=w65+0, ss=w101; rr!=w65+6; rr+=1) *rr = *ss++;
  /* #364: @101 = @100[:6] */
  for (rr=w101, ss=w100+0; ss!=w100+6; ss+=1) *rr++ = *ss;
  /* #365: (@65[0, 1, 2, 3, 6, 9] = @101) */
  for (cii=casadi_s17, rr=w65, ss=w101; cii!=casadi_s17+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #366: @35 = 00 */
  /* #367: @36 = 00 */
  /* #368: @3 = 00 */
  /* #369: @94 = (@94-@33) */
  w94 -= w33;
  /* #370: @77 = (-@77) */
  w77 = (- w77 );
  /* #371: @77 = (@77-@79) */
  w77 -= w79;
  /* #372: @57 = 00 */
  /* #373: @8 = 00 */
  /* #374: @66 = (@66+@27) */
  w66 += w27;
  /* #375: @66 = (@66+@52) */
  w66 += w52;
  /* #376: @66 = (@66+@4) */
  w66 += w4;
  /* #377: @60 = 00 */
  /* #378: @74 = vertcat(@35, @36, @3, @94, @77, @57, @8, @66, @60) */
  rr=w74;
  *rr++ = w94;
  *rr++ = w77;
  *rr++ = w66;
  /* #379: @99 = @74[:3] */
  for (rr=w99, ss=w74+0; ss!=w74+3; ss+=1) *rr++ = *ss;
  /* #380: (@65[6:9] = @99) */
  for (rr=w65+6, ss=w99; rr!=w65+9; rr+=1) *rr = *ss++;
  /* #381: @99 = @74[:3] */
  for (rr=w99, ss=w74+0; ss!=w74+3; ss+=1) *rr++ = *ss;
  /* #382: (@65[4:13:3] = @99) */
  for (rr=w65+4, ss=w99; rr!=w65+13; rr+=3) *rr = *ss++;
  /* #383: @35 = 00 */
  /* #384: @36 = 00 */
  /* #385: @3 = 00 */
  /* #386: @25 = (@25-@24) */
  w25 -= w24;
  /* #387: @82 = (-@82) */
  w82 = (- w82 );
  /* #388: @82 = (@82-@18) */
  w82 -= w18;
  /* #389: @57 = 00 */
  /* #390: @8 = 00 */
  /* #391: @80 = (@80+@81) */
  w80 += w81;
  /* #392: @80 = (@80+@31) */
  w80 += w31;
  /* #393: @80 = (@80+@58) */
  w80 += w58;
  /* #394: @60 = 00 */
  /* #395: @99 = vertcat(@35, @36, @3, @25, @82, @57, @8, @80, @60) */
  rr=w99;
  *rr++ = w25;
  *rr++ = w82;
  *rr++ = w80;
  /* #396: @74 = @99[:3] */
  for (rr=w74, ss=w99+0; ss!=w99+3; ss+=1) *rr++ = *ss;
  /* #397: (@65[9:12] = @74) */
  for (rr=w65+9, ss=w74; rr!=w65+12; rr+=1) *rr = *ss++;
  /* #398: @74 = @99[:3] */
  for (rr=w74, ss=w99+0; ss!=w99+3; ss+=1) *rr++ = *ss;
  /* #399: (@65[5:14:3] = @74) */
  for (rr=w65+5, ss=w74; rr!=w65+14; rr+=3) *rr = *ss++;
  /* #400: @102 = @65' */
  casadi_trans(w65,casadi_s18, w102, casadi_s18, iw);
  /* #401: output[2][0] = @102 */
  casadi_copy(w102, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s20;
    case 2: return casadi_s21;
    case 3: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s23;
    case 1: return casadi_s24;
    case 2: return casadi_s18;
    case 3: return casadi_s25;
    case 4: return casadi_s26;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 26;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 10;
  if (sz_w) *sz_w = 371;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
