/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_model_mpcc_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[33] = {11, 10, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10};
static const casadi_int casadi_s2[25] = {1, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[1] = {1};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[2] = {0, 13};
static const casadi_int casadi_s7[1] = {3};
static const casadi_int casadi_s8[2] = {0, 15};
static const casadi_int casadi_s9[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s10[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s11[4] = {0, 1, 0, 0};
static const casadi_int casadi_s12[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s13[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[20] = {-3.7500000000000000e+00, 3.7500000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000000e+00, 1.8750000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000004e+00, 1.8750000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -3.7500000000000009e+00, 3.7500000000000009e+00};
static const casadi_real casadi_c1[13] = {0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4.};
static const casadi_real casadi_c2[15] = {0., 0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4., 4.};

/* fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* xr:(i0,i1[11])->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* yr:(i0,i1[11])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* unicycle_model_mpcc_cost_ext_cost_fun:(i0[6],i1[3],i2[0],i3[46])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, *w2=w+52, w4, *w5=w+64, w6, *w7=w+76, w8, w9, w10, w11, w12;
  /* #0: @0 = input[3][4] */
  w0 = arg[3] ? arg[3][36] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 11, w2);
  /* #3: @3 = 00 */
  /* #4: @4 = 1 */
  w4 = 1.;
  /* #5: @5 = zeros(11x1) */
  casadi_clear(w5, 11);
  /* #6: @6 = fwd1_xr(@1, @2, @3, @4, @5) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  res1[0]=(&w6);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @5 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+11 : 0, 11, w5);
  /* #8: @3 = 00 */
  /* #9: @4 = 1 */
  w4 = 1.;
  /* #10: @7 = zeros(11x1) */
  casadi_clear(w7, 11);
  /* #11: @8 = fwd1_yr(@1, @5, @3, @4, @7) */
  arg1[0]=(&w1);
  arg1[1]=w5;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w7;
  res1[0]=(&w8);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @6 = atan2(@6,@8) */
  w6  = atan2(w6,w8);
  /* #13: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #14: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #15: @9 = xr(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  res1[0]=(&w9);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @10 = (@4-@9) */
  w10  = (w4-w9);
  /* #17: @8 = (@8*@10) */
  w8 *= w10;
  /* #18: @10 = cos(@6) */
  w10 = cos( w6 );
  /* #19: @11 = input[0][1] */
  w11 = arg[0] ? arg[0][1] : 0;
  /* #20: @12 = yr(@1, @5) */
  arg1[0]=(&w1);
  arg1[1]=w5;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @1 = (@11-@12) */
  w1  = (w11-w12);
  /* #22: @10 = (@10*@1) */
  w10 *= w1;
  /* #23: @8 = (@8-@10) */
  w8 -= w10;
  /* #24: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #25: @0 = (@0*@8) */
  w0 *= w8;
  /* #26: @8 = input[3][5] */
  w8 = arg[3] ? arg[3][37] : 0;
  /* #27: @10 = cos(@6) */
  w10 = cos( w6 );
  /* #28: @4 = (@4-@9) */
  w4 -= w9;
  /* #29: @10 = (@10*@4) */
  w10 *= w4;
  /* #30: @10 = (-@10) */
  w10 = (- w10 );
  /* #31: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #32: @11 = (@11-@12) */
  w11 -= w12;
  /* #33: @6 = (@6*@11) */
  w6 *= w11;
  /* #34: @10 = (@10-@6) */
  w10 -= w6;
  /* #35: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #36: @8 = (@8*@10) */
  w8 *= w10;
  /* #37: @0 = (@0+@8) */
  w0 += w8;
  /* #38: @8 = input[1][0] */
  w8 = arg[1] ? arg[1][0] : 0;
  /* #39: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #40: @0 = (@0+@8) */
  w0 += w8;
  /* #41: @8 = input[1][1] */
  w8 = arg[1] ? arg[1][1] : 0;
  /* #42: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #43: @0 = (@0+@8) */
  w0 += w8;
  /* #44: @8 = 0.1 */
  w8 = 1.0000000000000001e-01;
  /* #45: @10 = input[1][2] */
  w10 = arg[1] ? arg[1][2] : 0;
  /* #46: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #47: @8 = (@8*@10) */
  w8 *= w10;
  /* #48: @0 = (@0+@8) */
  w0 += w8;
  /* #49: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][38] : 0;
  /* #50: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #51: @8 = (@8*@10) */
  w8 *= w10;
  /* #52: @0 = (@0-@8) */
  w0 -= w8;
  /* #53: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_model_mpcc_cost_ext_cost_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_cost_ext_cost_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_cost_ext_cost_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s11;
    case 3: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 92;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
