/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[33] = {11, 10, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10};
static const casadi_int casadi_s2[25] = {1, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[1] = {1};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[2] = {0, 13};
static const casadi_int casadi_s7[1] = {3};
static const casadi_int casadi_s8[2] = {0, 15};
static const casadi_int casadi_s9[21] = {1, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s10[30] = {10, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9};
static const casadi_int casadi_s11[2] = {0, 11};
static const casadi_int casadi_s12[19] = {1, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s13[27] = {9, 8, 0, 2, 4, 6, 8, 10, 12, 14, 16, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8};
static const casadi_int casadi_s14[2] = {0, 9};
static const casadi_int casadi_s15[8] = {6, 1, 0, 4, 0, 1, 4, 5};
static const casadi_int casadi_s16[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[18] = {6, 6, 0, 3, 6, 6, 6, 9, 9, 0, 1, 4, 0, 1, 4, 0, 1, 4};
static const casadi_int casadi_s18[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s19[3] = {0, 0, 0};
static const casadi_int casadi_s20[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s21[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s22[9] = {0, 6, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[20] = {-3.7500000000000000e+00, 3.7500000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000000e+00, 1.8750000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000004e+00, 1.8750000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -3.7500000000000009e+00, 3.7500000000000009e+00};
static const casadi_real casadi_c1[13] = {0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4.};
static const casadi_real casadi_c2[15] = {0., 0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4., 4.};
static const casadi_real casadi_c3[18] = {-2.5000000000000000e+00, 2.5000000000000000e+00, -1.6666666666666665e+00, 1.6666666666666665e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -1.6666666666666670e+00, 1.6666666666666670e+00, -2.5000000000000004e+00, 2.5000000000000004e+00};
static const casadi_real casadi_c4[11] = {0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4.};
static const casadi_real casadi_c5[16] = {-1.2500000000000000e+00, 1.2500000000000000e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.4999999999999978e+00, 2.4999999999999978e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -1.2500000000000002e+00, 1.2500000000000002e+00};
static const casadi_real casadi_c6[9] = {0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4.};

/* fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* xr:(i0,i1[11])->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* yr:(i0,i1[11])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* adj1_yr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_xr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* adj1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* fwd1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],fwd_i0,fwd_i1[11],fwd_out_o0[1x1,0nz],fwd_fwd_i0,fwd_fwd_i1[11])->(fwd_fwd_o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+9, *w3=w+18, *w4=w+28, *w5=w+39, *w6=w+59, w7, w8;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x9) */
  casadi_clear(w2, 9);
  /* #3: @3 = zeros(1x10) */
  casadi_clear(w3, 10);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 11, w4);
  /* #5: @4 = @4' */
  /* #6: @5 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes(w4, casadi_s2, w5, casadi_s1, w3, casadi_s0, w, 0);
  /* #8: @6 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w6);
  /* #9: @2 = mac(@3,@6,@2) */
  casadi_mtimes(w3, casadi_s0, w6, casadi_s10, w2, casadi_s9, w, 0);
  /* #10: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w2,1,(&w1),casadi_s3, iw, w);
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @0 = (@0*@7) */
  w0 *= w7;
  /* #14: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w3,1,(&w1),casadi_s3, iw, w);
  /* #15: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #16: @7 = (@7*@1) */
  w7 *= w1;
  /* #17: @0 = (@0+@7) */
  w0 += w7;
  /* #18: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],fwd_i0,fwd_i1[11],fwd_out_o0[1x1,0nz],fwd_fwd_i0,fwd_fwd_i1[11])->(fwd_fwd_o0) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+9, *w3=w+18, *w4=w+28, *w5=w+39, *w6=w+59, w7, w8;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x9) */
  casadi_clear(w2, 9);
  /* #3: @3 = zeros(1x10) */
  casadi_clear(w3, 10);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 11, w4);
  /* #5: @4 = @4' */
  /* #6: @5 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes(w4, casadi_s2, w5, casadi_s1, w3, casadi_s0, w, 0);
  /* #8: @6 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w6);
  /* #9: @2 = mac(@3,@6,@2) */
  casadi_mtimes(w3, casadi_s0, w6, casadi_s10, w2, casadi_s9, w, 0);
  /* #10: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w2,1,(&w1),casadi_s3, iw, w);
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @0 = (@0*@7) */
  w0 *= w7;
  /* #14: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w3,1,(&w1),casadi_s3, iw, w);
  /* #15: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #16: @7 = (@7*@1) */
  w7 *= w1;
  /* #17: @0 = (@0+@7) */
  w0 += w7;
  /* #18: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* fwd3_adj1_yr:(i0,i1[11],out_o0[1x1,0nz],adj_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],fwd_i0[1x3],fwd_i1[11x3],fwd_out_o0[1x3,0nz],fwd_adj_o0[1x3])->(fwd_adj_i0[1x3],fwd_adj_i1[11x3,0nz]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+9, *w3=w+18, *w4=w+28, *w5=w+39, *w6=w+59, w7, w8, w9;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x9) */
  casadi_clear(w2, 9);
  /* #3: @3 = zeros(1x10) */
  casadi_clear(w3, 10);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 11, w4);
  /* #5: @4 = @4' */
  /* #6: @5 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes(w4, casadi_s2, w5, casadi_s1, w3, casadi_s0, w, 0);
  /* #8: @6 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w6);
  /* #9: @2 = mac(@3,@6,@2) */
  casadi_mtimes(w3, casadi_s0, w6, casadi_s10, w2, casadi_s9, w, 0);
  /* #10: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w2,1,(&w1),casadi_s3, iw, w);
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #13: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #14: @9 = BSplineParametric(@1) */
  casadi_clear((&w9), 1);
  CASADI_PREFIX(nd_boor_eval)((&w9),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w3,1,(&w1),casadi_s3, iw, w);
  /* #15: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #16: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #17: @8 = (@8+@1) */
  w8 += w1;
  /* #18: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  /* #19: @8 = input[6][1] */
  w8 = arg[6] ? arg[6][1] : 0;
  /* #20: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #21: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #22: @1 = input[9][1] */
  w1 = arg[9] ? arg[9][1] : 0;
  /* #23: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #24: @8 = (@8+@1) */
  w8 += w1;
  /* #25: output[0][1] = @8 */
  if (res[0]) res[0][1] = w8;
  /* #26: @8 = input[6][2] */
  w8 = arg[6] ? arg[6][2] : 0;
  /* #27: @7 = (@7*@8) */
  w7 *= w8;
  /* #28: @0 = (@0*@7) */
  w0 *= w7;
  /* #29: @7 = input[9][2] */
  w7 = arg[9] ? arg[9][2] : 0;
  /* #30: @9 = (@9*@7) */
  w9 *= w7;
  /* #31: @0 = (@0+@9) */
  w0 += w9;
  /* #32: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

/* fwd3_adj1_xr:(i0,i1[11],out_o0[1x1,0nz],adj_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],fwd_i0[1x3],fwd_i1[11x3],fwd_out_o0[1x3,0nz],fwd_adj_o0[1x3])->(fwd_adj_i0[1x3],fwd_adj_i1[11x3,0nz]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+9, *w3=w+18, *w4=w+28, *w5=w+39, *w6=w+59, w7, w8, w9;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x9) */
  casadi_clear(w2, 9);
  /* #3: @3 = zeros(1x10) */
  casadi_clear(w3, 10);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 11, w4);
  /* #5: @4 = @4' */
  /* #6: @5 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes(w4, casadi_s2, w5, casadi_s1, w3, casadi_s0, w, 0);
  /* #8: @6 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w6);
  /* #9: @2 = mac(@3,@6,@2) */
  casadi_mtimes(w3, casadi_s0, w6, casadi_s10, w2, casadi_s9, w, 0);
  /* #10: @7 = BSplineParametric(@1) */
  casadi_clear((&w7), 1);
  CASADI_PREFIX(nd_boor_eval)((&w7),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w2,1,(&w1),casadi_s3, iw, w);
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #13: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #14: @9 = BSplineParametric(@1) */
  casadi_clear((&w9), 1);
  CASADI_PREFIX(nd_boor_eval)((&w9),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w3,1,(&w1),casadi_s3, iw, w);
  /* #15: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #16: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #17: @8 = (@8+@1) */
  w8 += w1;
  /* #18: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  /* #19: @8 = input[6][1] */
  w8 = arg[6] ? arg[6][1] : 0;
  /* #20: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #21: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #22: @1 = input[9][1] */
  w1 = arg[9] ? arg[9][1] : 0;
  /* #23: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #24: @8 = (@8+@1) */
  w8 += w1;
  /* #25: output[0][1] = @8 */
  if (res[0]) res[0][1] = w8;
  /* #26: @8 = input[6][2] */
  w8 = arg[6] ? arg[6][2] : 0;
  /* #27: @7 = (@7*@8) */
  w7 *= w8;
  /* #28: @0 = (@0*@7) */
  w0 *= w7;
  /* #29: @7 = input[9][2] */
  w7 = arg[9] ? arg[9][2] : 0;
  /* #30: @9 = (@9*@7) */
  w9 *= w7;
  /* #31: @0 = (@0+@9) */
  w0 += w9;
  /* #32: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

/* fwd3_adj1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],out_adj_out_o0[1x1,0nz],out_adj_fwd_i0[1x1,0nz],out_adj_fwd_i1[11x1,0nz],fwd_i0[1x3],fwd_i1[11x3],fwd_out_o0[1x3,0nz],fwd_fwd_i0[1x3],fwd_fwd_i1[11x3],fwd_out_fwd_o0[1x3,0nz],fwd_adj_fwd_o0[1x3])->(fwd_adj_i0[1x3],fwd_adj_i1[11x3,0nz],fwd_adj_out_o0[1x3,0nz],fwd_adj_fwd_i0[1x3],fwd_adj_fwd_i1[11x3,0nz]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, *w4=w+11, *w5=w+19, *w6=w+28, *w7=w+38, *w8=w+49, *w9=w+69, *w10=w+87, w11, w12, w13, w14, w15, w16, w17, w18, w19;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = zeros(1x8) */
  casadi_clear(w4, 8);
  /* #5: @5 = zeros(1x9) */
  casadi_clear(w5, 9);
  /* #6: @6 = zeros(1x10) */
  casadi_clear(w6, 10);
  /* #7: @7 = input[1][0] */
  casadi_copy(arg[1], 11, w7);
  /* #8: @7 = @7' */
  /* #9: @8 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w8);
  /* #10: @6 = mac(@7,@8,@6) */
  casadi_mtimes(w7, casadi_s2, w8, casadi_s1, w6, casadi_s0, w, 0);
  /* #11: @9 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w9);
  /* #12: @5 = mac(@6,@9,@5) */
  casadi_mtimes(w6, casadi_s0, w9, casadi_s10, w5, casadi_s9, w, 0);
  /* #13: @10 = 
  [[-1.25, 00, 00, 00, 00, 00, 00, 00], 
   [1.25, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.25], 
   [00, 00, 00, 00, 00, 00, 00, 1.25]] */
  casadi_copy(casadi_c5, 16, w10);
  /* #14: @4 = mac(@5,@10,@4) */
  casadi_mtimes(w5, casadi_s9, w10, casadi_s13, w4, casadi_s12, w, 0);
  /* #15: @11 = BSplineParametric(@3) */
  casadi_clear((&w11), 1);
  CASADI_PREFIX(nd_boor_eval)((&w11),1,casadi_c6,casadi_s14,casadi_s3,casadi_s4,w4,1,(&w3),casadi_s3, iw, w);
  /* #16: @12 = input[12][0] */
  w12 = arg[12] ? arg[12][0] : 0;
  /* #17: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #18: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #19: @14 = BSplineParametric(@3) */
  casadi_clear((&w14), 1);
  CASADI_PREFIX(nd_boor_eval)((&w14),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w5,1,(&w3),casadi_s3, iw, w);
  /* #20: @15 = input[15][0] */
  w15 = arg[15] ? arg[15][0] : 0;
  /* #21: @15 = (@1*@15) */
  w15  = (w1*w15);
  /* #22: @16 = input[18][0] */
  w16 = arg[18] ? arg[18][0] : 0;
  /* #23: @17 = (@0*@16) */
  w17  = (w0*w16);
  /* #24: @15 = (@15+@17) */
  w15 += w17;
  /* #25: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #26: @13 = (@13+@15) */
  w13 += w15;
  /* #27: output[0][0] = @13 */
  if (res[0]) res[0][0] = w13;
  /* #28: @13 = input[12][1] */
  w13 = arg[12] ? arg[12][1] : 0;
  /* #29: @15 = (@11*@13) */
  w15  = (w11*w13);
  /* #30: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #31: @17 = input[15][1] */
  w17 = arg[15] ? arg[15][1] : 0;
  /* #32: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #33: @18 = input[18][1] */
  w18 = arg[18] ? arg[18][1] : 0;
  /* #34: @19 = (@0*@18) */
  w19  = (w0*w18);
  /* #35: @17 = (@17+@19) */
  w17 += w19;
  /* #36: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #37: @15 = (@15+@17) */
  w15 += w17;
  /* #38: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  /* #39: @15 = input[12][2] */
  w15 = arg[12] ? arg[12][2] : 0;
  /* #40: @11 = (@11*@15) */
  w11 *= w15;
  /* #41: @2 = (@2*@11) */
  w2 *= w11;
  /* #42: @11 = input[15][2] */
  w11 = arg[15] ? arg[15][2] : 0;
  /* #43: @11 = (@1*@11) */
  w11  = (w1*w11);
  /* #44: @17 = input[18][2] */
  w17 = arg[18] ? arg[18][2] : 0;
  /* #45: @0 = (@0*@17) */
  w0 *= w17;
  /* #46: @11 = (@11+@0) */
  w11 += w0;
  /* #47: @11 = (@14*@11) */
  w11  = (w14*w11);
  /* #48: @2 = (@2+@11) */
  w2 += w11;
  /* #49: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #50: @12 = (@14*@12) */
  w12  = (w14*w12);
  /* #51: @12 = (@1*@12) */
  w12  = (w1*w12);
  /* #52: @2 = BSplineParametric(@3) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w6,1,(&w3),casadi_s3, iw, w);
  /* #53: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #54: @12 = (@12+@16) */
  w12 += w16;
  /* #55: output[3][0] = @12 */
  if (res[3]) res[3][0] = w12;
  /* #56: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #57: @13 = (@1*@13) */
  w13  = (w1*w13);
  /* #58: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #59: @13 = (@13+@18) */
  w13 += w18;
  /* #60: output[3][1] = @13 */
  if (res[3]) res[3][1] = w13;
  /* #61: @14 = (@14*@15) */
  w14 *= w15;
  /* #62: @1 = (@1*@14) */
  w1 *= w14;
  /* #63: @2 = (@2*@17) */
  w2 *= w17;
  /* #64: @1 = (@1+@2) */
  w1 += w2;
  /* #65: output[3][2] = @1 */
  if (res[3]) res[3][2] = w1;
  return 0;
}

/* fwd3_adj1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0,out_adj_i0[1x1,0nz],out_adj_i1[11x1,0nz],out_adj_out_o0[1x1,0nz],out_adj_fwd_i0[1x1,0nz],out_adj_fwd_i1[11x1,0nz],fwd_i0[1x3],fwd_i1[11x3],fwd_out_o0[1x3,0nz],fwd_fwd_i0[1x3],fwd_fwd_i1[11x3],fwd_out_fwd_o0[1x3,0nz],fwd_adj_fwd_o0[1x3])->(fwd_adj_i0[1x3],fwd_adj_i1[11x3,0nz],fwd_adj_out_o0[1x3,0nz],fwd_adj_fwd_i0[1x3],fwd_adj_fwd_i1[11x3,0nz]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, *w4=w+11, *w5=w+19, *w6=w+28, *w7=w+38, *w8=w+49, *w9=w+69, *w10=w+87, w11, w12, w13, w14, w15, w16, w17, w18, w19;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[6][0] */
  w1 = arg[6] ? arg[6][0] : 0;
  /* #2: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = zeros(1x8) */
  casadi_clear(w4, 8);
  /* #5: @5 = zeros(1x9) */
  casadi_clear(w5, 9);
  /* #6: @6 = zeros(1x10) */
  casadi_clear(w6, 10);
  /* #7: @7 = input[1][0] */
  casadi_copy(arg[1], 11, w7);
  /* #8: @7 = @7' */
  /* #9: @8 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w8);
  /* #10: @6 = mac(@7,@8,@6) */
  casadi_mtimes(w7, casadi_s2, w8, casadi_s1, w6, casadi_s0, w, 0);
  /* #11: @9 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w9);
  /* #12: @5 = mac(@6,@9,@5) */
  casadi_mtimes(w6, casadi_s0, w9, casadi_s10, w5, casadi_s9, w, 0);
  /* #13: @10 = 
  [[-1.25, 00, 00, 00, 00, 00, 00, 00], 
   [1.25, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.25], 
   [00, 00, 00, 00, 00, 00, 00, 1.25]] */
  casadi_copy(casadi_c5, 16, w10);
  /* #14: @4 = mac(@5,@10,@4) */
  casadi_mtimes(w5, casadi_s9, w10, casadi_s13, w4, casadi_s12, w, 0);
  /* #15: @11 = BSplineParametric(@3) */
  casadi_clear((&w11), 1);
  CASADI_PREFIX(nd_boor_eval)((&w11),1,casadi_c6,casadi_s14,casadi_s3,casadi_s4,w4,1,(&w3),casadi_s3, iw, w);
  /* #16: @12 = input[12][0] */
  w12 = arg[12] ? arg[12][0] : 0;
  /* #17: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #18: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #19: @14 = BSplineParametric(@3) */
  casadi_clear((&w14), 1);
  CASADI_PREFIX(nd_boor_eval)((&w14),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w5,1,(&w3),casadi_s3, iw, w);
  /* #20: @15 = input[15][0] */
  w15 = arg[15] ? arg[15][0] : 0;
  /* #21: @15 = (@1*@15) */
  w15  = (w1*w15);
  /* #22: @16 = input[18][0] */
  w16 = arg[18] ? arg[18][0] : 0;
  /* #23: @17 = (@0*@16) */
  w17  = (w0*w16);
  /* #24: @15 = (@15+@17) */
  w15 += w17;
  /* #25: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #26: @13 = (@13+@15) */
  w13 += w15;
  /* #27: output[0][0] = @13 */
  if (res[0]) res[0][0] = w13;
  /* #28: @13 = input[12][1] */
  w13 = arg[12] ? arg[12][1] : 0;
  /* #29: @15 = (@11*@13) */
  w15  = (w11*w13);
  /* #30: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #31: @17 = input[15][1] */
  w17 = arg[15] ? arg[15][1] : 0;
  /* #32: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #33: @18 = input[18][1] */
  w18 = arg[18] ? arg[18][1] : 0;
  /* #34: @19 = (@0*@18) */
  w19  = (w0*w18);
  /* #35: @17 = (@17+@19) */
  w17 += w19;
  /* #36: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #37: @15 = (@15+@17) */
  w15 += w17;
  /* #38: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  /* #39: @15 = input[12][2] */
  w15 = arg[12] ? arg[12][2] : 0;
  /* #40: @11 = (@11*@15) */
  w11 *= w15;
  /* #41: @2 = (@2*@11) */
  w2 *= w11;
  /* #42: @11 = input[15][2] */
  w11 = arg[15] ? arg[15][2] : 0;
  /* #43: @11 = (@1*@11) */
  w11  = (w1*w11);
  /* #44: @17 = input[18][2] */
  w17 = arg[18] ? arg[18][2] : 0;
  /* #45: @0 = (@0*@17) */
  w0 *= w17;
  /* #46: @11 = (@11+@0) */
  w11 += w0;
  /* #47: @11 = (@14*@11) */
  w11  = (w14*w11);
  /* #48: @2 = (@2+@11) */
  w2 += w11;
  /* #49: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #50: @12 = (@14*@12) */
  w12  = (w14*w12);
  /* #51: @12 = (@1*@12) */
  w12  = (w1*w12);
  /* #52: @2 = BSplineParametric(@3) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w6,1,(&w3),casadi_s3, iw, w);
  /* #53: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #54: @12 = (@12+@16) */
  w12 += w16;
  /* #55: output[3][0] = @12 */
  if (res[3]) res[3][0] = w12;
  /* #56: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #57: @13 = (@1*@13) */
  w13  = (w1*w13);
  /* #58: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #59: @13 = (@13+@18) */
  w13 += w18;
  /* #60: output[3][1] = @13 */
  if (res[3]) res[3][1] = w13;
  /* #61: @14 = (@14*@15) */
  w14 *= w15;
  /* #62: @1 = (@1*@14) */
  w1 *= w14;
  /* #63: @2 = (@2*@17) */
  w2 *= w17;
  /* #64: @1 = (@1+@2) */
  w1 += w2;
  /* #65: output[3][2] = @1 */
  if (res[3]) res[3][2] = w1;
  return 0;
}

/* unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess:(i0[6],i1[],i2[],i3[46])->(o0,o1[6],o2[6x6,9nz],o3[],o4[0x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+5, *rr, *ss;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, *w2=w+114, w4, *w5=w+126, w6, *w7=w+138, w9, *w10=w+150, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w54, w55, *w59=w+195, *w60=w+199, *w61=w+205, w62, w63, w64, w65, w69, w70, *w71=w+220, *w72=w+223, w74, w75, w76, w77, w78, w79, w80, *w82=w+263, w84, *w85=w+275, w86, w87, w88, w89, w90, w91, w92, *w93=w+293, *w94=w+296, *w95=w+299, *w96=w+332, *w97=w+335;
  /* #0: @0 = input[3][4] */
  w0 = arg[3] ? arg[3][36] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 11, w2);
  /* #3: @3 = 00 */
  /* #4: @4 = 1 */
  w4 = 1.;
  /* #5: @5 = zeros(11x1) */
  casadi_clear(w5, 11);
  /* #6: @6 = fwd1_xr(@1, @2, @3, @4, @5) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  res1[0]=(&w6);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @7 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+11 : 0, 11, w7);
  /* #8: @8 = 00 */
  /* #9: @9 = 1 */
  w9 = 1.;
  /* #10: @10 = zeros(11x1) */
  casadi_clear(w10, 11);
  /* #11: @11 = fwd1_yr(@1, @7, @8, @9, @10) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @12 = atan2(@6,@11) */
  w12  = atan2(w6,w11);
  /* #13: @13 = sin(@12) */
  w13 = sin( w12 );
  /* #14: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #15: @15 = xr(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  res1[0]=(&w15);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @16 = (@14-@15) */
  w16  = (w14-w15);
  /* #17: @17 = (@13*@16) */
  w17  = (w13*w16);
  /* #18: @18 = cos(@12) */
  w18 = cos( w12 );
  /* #19: @19 = input[0][1] */
  w19 = arg[0] ? arg[0][1] : 0;
  /* #20: @20 = yr(@1, @7) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  res1[0]=(&w20);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @21 = (@19-@20) */
  w21  = (w19-w20);
  /* #22: @22 = (@18*@21) */
  w22  = (w18*w21);
  /* #23: @17 = (@17-@22) */
  w17 -= w22;
  /* #24: @22 = sq(@17) */
  w22 = casadi_sq( w17 );
  /* #25: @22 = (@0*@22) */
  w22  = (w0*w22);
  /* #26: @23 = input[3][5] */
  w23 = arg[3] ? arg[3][37] : 0;
  /* #27: @24 = cos(@12) */
  w24 = cos( w12 );
  /* #28: @14 = (@14-@15) */
  w14 -= w15;
  /* #29: @15 = (@24*@14) */
  w15  = (w24*w14);
  /* #30: @15 = (-@15) */
  w15 = (- w15 );
  /* #31: @25 = sin(@12) */
  w25 = sin( w12 );
  /* #32: @19 = (@19-@20) */
  w19 -= w20;
  /* #33: @20 = (@25*@19) */
  w20  = (w25*w19);
  /* #34: @15 = (@15-@20) */
  w15 -= w20;
  /* #35: @20 = sq(@15) */
  w20 = casadi_sq( w15 );
  /* #36: @20 = (@23*@20) */
  w20  = (w23*w20);
  /* #37: @22 = (@22+@20) */
  w22 += w20;
  /* #38: @20 = input[3][6] */
  w20 = arg[3] ? arg[3][38] : 0;
  /* #39: @26 = input[0][5] */
  w26 = arg[0] ? arg[0][5] : 0;
  /* #40: @26 = (@20*@26) */
  w26  = (w20*w26);
  /* #41: @22 = (@22-@26) */
  w22 -= w26;
  /* #42: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  /* #43: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #44: @17 = (@17*@0) */
  w17 *= w0;
  /* #45: @22 = (@13*@17) */
  w22  = (w13*w17);
  /* #46: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #47: @15 = (@15*@23) */
  w15 *= w23;
  /* #48: @26 = (@24*@15) */
  w26  = (w24*w15);
  /* #49: @27 = (@22-@26) */
  w27  = (w22-w26);
  /* #50: @28 = (@18*@17) */
  w28  = (w18*w17);
  /* #51: @29 = (-@28) */
  w29 = (- w28 );
  /* #52: @30 = (@25*@15) */
  w30  = (w25*w15);
  /* #53: @29 = (@29-@30) */
  w29 -= w30;
  /* #54: @31 = 00 */
  /* #55: @32 = 00 */
  /* #56: @33 = 00 */
  /* #57: @30 = (@30+@28) */
  w30 += w28;
  /* #58: {@28, @34} = adj1_yr(@1, @7, @33, @30) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w30);
  res1[0]=(&w28);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #59: @35 = 00 */
  /* #60: @26 = (@26-@22) */
  w26 -= w22;
  /* #61: {@22, @36} = adj1_xr(@1, @2, @35, @26) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w26);
  res1[0]=(&w22);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #62: @28 = (@28+@22) */
  w28 += w22;
  /* #63: @37 = 00 */
  /* #64: @22 = sq(@6) */
  w22 = casadi_sq( w6 );
  /* #65: @38 = sq(@11) */
  w38 = casadi_sq( w11 );
  /* #66: @22 = (@22+@38) */
  w22 += w38;
  /* #67: @38 = (@6/@22) */
  w38  = (w6/w22);
  /* #68: @39 = sin(@12) */
  w39 = sin( w12 );
  /* #69: @40 = (@14*@15) */
  w40  = (w14*w15);
  /* #70: @41 = (@39*@40) */
  w41  = (w39*w40);
  /* #71: @42 = cos(@12) */
  w42 = cos( w12 );
  /* #72: @43 = (@19*@15) */
  w43  = (w19*w15);
  /* #73: @44 = (@42*@43) */
  w44  = (w42*w43);
  /* #74: @41 = (@41-@44) */
  w41 -= w44;
  /* #75: @44 = sin(@12) */
  w44 = sin( w12 );
  /* #76: @45 = (@21*@17) */
  w45  = (w21*w17);
  /* #77: @46 = (@44*@45) */
  w46  = (w44*w45);
  /* #78: @41 = (@41+@46) */
  w41 += w46;
  /* #79: @46 = cos(@12) */
  w46 = cos( w12 );
  /* #80: @47 = (@16*@17) */
  w47  = (w16*w17);
  /* #81: @48 = (@46*@47) */
  w48  = (w46*w47);
  /* #82: @41 = (@41+@48) */
  w41 += w48;
  /* #83: @48 = (@38*@41) */
  w48  = (w38*w41);
  /* #84: @48 = (-@48) */
  w48 = (- w48 );
  /* #85: {@49, @50, @51, NULL, @52} = adj1_fwd1_yr(@1, @7, @8, @9, @10, @37, @48) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  arg1[5]=0;
  arg1[6]=(&w48);
  res1[0]=(&w49);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #86: @28 = (@28+@49) */
  w28 += w49;
  /* #87: @53 = 00 */
  /* #88: @49 = (@11/@22) */
  w49  = (w11/w22);
  /* #89: @54 = (@49*@41) */
  w54  = (w49*w41);
  /* #90: {@55, @56, @57, NULL, @58} = adj1_fwd1_xr(@1, @2, @3, @4, @5, @53, @54) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  arg1[5]=0;
  arg1[6]=(&w54);
  res1[0]=(&w55);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #91: @28 = (@28+@55) */
  w28 += w55;
  /* #92: @20 = (-@20) */
  w20 = (- w20 );
  /* #93: @59 = vertcat(@27, @29, @31, @32, @28, @20) */
  rr=w59;
  *rr++ = w27;
  *rr++ = w29;
  *rr++ = w28;
  *rr++ = w20;
  /* #94: @60 = dense(@59) */
  casadi_densify(w59, casadi_s15, w60, 0);
  /* #95: output[1][0] = @60 */
  casadi_copy(w60, 6, res[1]);
  /* #96: @61 = zeros(6x6,9nz) */
  casadi_clear(w61, 9);
  /* #97: @59 = ones(6x1,4nz) */
  casadi_fill(w59, 4, 1.);
  /* #98: {@27, NULL, NULL, NULL, NULL, NULL} = vertsplit(@59) */
  w27 = w59[0];
  /* #99: @29 = (@13*@27) */
  w29  = (w13*w27);
  /* #100: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #101: @29 = (@0*@29) */
  w29  = (w0*w29);
  /* #102: @28 = (@13*@29) */
  w28  = (w13*w29);
  /* #103: @20 = (@24*@27) */
  w20  = (w24*w27);
  /* #104: @20 = (-@20) */
  w20 = (- w20 );
  /* #105: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #106: @20 = (@23*@20) */
  w20  = (w23*w20);
  /* #107: @55 = (@24*@20) */
  w55  = (w24*w20);
  /* #108: @62 = (@28-@55) */
  w62  = (w28-w55);
  /* #109: @63 = (@25*@20) */
  w63  = (w25*w20);
  /* #110: @64 = (-@63) */
  w64 = (- w63 );
  /* #111: @65 = (@18*@29) */
  w65  = (w18*w29);
  /* #112: @64 = (@64-@65) */
  w64 -= w65;
  /* #113: @31 = 00 */
  /* #114: @32 = 00 */
  /* #115: @66 = 00 */
  /* #116: @67 = 00 */
  /* #117: @68 = 00 */
  /* #118: @69 = ones(6x1,1nz) */
  w69 = 1.;
  /* #119: {NULL, NULL, NULL, NULL, @70, NULL} = vertsplit(@69) */
  w70 = w69;
  /* #120: @69 = horzcat(@67, @68, @70) */
  rr=(&w69);
  *rr++ = w70;
  /* #121: @71 = dense(@69) */
  casadi_densify((&w69), casadi_s16, w71, 0);
  /* #122: @72 = zeros(11x3) */
  casadi_clear(w72, 33);
  /* #123: @73 = zeros(1x3,0nz) */
  /* #124: @63 = (@63+@65) */
  w63 += w65;
  /* #125: @65 = ones(6x1,1nz) */
  w65 = 1.;
  /* #126: {NULL, @69, NULL, NULL, NULL, NULL} = vertsplit(@65) */
  w69 = w65;
  /* #127: @65 = (@25*@69) */
  w65  = (w25*w69);
  /* #128: @65 = (-@65) */
  w65 = (- w65 );
  /* #129: @65 = (2.*@65) */
  w65 = (2.* w65 );
  /* #130: @65 = (@23*@65) */
  w65  = (w23*w65);
  /* #131: @74 = (@25*@65) */
  w74  = (w25*w65);
  /* #132: @75 = (@18*@69) */
  w75  = (w18*w69);
  /* #133: @75 = (-@75) */
  w75 = (- w75 );
  /* #134: @75 = (2.*@75) */
  w75 = (2.* w75 );
  /* #135: @75 = (@0*@75) */
  w75  = (w0*w75);
  /* #136: @76 = (@18*@75) */
  w76  = (w18*w75);
  /* #137: @77 = (@74+@76) */
  w77  = (w74+w76);
  /* #138: @78 = cos(@12) */
  w78 = cos( w12 );
  /* #139: @79 = sq(@6) */
  w79 = casadi_sq( w6 );
  /* #140: @80 = sq(@11) */
  w80 = casadi_sq( w11 );
  /* #141: @79 = (@79+@80) */
  w79 += w80;
  /* #142: @80 = (@11/@79) */
  w80  = (w11/w79);
  /* #143: @81 = 00 */
  /* #144: @82 = zeros(11x1) */
  casadi_clear(w82, 11);
  /* #145: @83 = 00 */
  /* #146: @84 = 0 */
  w84 = 0.;
  /* #147: @85 = zeros(11x1) */
  casadi_clear(w85, 11);
  /* #148: @86 = fwd1_fwd1_xr(@1, @2, @3, @4, @5, @81, @70, @82, @83, @84, @85) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  arg1[5]=0;
  arg1[6]=(&w70);
  arg1[7]=w82;
  arg1[8]=0;
  arg1[9]=(&w84);
  arg1[10]=w85;
  res1[0]=(&w86);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #149: @80 = (@80*@86) */
  w80 *= w86;
  /* #150: @79 = (@6/@79) */
  w79  = (w6/w79);
  /* #151: @81 = 00 */
  /* #152: @82 = zeros(11x1) */
  casadi_clear(w82, 11);
  /* #153: @83 = 00 */
  /* #154: @84 = 0 */
  w84 = 0.;
  /* #155: @85 = zeros(11x1) */
  casadi_clear(w85, 11);
  /* #156: @87 = fwd1_fwd1_yr(@1, @7, @8, @9, @10, @81, @70, @82, @83, @84, @85) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  arg1[5]=0;
  arg1[6]=(&w70);
  arg1[7]=w82;
  arg1[8]=0;
  arg1[9]=(&w84);
  arg1[10]=w85;
  res1[0]=(&w87);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #157: @79 = (@79*@87) */
  w79 *= w87;
  /* #158: @80 = (@80-@79) */
  w80 -= w79;
  /* #159: @78 = (@78*@80) */
  w78 *= w80;
  /* #160: @79 = (@15*@78) */
  w79  = (w15*w78);
  /* #161: @78 = (@19*@78) */
  w78  = (w19*w78);
  /* #162: @81 = 00 */
  /* #163: @82 = zeros(11x1) */
  casadi_clear(w82, 11);
  /* #164: @84 = fwd1_yr(@1, @7, @81, @70, @82) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w70);
  arg1[4]=w82;
  res1[0]=(&w84);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #165: @88 = (@25*@84) */
  w88  = (w25*w84);
  /* #166: @78 = (@78-@88) */
  w78 -= w88;
  /* #167: @78 = (-@78) */
  w78 = (- w78 );
  /* #168: @81 = 00 */
  /* #169: @82 = zeros(11x1) */
  casadi_clear(w82, 11);
  /* #170: @88 = fwd1_xr(@1, @2, @81, @70, @82) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w70);
  arg1[4]=w82;
  res1[0]=(&w88);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #171: @89 = (@24*@88) */
  w89  = (w24*w88);
  /* #172: @89 = (-@89) */
  w89 = (- w89 );
  /* #173: @90 = sin(@12) */
  w90 = sin( w12 );
  /* #174: @90 = (@90*@80) */
  w90 *= w80;
  /* #175: @91 = (@14*@90) */
  w91  = (w14*w90);
  /* #176: @89 = (@89-@91) */
  w89 -= w91;
  /* #177: @78 = (@78-@89) */
  w78 -= w89;
  /* #178: @78 = (2.*@78) */
  w78 = (2.* w78 );
  /* #179: @23 = (@23*@78) */
  w23 *= w78;
  /* #180: @25 = (@25*@23) */
  w25 *= w23;
  /* #181: @79 = (@79+@25) */
  w79 += w25;
  /* #182: @25 = cos(@12) */
  w25 = cos( w12 );
  /* #183: @25 = (@25*@80) */
  w25 *= w80;
  /* #184: @78 = (@16*@25) */
  w78  = (w16*w25);
  /* #185: @89 = (@13*@88) */
  w89  = (w13*w88);
  /* #186: @78 = (@78-@89) */
  w78 -= w89;
  /* #187: @89 = (@18*@84) */
  w89  = (w18*w84);
  /* #188: @89 = (-@89) */
  w89 = (- w89 );
  /* #189: @91 = sin(@12) */
  w91 = sin( w12 );
  /* #190: @91 = (@91*@80) */
  w91 *= w80;
  /* #191: @92 = (@21*@91) */
  w92  = (w21*w91);
  /* #192: @89 = (@89-@92) */
  w89 -= w92;
  /* #193: @78 = (@78-@89) */
  w78 -= w89;
  /* #194: @78 = (2.*@78) */
  w78 = (2.* w78 );
  /* #195: @0 = (@0*@78) */
  w0 *= w78;
  /* #196: @18 = (@18*@0) */
  w18 *= w0;
  /* #197: @91 = (@17*@91) */
  w91  = (w17*w91);
  /* #198: @18 = (@18-@91) */
  w18 -= w91;
  /* #199: @91 = (@79+@18) */
  w91  = (w79+w18);
  /* #200: @93 = horzcat(@63, @77, @91) */
  rr=w93;
  *rr++ = w63;
  *rr++ = w77;
  *rr++ = w91;
  /* #201: {@94, NULL} = fwd3_adj1_yr(@1, @7, @33, @30, @66, @34, @71, @72, @73, @93) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w30);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=w71;
  arg1[7]=w72;
  arg1[8]=0;
  arg1[9]=w93;
  res1[0]=w94;
  res1[1]=0;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #202: {@30, @63, @77} = horzsplit(@94) */
  w30 = w94[0];
  w63 = w94[1];
  w77 = w94[2];
  /* #203: @33 = 00 */
  /* #204: @91 = horzcat(@67, @68, @70) */
  rr=(&w91);
  *rr++ = w70;
  /* #205: @94 = dense(@91) */
  casadi_densify((&w91), casadi_s16, w94, 0);
  /* #206: @72 = zeros(11x3) */
  casadi_clear(w72, 33);
  /* #207: @66 = zeros(1x3,0nz) */
  /* #208: @55 = (@55-@28) */
  w55 -= w28;
  /* #209: @28 = (@24*@65) */
  w28  = (w24*w65);
  /* #210: @91 = (@13*@75) */
  w91  = (w13*w75);
  /* #211: @78 = (@28-@91) */
  w78  = (w28-w91);
  /* #212: @24 = (@24*@23) */
  w24 *= w23;
  /* #213: @90 = (@15*@90) */
  w90  = (w15*w90);
  /* #214: @24 = (@24-@90) */
  w24 -= w90;
  /* #215: @25 = (@17*@25) */
  w25  = (w17*w25);
  /* #216: @13 = (@13*@0) */
  w13 *= w0;
  /* #217: @25 = (@25+@13) */
  w25 += w13;
  /* #218: @13 = (@24-@25) */
  w13  = (w24-w25);
  /* #219: @71 = horzcat(@55, @78, @13) */
  rr=w71;
  *rr++ = w55;
  *rr++ = w78;
  *rr++ = w13;
  /* #220: {@93, NULL} = fwd3_adj1_xr(@1, @2, @35, @26, @33, @36, @94, @72, @66, @71) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w26);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=w94;
  arg1[7]=w72;
  arg1[8]=0;
  arg1[9]=w71;
  res1[0]=w93;
  res1[1]=0;
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #221: {@26, @55, @78} = horzsplit(@93) */
  w26 = w93[0];
  w55 = w93[1];
  w78 = w93[2];
  /* #222: @30 = (@30+@26) */
  w30 += w26;
  /* #223: @35 = 00 */
  /* #224: @33 = 00 */
  /* #225: @26 = horzcat(@67, @68, @70) */
  rr=(&w26);
  *rr++ = w70;
  /* #226: @93 = dense(@26) */
  casadi_densify((&w26), casadi_s16, w93, 0);
  /* #227: @72 = zeros(11x3) */
  casadi_clear(w72, 33);
  /* #228: @36 = zeros(1x3,0nz) */
  /* #229: @94 = zeros(1x3) */
  casadi_clear(w94, 3);
  /* #230: @95 = zeros(11x3) */
  casadi_clear(w95, 33);
  /* #231: @66 = zeros(1x3,0nz) */
  /* #232: @26 = (@15*@27) */
  w26  = (w15*w27);
  /* #233: @13 = (@14*@20) */
  w13  = (w14*w20);
  /* #234: @26 = (@26+@13) */
  w26 += w13;
  /* #235: @26 = (@39*@26) */
  w26  = (w39*w26);
  /* #236: @20 = (@19*@20) */
  w20  = (w19*w20);
  /* #237: @20 = (@42*@20) */
  w20  = (w42*w20);
  /* #238: @26 = (@26-@20) */
  w26 -= w20;
  /* #239: @20 = (@21*@29) */
  w20  = (w21*w29);
  /* #240: @20 = (@44*@20) */
  w20  = (w44*w20);
  /* #241: @26 = (@26+@20) */
  w26 += w20;
  /* #242: @27 = (@17*@27) */
  w27  = (w17*w27);
  /* #243: @29 = (@16*@29) */
  w29  = (w16*w29);
  /* #244: @27 = (@27+@29) */
  w27 += w29;
  /* #245: @27 = (@46*@27) */
  w27  = (w46*w27);
  /* #246: @26 = (@26+@27) */
  w26 += w27;
  /* #247: @27 = (@38*@26) */
  w27  = (w38*w26);
  /* #248: @27 = (-@27) */
  w27 = (- w27 );
  /* #249: @29 = (@14*@65) */
  w29  = (w14*w65);
  /* #250: @29 = (@39*@29) */
  w29  = (w39*w29);
  /* #251: @20 = (@15*@69) */
  w20  = (w15*w69);
  /* #252: @65 = (@19*@65) */
  w65  = (w19*w65);
  /* #253: @20 = (@20+@65) */
  w20 += w65;
  /* #254: @20 = (@42*@20) */
  w20  = (w42*w20);
  /* #255: @29 = (@29-@20) */
  w29 -= w20;
  /* #256: @69 = (@17*@69) */
  w69  = (w17*w69);
  /* #257: @20 = (@21*@75) */
  w20  = (w21*w75);
  /* #258: @69 = (@69+@20) */
  w69 += w20;
  /* #259: @69 = (@44*@69) */
  w69  = (w44*w69);
  /* #260: @29 = (@29+@69) */
  w29 += w69;
  /* #261: @75 = (@16*@75) */
  w75  = (w16*w75);
  /* #262: @75 = (@46*@75) */
  w75  = (w46*w75);
  /* #263: @29 = (@29+@75) */
  w29 += w75;
  /* #264: @75 = (@38*@29) */
  w75  = (w38*w29);
  /* #265: @75 = (-@75) */
  w75 = (- w75 );
  /* #266: @69 = (@86/@22) */
  w69  = (w86/w22);
  /* #267: @20 = (@38/@22) */
  w20  = (w38/w22);
  /* #268: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #269: @6 = (@6*@86) */
  w6 *= w86;
  /* #270: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #271: @11 = (@11*@87) */
  w11 *= w87;
  /* #272: @6 = (@6+@11) */
  w6 += w11;
  /* #273: @20 = (@20*@6) */
  w20 *= w6;
  /* #274: @69 = (@69-@20) */
  w69 -= w20;
  /* #275: @69 = (@41*@69) */
  w69  = (w41*w69);
  /* #276: @20 = cos(@12) */
  w20 = cos( w12 );
  /* #277: @20 = (@20*@80) */
  w20 *= w80;
  /* #278: @40 = (@40*@20) */
  w40 *= w20;
  /* #279: @14 = (@14*@23) */
  w14 *= w23;
  /* #280: @20 = (@15*@88) */
  w20  = (w15*w88);
  /* #281: @14 = (@14-@20) */
  w14 -= w20;
  /* #282: @39 = (@39*@14) */
  w39 *= w14;
  /* #283: @40 = (@40+@39) */
  w40 += w39;
  /* #284: @19 = (@19*@23) */
  w19 *= w23;
  /* #285: @15 = (@15*@84) */
  w15 *= w84;
  /* #286: @19 = (@19-@15) */
  w19 -= w15;
  /* #287: @42 = (@42*@19) */
  w42 *= w19;
  /* #288: @19 = sin(@12) */
  w19 = sin( w12 );
  /* #289: @19 = (@19*@80) */
  w19 *= w80;
  /* #290: @43 = (@43*@19) */
  w43 *= w19;
  /* #291: @42 = (@42-@43) */
  w42 -= w43;
  /* #292: @40 = (@40-@42) */
  w40 -= w42;
  /* #293: @42 = cos(@12) */
  w42 = cos( w12 );
  /* #294: @42 = (@42*@80) */
  w42 *= w80;
  /* #295: @45 = (@45*@42) */
  w45 *= w42;
  /* #296: @21 = (@21*@0) */
  w21 *= w0;
  /* #297: @84 = (@17*@84) */
  w84  = (w17*w84);
  /* #298: @21 = (@21-@84) */
  w21 -= w84;
  /* #299: @44 = (@44*@21) */
  w44 *= w21;
  /* #300: @45 = (@45+@44) */
  w45 += w44;
  /* #301: @40 = (@40+@45) */
  w40 += w45;
  /* #302: @16 = (@16*@0) */
  w16 *= w0;
  /* #303: @17 = (@17*@88) */
  w17 *= w88;
  /* #304: @16 = (@16-@17) */
  w16 -= w17;
  /* #305: @46 = (@46*@16) */
  w46 *= w16;
  /* #306: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #307: @12 = (@12*@80) */
  w12 *= w80;
  /* #308: @47 = (@47*@12) */
  w47 *= w12;
  /* #309: @46 = (@46-@47) */
  w46 -= w47;
  /* #310: @40 = (@40+@46) */
  w40 += w46;
  /* #311: @38 = (@38*@40) */
  w38 *= w40;
  /* #312: @69 = (@69+@38) */
  w69 += w38;
  /* #313: @69 = (-@69) */
  w69 = (- w69 );
  /* #314: @71 = horzcat(@27, @75, @69) */
  rr=w71;
  *rr++ = w27;
  *rr++ = w75;
  *rr++ = w69;
  /* #315: {@96, NULL, NULL, NULL, NULL} = fwd3_adj1_fwd1_yr(@1, @7, @8, @9, @10, @37, @48, @35, @50, @51, @33, @52, @93, @72, @36, @94, @95, @66, @71) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  arg1[5]=0;
  arg1[6]=(&w48);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=w93;
  arg1[13]=w72;
  arg1[14]=0;
  arg1[15]=w94;
  arg1[16]=w95;
  arg1[17]=0;
  arg1[18]=w71;
  res1[0]=w96;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f13(arg1, res1, iw, w, 0)) return 1;
  /* #316: {@9, @48, @27} = horzsplit(@96) */
  w9 = w96[0];
  w48 = w96[1];
  w27 = w96[2];
  /* #317: @30 = (@30+@9) */
  w30 += w9;
  /* #318: @8 = 00 */
  /* #319: @37 = 00 */
  /* #320: @9 = horzcat(@67, @68, @70) */
  rr=(&w9);
  *rr++ = w70;
  /* #321: @96 = dense(@9) */
  casadi_densify((&w9), casadi_s16, w96, 0);
  /* #322: @72 = zeros(11x3) */
  casadi_clear(w72, 33);
  /* #323: @67 = zeros(1x3,0nz) */
  /* #324: @93 = zeros(1x3) */
  casadi_clear(w93, 3);
  /* #325: @95 = zeros(11x3) */
  casadi_clear(w95, 33);
  /* #326: @68 = zeros(1x3,0nz) */
  /* #327: @26 = (@49*@26) */
  w26  = (w49*w26);
  /* #328: @29 = (@49*@29) */
  w29  = (w49*w29);
  /* #329: @87 = (@87/@22) */
  w87 /= w22;
  /* #330: @22 = (@49/@22) */
  w22  = (w49/w22);
  /* #331: @22 = (@22*@6) */
  w22 *= w6;
  /* #332: @87 = (@87-@22) */
  w87 -= w22;
  /* #333: @41 = (@41*@87) */
  w41 *= w87;
  /* #334: @49 = (@49*@40) */
  w49 *= w40;
  /* #335: @41 = (@41+@49) */
  w41 += w49;
  /* #336: @94 = horzcat(@26, @29, @41) */
  rr=w94;
  *rr++ = w26;
  *rr++ = w29;
  *rr++ = w41;
  /* #337: {@71, NULL, NULL, NULL, NULL} = fwd3_adj1_fwd1_xr(@1, @2, @3, @4, @5, @53, @54, @8, @56, @57, @37, @58, @96, @72, @67, @93, @95, @68, @94) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  arg1[5]=0;
  arg1[6]=(&w54);
  arg1[7]=0;
  arg1[8]=0;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  arg1[12]=w96;
  arg1[13]=w72;
  arg1[14]=0;
  arg1[15]=w93;
  arg1[16]=w95;
  arg1[17]=0;
  arg1[18]=w94;
  res1[0]=w71;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f14(arg1, res1, iw, w, 0)) return 1;
  /* #338: {@1, @4, @54} = horzsplit(@71) */
  w1 = w71[0];
  w4 = w71[1];
  w54 = w71[2];
  /* #339: @30 = (@30+@1) */
  w30 += w1;
  /* #340: @3 = 00 */
  /* #341: @71 = vertcat(@62, @64, @31, @32, @30, @3) */
  rr=w71;
  *rr++ = w62;
  *rr++ = w64;
  *rr++ = w30;
  /* #342: @96 = @71[:3] */
  for (rr=w96, ss=w71+0; ss!=w71+3; ss+=1) *rr++ = *ss;
  /* #343: (@61[:3] = @96) */
  for (rr=w61+0, ss=w96; rr!=w61+3; rr+=1) *rr = *ss++;
  /* #344: @96 = @71[:3] */
  for (rr=w96, ss=w71+0; ss!=w71+3; ss+=1) *rr++ = *ss;
  /* #345: (@61[:9:3] = @96) */
  for (rr=w61+0, ss=w96; rr!=w61+9; rr+=3) *rr = *ss++;
  /* #346: @91 = (@91-@28) */
  w91 -= w28;
  /* #347: @74 = (-@74) */
  w74 = (- w74 );
  /* #348: @74 = (@74-@76) */
  w74 -= w76;
  /* #349: @31 = 00 */
  /* #350: @32 = 00 */
  /* #351: @63 = (@63+@55) */
  w63 += w55;
  /* #352: @63 = (@63+@48) */
  w63 += w48;
  /* #353: @63 = (@63+@4) */
  w63 += w4;
  /* #354: @3 = 00 */
  /* #355: @96 = vertcat(@91, @74, @31, @32, @63, @3) */
  rr=w96;
  *rr++ = w91;
  *rr++ = w74;
  *rr++ = w63;
  /* #356: @71 = @96[:3] */
  for (rr=w71, ss=w96+0; ss!=w96+3; ss+=1) *rr++ = *ss;
  /* #357: (@61[3:6] = @71) */
  for (rr=w61+3, ss=w71; rr!=w61+6; rr+=1) *rr = *ss++;
  /* #358: @71 = @96[:3] */
  for (rr=w71, ss=w96+0; ss!=w96+3; ss+=1) *rr++ = *ss;
  /* #359: (@61[1:10:3] = @71) */
  for (rr=w61+1, ss=w71; rr!=w61+10; rr+=3) *rr = *ss++;
  /* #360: @25 = (@25-@24) */
  w25 -= w24;
  /* #361: @79 = (-@79) */
  w79 = (- w79 );
  /* #362: @79 = (@79-@18) */
  w79 -= w18;
  /* #363: @31 = 00 */
  /* #364: @32 = 00 */
  /* #365: @77 = (@77+@78) */
  w77 += w78;
  /* #366: @77 = (@77+@27) */
  w77 += w27;
  /* #367: @77 = (@77+@54) */
  w77 += w54;
  /* #368: @3 = 00 */
  /* #369: @71 = vertcat(@25, @79, @31, @32, @77, @3) */
  rr=w71;
  *rr++ = w25;
  *rr++ = w79;
  *rr++ = w77;
  /* #370: @96 = @71[:3] */
  for (rr=w96, ss=w71+0; ss!=w71+3; ss+=1) *rr++ = *ss;
  /* #371: (@61[6:9] = @96) */
  for (rr=w61+6, ss=w96; rr!=w61+9; rr+=1) *rr = *ss++;
  /* #372: @96 = @71[:3] */
  for (rr=w96, ss=w71+0; ss!=w71+3; ss+=1) *rr++ = *ss;
  /* #373: (@61[2:11:3] = @96) */
  for (rr=w61+2, ss=w96; rr!=w61+11; rr+=3) *rr = *ss++;
  /* #374: @97 = @61' */
  casadi_trans(w61,casadi_s17, w97, casadi_s17, iw);
  /* #375: output[2][0] = @97 */
  casadi_copy(w97, 9, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s19;
    case 3: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s21;
    case 1: return casadi_s18;
    case 2: return casadi_s17;
    case 3: return casadi_s19;
    case 4: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 26;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 344;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
