/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) unicycle_model_mpcc_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[33] = {11, 10, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10};
static const casadi_int casadi_s2[25] = {1, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[1] = {1};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[2] = {0, 13};
static const casadi_int casadi_s7[1] = {3};
static const casadi_int casadi_s8[2] = {0, 15};
static const casadi_int casadi_s9[21] = {1, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s10[30] = {10, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9};
static const casadi_int casadi_s11[2] = {0, 11};
static const casadi_int casadi_s12[11] = {9, 1, 0, 7, 0, 1, 2, 3, 4, 7, 8};
static const casadi_int casadi_s13[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s14[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s15[4] = {0, 1, 0, 0};
static const casadi_int casadi_s16[50] = {46, 1, 0, 46, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45};
static const casadi_int casadi_s17[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s18[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

static const casadi_real casadi_c0[20] = {-3.7500000000000000e+00, 3.7500000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000000e+00, 1.8750000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -1.8750000000000004e+00, 1.8750000000000004e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -3.7500000000000009e+00, 3.7500000000000009e+00};
static const casadi_real casadi_c1[13] = {0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4.};
static const casadi_real casadi_c2[15] = {0., 0., 0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4., 4., 4.};
static const casadi_real casadi_c3[18] = {-2.5000000000000000e+00, 2.5000000000000000e+00, -1.6666666666666665e+00, 1.6666666666666665e+00, -2.5000000000000000e+00, 2.5000000000000000e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.4999999999999991e+00, 2.4999999999999991e+00, -2.5000000000000004e+00, 2.5000000000000004e+00, -1.6666666666666670e+00, 1.6666666666666670e+00, -2.5000000000000004e+00, 2.5000000000000004e+00};
static const casadi_real casadi_c4[11] = {0., 0., 8.0000000000000004e-01, 1.2000000000000002e+00, 1.6000000000000001e+00, 2., 2.4000000000000004e+00, 2.8000000000000003e+00, 3.2000000000000002e+00, 4., 4.};

/* fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11])->(fwd_o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* xr:(i0,i1[11])->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* yr:(i0,i1[11])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+10, w2;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 11, w1);
  /* #2: @2 = BSplineParametric(@0) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c2,casadi_s8,casadi_s7,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* adj1_yr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_xr:(i0,i1[11],out_o0[1x1,0nz],adj_o0)->(adj_i0,adj_i1[11x1,0nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+18, *w3=w+29, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x10) */
  casadi_clear(w1, 10);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 11, w2);
  /* #3: @2 = @2' */
  /* #4: @3 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w3);
  /* #5: @1 = mac(@2,@3,@1) */
  casadi_mtimes(w2, casadi_s2, w3, casadi_s1, w1, casadi_s0, w, 0);
  /* #6: @4 = BSplineParametric(@0) */
  casadi_clear((&w4), 1);
  CASADI_PREFIX(nd_boor_eval)((&w4),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4*@0) */
  w4 *= w0;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  return 0;
}

/* adj1_fwd1_yr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* adj1_fwd1_xr:(i0,i1[11],out_o0[1x1,0nz],fwd_i0,fwd_i1[11],out_fwd_o0[1x1,0nz],adj_fwd_o0)->(adj_i0,adj_i1[11x1,0nz],adj_out_o0[1x1,0nz],adj_fwd_i0,adj_fwd_i1[11x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+8, *w2=w+17, *w3=w+27, *w4=w+38, *w5=w+58, w6, w7, w8;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x9) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(1x10) */
  casadi_clear(w2, 10);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 11, w3);
  /* #4: @3 = @3' */
  /* #5: @4 = sparse: 11-by-10, 20 nnz
   (0, 0) -> -3.75
   (1, 0) -> 3.75
   (1, 1) -> -2.5
   (2, 1) -> 2.5
   (2, 2) -> -1.875
   (3, 2) -> 1.875
   (3, 3) -> -2.5
   (4, 3) -> 2.5
   (4, 4) -> -2.5
   (5, 4) -> 2.5
   (5, 5) -> -2.5
   (6, 5) -> 2.5
   (6, 6) -> -2.5
   (7, 6) -> 2.5
   (7, 7) -> -1.875
   (8, 7) -> 1.875
   (8, 8) -> -2.5
   (9, 8) -> 2.5
   (9, 9) -> -3.75
   (10, 9) -> 3.75 */
  casadi_copy(casadi_c0, 20, w4);
  /* #6: @2 = mac(@3,@4,@2) */
  casadi_mtimes(w3, casadi_s2, w4, casadi_s1, w2, casadi_s0, w, 0);
  /* #7: @5 = 
  [[-2.5, 00, 00, 00, 00, 00, 00, 00, 00], 
   [2.5, -1.66667, 00, 00, 00, 00, 00, 00, 00], 
   [00, 1.66667, -2.5, 00, 00, 00, 00, 00, 00], 
   [00, 00, 2.5, -2.5, 00, 00, 00, 00, 00], 
   [00, 00, 00, 2.5, -2.5, 00, 00, 00, 00], 
   [00, 00, 00, 00, 2.5, -2.5, 00, 00, 00], 
   [00, 00, 00, 00, 00, 2.5, -2.5, 00, 00], 
   [00, 00, 00, 00, 00, 00, 2.5, -1.66667, 00], 
   [00, 00, 00, 00, 00, 00, 00, 1.66667, -2.5], 
   [00, 00, 00, 00, 00, 00, 00, 00, 2.5]] */
  casadi_copy(casadi_c3, 18, w5);
  /* #8: @1 = mac(@2,@5,@1) */
  casadi_mtimes(w2, casadi_s0, w5, casadi_s10, w1, casadi_s9, w, 0);
  /* #9: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s11,casadi_s4,casadi_s4,w1,1,(&w0),casadi_s3, iw, w);
  /* #10: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #11: @8 = input[6][0] */
  w8 = arg[6] ? arg[6][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @6 = (@6*@7) */
  w6 *= w7;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #15: @6 = BSplineParametric(@0) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c1,casadi_s6,casadi_s5,casadi_s4,w2,1,(&w0),casadi_s3, iw, w);
  /* #16: @6 = (@6*@8) */
  w6 *= w8;
  /* #17: output[3][0] = @6 */
  if (res[3]) res[3][0] = w6;
  return 0;
}

/* unicycle_model_mpcc_cost_ext_cost_0_fun_jac:(i0[6],i1[3],i2[0],i3[46])->(o0,o1[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, *w2=w+81, w4, *w5=w+93, w6, *w7=w+105, w9, *w10=w+117, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, *w33=w+147, *w34=w+154;
  /* #0: @0 = input[3][4] */
  w0 = arg[3] ? arg[3][36] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 11, w2);
  /* #3: @3 = 00 */
  /* #4: @4 = 1 */
  w4 = 1.;
  /* #5: @5 = zeros(11x1) */
  casadi_clear(w5, 11);
  /* #6: @6 = fwd1_xr(@1, @2, @3, @4, @5) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  res1[0]=(&w6);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @7 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+11 : 0, 11, w7);
  /* #8: @8 = 00 */
  /* #9: @9 = 1 */
  w9 = 1.;
  /* #10: @10 = zeros(11x1) */
  casadi_clear(w10, 11);
  /* #11: @11 = fwd1_yr(@1, @7, @8, @9, @10) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @12 = atan2(@6,@11) */
  w12  = atan2(w6,w11);
  /* #13: @13 = sin(@12) */
  w13 = sin( w12 );
  /* #14: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #15: @15 = xr(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  res1[0]=(&w15);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @16 = (@14-@15) */
  w16  = (w14-w15);
  /* #17: @17 = (@13*@16) */
  w17  = (w13*w16);
  /* #18: @18 = cos(@12) */
  w18 = cos( w12 );
  /* #19: @19 = input[0][1] */
  w19 = arg[0] ? arg[0][1] : 0;
  /* #20: @20 = yr(@1, @7) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  res1[0]=(&w20);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @21 = (@19-@20) */
  w21  = (w19-w20);
  /* #22: @22 = (@18*@21) */
  w22  = (w18*w21);
  /* #23: @17 = (@17-@22) */
  w17 -= w22;
  /* #24: @22 = sq(@17) */
  w22 = casadi_sq( w17 );
  /* #25: @22 = (@0*@22) */
  w22  = (w0*w22);
  /* #26: @23 = input[3][5] */
  w23 = arg[3] ? arg[3][37] : 0;
  /* #27: @24 = cos(@12) */
  w24 = cos( w12 );
  /* #28: @14 = (@14-@15) */
  w14 -= w15;
  /* #29: @15 = (@24*@14) */
  w15  = (w24*w14);
  /* #30: @15 = (-@15) */
  w15 = (- w15 );
  /* #31: @25 = sin(@12) */
  w25 = sin( w12 );
  /* #32: @19 = (@19-@20) */
  w19 -= w20;
  /* #33: @20 = (@25*@19) */
  w20  = (w25*w19);
  /* #34: @15 = (@15-@20) */
  w15 -= w20;
  /* #35: @20 = sq(@15) */
  w20 = casadi_sq( w15 );
  /* #36: @20 = (@23*@20) */
  w20  = (w23*w20);
  /* #37: @22 = (@22+@20) */
  w22 += w20;
  /* #38: @20 = input[1][0] */
  w20 = arg[1] ? arg[1][0] : 0;
  /* #39: @26 = sq(@20) */
  w26 = casadi_sq( w20 );
  /* #40: @22 = (@22+@26) */
  w22 += w26;
  /* #41: @26 = input[1][1] */
  w26 = arg[1] ? arg[1][1] : 0;
  /* #42: @27 = sq(@26) */
  w27 = casadi_sq( w26 );
  /* #43: @22 = (@22+@27) */
  w22 += w27;
  /* #44: @27 = 0.1 */
  w27 = 1.0000000000000001e-01;
  /* #45: @28 = input[1][2] */
  w28 = arg[1] ? arg[1][2] : 0;
  /* #46: @29 = sq(@28) */
  w29 = casadi_sq( w28 );
  /* #47: @27 = (@27*@29) */
  w27 *= w29;
  /* #48: @22 = (@22+@27) */
  w22 += w27;
  /* #49: @27 = input[3][6] */
  w27 = arg[3] ? arg[3][38] : 0;
  /* #50: @29 = input[0][5] */
  w29 = arg[0] ? arg[0][5] : 0;
  /* #51: @29 = (@27*@29) */
  w29  = (w27*w29);
  /* #52: @22 = (@22-@29) */
  w22 -= w29;
  /* #53: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  /* #54: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #55: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #56: @22 = 0.1 */
  w22 = 1.0000000000000001e-01;
  /* #57: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #58: @22 = (@22*@28) */
  w22 *= w28;
  /* #59: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #60: @17 = (@17*@0) */
  w17 *= w0;
  /* #61: @13 = (@13*@17) */
  w13 *= w17;
  /* #62: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #63: @15 = (@15*@23) */
  w15 *= w23;
  /* #64: @24 = (@24*@15) */
  w24 *= w15;
  /* #65: @23 = (@13-@24) */
  w23  = (w13-w24);
  /* #66: @18 = (@18*@17) */
  w18 *= w17;
  /* #67: @0 = (-@18) */
  w0 = (- w18 );
  /* #68: @25 = (@25*@15) */
  w25 *= w15;
  /* #69: @0 = (@0-@25) */
  w0 -= w25;
  /* #70: @30 = 00 */
  /* #71: @31 = 00 */
  /* #72: @32 = 00 */
  /* #73: @25 = (@25+@18) */
  w25 += w18;
  /* #74: {@18, NULL} = adj1_yr(@1, @7, @32, @25) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w25);
  res1[0]=(&w18);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #75: @32 = 00 */
  /* #76: @24 = (@24-@13) */
  w24 -= w13;
  /* #77: {@13, NULL} = adj1_xr(@1, @2, @32, @24) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w24);
  res1[0]=(&w13);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #78: @18 = (@18+@13) */
  w18 += w13;
  /* #79: @32 = 00 */
  /* #80: @13 = sq(@6) */
  w13 = casadi_sq( w6 );
  /* #81: @24 = sq(@11) */
  w24 = casadi_sq( w11 );
  /* #82: @13 = (@13+@24) */
  w13 += w24;
  /* #83: @6 = (@6/@13) */
  w6 /= w13;
  /* #84: @24 = sin(@12) */
  w24 = sin( w12 );
  /* #85: @14 = (@14*@15) */
  w14 *= w15;
  /* #86: @24 = (@24*@14) */
  w24 *= w14;
  /* #87: @14 = cos(@12) */
  w14 = cos( w12 );
  /* #88: @19 = (@19*@15) */
  w19 *= w15;
  /* #89: @14 = (@14*@19) */
  w14 *= w19;
  /* #90: @24 = (@24-@14) */
  w24 -= w14;
  /* #91: @14 = sin(@12) */
  w14 = sin( w12 );
  /* #92: @21 = (@21*@17) */
  w21 *= w17;
  /* #93: @14 = (@14*@21) */
  w14 *= w21;
  /* #94: @24 = (@24+@14) */
  w24 += w14;
  /* #95: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #96: @16 = (@16*@17) */
  w16 *= w17;
  /* #97: @12 = (@12*@16) */
  w12 *= w16;
  /* #98: @24 = (@24+@12) */
  w24 += w12;
  /* #99: @6 = (@6*@24) */
  w6 *= w24;
  /* #100: @6 = (-@6) */
  w6 = (- w6 );
  /* #101: {@12, NULL, NULL, NULL, NULL} = adj1_fwd1_yr(@1, @7, @8, @9, @10, @32, @6) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w9);
  arg1[4]=w10;
  arg1[5]=0;
  arg1[6]=(&w6);
  res1[0]=(&w12);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #102: @18 = (@18+@12) */
  w18 += w12;
  /* #103: @8 = 00 */
  /* #104: @11 = (@11/@13) */
  w11 /= w13;
  /* #105: @11 = (@11*@24) */
  w11 *= w24;
  /* #106: {@24, NULL, NULL, NULL, NULL} = adj1_fwd1_xr(@1, @2, @3, @4, @5, @8, @11) */
  arg1[0]=(&w1);
  arg1[1]=w2;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=w5;
  arg1[5]=0;
  arg1[6]=(&w11);
  res1[0]=(&w24);
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #107: @18 = (@18+@24) */
  w18 += w24;
  /* #108: @27 = (-@27) */
  w27 = (- w27 );
  /* #109: @33 = vertcat(@20, @26, @22, @23, @0, @30, @31, @18, @27) */
  rr=w33;
  *rr++ = w20;
  *rr++ = w26;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w0;
  *rr++ = w18;
  *rr++ = w27;
  /* #110: @34 = dense(@33) */
  casadi_densify(w33, casadi_s12, w34, 0);
  /* #111: output[1][0] = @34 */
  casadi_copy(w34, 9, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void unicycle_model_mpcc_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real unicycle_model_mpcc_cost_ext_cost_0_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    case 3: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* unicycle_model_mpcc_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int unicycle_model_mpcc_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 163;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
