
/*
Auto-generated by CVXPYgen on August 24, 2025 at 04:13:00.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_Domain(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_A_mat(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_b_vec(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1402] = val;
  Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_c(){
  for(i=0; i<7; i++){
    Canon_Params.c[i] = 0;
    for(j=canon_c_map.p[i]; j<canon_c_map.p[i+1]; j++){
      Canon_Params.c[i] += canon_c_map.x[j]*cpg_params_vec[canon_c_map.i[j]];
    }
  }
}

void cpg_canonicalize_G(){
  for(i=0; i<1400; i++){
    Canon_Params.G->x[i] = 0;
    for(j=canon_G_map.p[i]; j<canon_G_map.p[i+1]; j++){
      Canon_Params.G->x[i] += canon_G_map.x[j]*cpg_params_vec[canon_G_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<200; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.var2[0] = ecos_workspace->x[0];
  CPG_Prim.var2[1] = ecos_workspace->x[1];
  CPG_Prim.var2[2] = ecos_workspace->x[2];
  CPG_Prim.var2[3] = ecos_workspace->x[3];
  CPG_Prim.var2[4] = ecos_workspace->x[4];
  CPG_Prim.var2[5] = ecos_workspace->x[5];
  CPG_Prim.var2[6] = ecos_workspace->x[6];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = ecos_workspace->z[0];
  CPG_Dual.d0[1] = ecos_workspace->z[1];
  CPG_Dual.d0[2] = ecos_workspace->z[2];
  CPG_Dual.d0[3] = ecos_workspace->z[3];
  CPG_Dual.d0[4] = ecos_workspace->z[4];
  CPG_Dual.d0[5] = ecos_workspace->z[5];
  CPG_Dual.d0[6] = ecos_workspace->z[6];
  CPG_Dual.d0[7] = ecos_workspace->z[7];
  CPG_Dual.d0[8] = ecos_workspace->z[8];
  CPG_Dual.d0[9] = ecos_workspace->z[9];
  CPG_Dual.d0[10] = ecos_workspace->z[10];
  CPG_Dual.d0[11] = ecos_workspace->z[11];
  CPG_Dual.d0[12] = ecos_workspace->z[12];
  CPG_Dual.d0[13] = ecos_workspace->z[13];
  CPG_Dual.d0[14] = ecos_workspace->z[14];
  CPG_Dual.d0[15] = ecos_workspace->z[15];
  CPG_Dual.d0[16] = ecos_workspace->z[16];
  CPG_Dual.d0[17] = ecos_workspace->z[17];
  CPG_Dual.d0[18] = ecos_workspace->z[18];
  CPG_Dual.d0[19] = ecos_workspace->z[19];
  CPG_Dual.d0[20] = ecos_workspace->z[20];
  CPG_Dual.d0[21] = ecos_workspace->z[21];
  CPG_Dual.d0[22] = ecos_workspace->z[22];
  CPG_Dual.d0[23] = ecos_workspace->z[23];
  CPG_Dual.d0[24] = ecos_workspace->z[24];
  CPG_Dual.d0[25] = ecos_workspace->z[25];
  CPG_Dual.d0[26] = ecos_workspace->z[26];
  CPG_Dual.d0[27] = ecos_workspace->z[27];
  CPG_Dual.d0[28] = ecos_workspace->z[28];
  CPG_Dual.d0[29] = ecos_workspace->z[29];
  CPG_Dual.d0[30] = ecos_workspace->z[30];
  CPG_Dual.d0[31] = ecos_workspace->z[31];
  CPG_Dual.d0[32] = ecos_workspace->z[32];
  CPG_Dual.d0[33] = ecos_workspace->z[33];
  CPG_Dual.d0[34] = ecos_workspace->z[34];
  CPG_Dual.d0[35] = ecos_workspace->z[35];
  CPG_Dual.d0[36] = ecos_workspace->z[36];
  CPG_Dual.d0[37] = ecos_workspace->z[37];
  CPG_Dual.d0[38] = ecos_workspace->z[38];
  CPG_Dual.d0[39] = ecos_workspace->z[39];
  CPG_Dual.d0[40] = ecos_workspace->z[40];
  CPG_Dual.d0[41] = ecos_workspace->z[41];
  CPG_Dual.d0[42] = ecos_workspace->z[42];
  CPG_Dual.d0[43] = ecos_workspace->z[43];
  CPG_Dual.d0[44] = ecos_workspace->z[44];
  CPG_Dual.d0[45] = ecos_workspace->z[45];
  CPG_Dual.d0[46] = ecos_workspace->z[46];
  CPG_Dual.d0[47] = ecos_workspace->z[47];
  CPG_Dual.d0[48] = ecos_workspace->z[48];
  CPG_Dual.d0[49] = ecos_workspace->z[49];
  CPG_Dual.d0[50] = ecos_workspace->z[50];
  CPG_Dual.d0[51] = ecos_workspace->z[51];
  CPG_Dual.d0[52] = ecos_workspace->z[52];
  CPG_Dual.d0[53] = ecos_workspace->z[53];
  CPG_Dual.d0[54] = ecos_workspace->z[54];
  CPG_Dual.d0[55] = ecos_workspace->z[55];
  CPG_Dual.d0[56] = ecos_workspace->z[56];
  CPG_Dual.d0[57] = ecos_workspace->z[57];
  CPG_Dual.d0[58] = ecos_workspace->z[58];
  CPG_Dual.d0[59] = ecos_workspace->z[59];
  CPG_Dual.d0[60] = ecos_workspace->z[60];
  CPG_Dual.d0[61] = ecos_workspace->z[61];
  CPG_Dual.d0[62] = ecos_workspace->z[62];
  CPG_Dual.d0[63] = ecos_workspace->z[63];
  CPG_Dual.d0[64] = ecos_workspace->z[64];
  CPG_Dual.d0[65] = ecos_workspace->z[65];
  CPG_Dual.d0[66] = ecos_workspace->z[66];
  CPG_Dual.d0[67] = ecos_workspace->z[67];
  CPG_Dual.d0[68] = ecos_workspace->z[68];
  CPG_Dual.d0[69] = ecos_workspace->z[69];
  CPG_Dual.d0[70] = ecos_workspace->z[70];
  CPG_Dual.d0[71] = ecos_workspace->z[71];
  CPG_Dual.d0[72] = ecos_workspace->z[72];
  CPG_Dual.d0[73] = ecos_workspace->z[73];
  CPG_Dual.d0[74] = ecos_workspace->z[74];
  CPG_Dual.d0[75] = ecos_workspace->z[75];
  CPG_Dual.d0[76] = ecos_workspace->z[76];
  CPG_Dual.d0[77] = ecos_workspace->z[77];
  CPG_Dual.d0[78] = ecos_workspace->z[78];
  CPG_Dual.d0[79] = ecos_workspace->z[79];
  CPG_Dual.d0[80] = ecos_workspace->z[80];
  CPG_Dual.d0[81] = ecos_workspace->z[81];
  CPG_Dual.d0[82] = ecos_workspace->z[82];
  CPG_Dual.d0[83] = ecos_workspace->z[83];
  CPG_Dual.d0[84] = ecos_workspace->z[84];
  CPG_Dual.d0[85] = ecos_workspace->z[85];
  CPG_Dual.d0[86] = ecos_workspace->z[86];
  CPG_Dual.d0[87] = ecos_workspace->z[87];
  CPG_Dual.d0[88] = ecos_workspace->z[88];
  CPG_Dual.d0[89] = ecos_workspace->z[89];
  CPG_Dual.d0[90] = ecos_workspace->z[90];
  CPG_Dual.d0[91] = ecos_workspace->z[91];
  CPG_Dual.d0[92] = ecos_workspace->z[92];
  CPG_Dual.d0[93] = ecos_workspace->z[93];
  CPG_Dual.d0[94] = ecos_workspace->z[94];
  CPG_Dual.d0[95] = ecos_workspace->z[95];
  CPG_Dual.d0[96] = ecos_workspace->z[96];
  CPG_Dual.d0[97] = ecos_workspace->z[97];
  CPG_Dual.d0[98] = ecos_workspace->z[98];
  CPG_Dual.d0[99] = ecos_workspace->z[99];
  CPG_Dual.d0[100] = ecos_workspace->z[100];
  CPG_Dual.d0[101] = ecos_workspace->z[101];
  CPG_Dual.d0[102] = ecos_workspace->z[102];
  CPG_Dual.d0[103] = ecos_workspace->z[103];
  CPG_Dual.d0[104] = ecos_workspace->z[104];
  CPG_Dual.d0[105] = ecos_workspace->z[105];
  CPG_Dual.d0[106] = ecos_workspace->z[106];
  CPG_Dual.d0[107] = ecos_workspace->z[107];
  CPG_Dual.d0[108] = ecos_workspace->z[108];
  CPG_Dual.d0[109] = ecos_workspace->z[109];
  CPG_Dual.d0[110] = ecos_workspace->z[110];
  CPG_Dual.d0[111] = ecos_workspace->z[111];
  CPG_Dual.d0[112] = ecos_workspace->z[112];
  CPG_Dual.d0[113] = ecos_workspace->z[113];
  CPG_Dual.d0[114] = ecos_workspace->z[114];
  CPG_Dual.d0[115] = ecos_workspace->z[115];
  CPG_Dual.d0[116] = ecos_workspace->z[116];
  CPG_Dual.d0[117] = ecos_workspace->z[117];
  CPG_Dual.d0[118] = ecos_workspace->z[118];
  CPG_Dual.d0[119] = ecos_workspace->z[119];
  CPG_Dual.d0[120] = ecos_workspace->z[120];
  CPG_Dual.d0[121] = ecos_workspace->z[121];
  CPG_Dual.d0[122] = ecos_workspace->z[122];
  CPG_Dual.d0[123] = ecos_workspace->z[123];
  CPG_Dual.d0[124] = ecos_workspace->z[124];
  CPG_Dual.d0[125] = ecos_workspace->z[125];
  CPG_Dual.d0[126] = ecos_workspace->z[126];
  CPG_Dual.d0[127] = ecos_workspace->z[127];
  CPG_Dual.d0[128] = ecos_workspace->z[128];
  CPG_Dual.d0[129] = ecos_workspace->z[129];
  CPG_Dual.d0[130] = ecos_workspace->z[130];
  CPG_Dual.d0[131] = ecos_workspace->z[131];
  CPG_Dual.d0[132] = ecos_workspace->z[132];
  CPG_Dual.d0[133] = ecos_workspace->z[133];
  CPG_Dual.d0[134] = ecos_workspace->z[134];
  CPG_Dual.d0[135] = ecos_workspace->z[135];
  CPG_Dual.d0[136] = ecos_workspace->z[136];
  CPG_Dual.d0[137] = ecos_workspace->z[137];
  CPG_Dual.d0[138] = ecos_workspace->z[138];
  CPG_Dual.d0[139] = ecos_workspace->z[139];
  CPG_Dual.d0[140] = ecos_workspace->z[140];
  CPG_Dual.d0[141] = ecos_workspace->z[141];
  CPG_Dual.d0[142] = ecos_workspace->z[142];
  CPG_Dual.d0[143] = ecos_workspace->z[143];
  CPG_Dual.d0[144] = ecos_workspace->z[144];
  CPG_Dual.d0[145] = ecos_workspace->z[145];
  CPG_Dual.d0[146] = ecos_workspace->z[146];
  CPG_Dual.d0[147] = ecos_workspace->z[147];
  CPG_Dual.d0[148] = ecos_workspace->z[148];
  CPG_Dual.d0[149] = ecos_workspace->z[149];
  CPG_Dual.d0[150] = ecos_workspace->z[150];
  CPG_Dual.d0[151] = ecos_workspace->z[151];
  CPG_Dual.d0[152] = ecos_workspace->z[152];
  CPG_Dual.d0[153] = ecos_workspace->z[153];
  CPG_Dual.d0[154] = ecos_workspace->z[154];
  CPG_Dual.d0[155] = ecos_workspace->z[155];
  CPG_Dual.d0[156] = ecos_workspace->z[156];
  CPG_Dual.d0[157] = ecos_workspace->z[157];
  CPG_Dual.d0[158] = ecos_workspace->z[158];
  CPG_Dual.d0[159] = ecos_workspace->z[159];
  CPG_Dual.d0[160] = ecos_workspace->z[160];
  CPG_Dual.d0[161] = ecos_workspace->z[161];
  CPG_Dual.d0[162] = ecos_workspace->z[162];
  CPG_Dual.d0[163] = ecos_workspace->z[163];
  CPG_Dual.d0[164] = ecos_workspace->z[164];
  CPG_Dual.d0[165] = ecos_workspace->z[165];
  CPG_Dual.d0[166] = ecos_workspace->z[166];
  CPG_Dual.d0[167] = ecos_workspace->z[167];
  CPG_Dual.d0[168] = ecos_workspace->z[168];
  CPG_Dual.d0[169] = ecos_workspace->z[169];
  CPG_Dual.d0[170] = ecos_workspace->z[170];
  CPG_Dual.d0[171] = ecos_workspace->z[171];
  CPG_Dual.d0[172] = ecos_workspace->z[172];
  CPG_Dual.d0[173] = ecos_workspace->z[173];
  CPG_Dual.d0[174] = ecos_workspace->z[174];
  CPG_Dual.d0[175] = ecos_workspace->z[175];
  CPG_Dual.d0[176] = ecos_workspace->z[176];
  CPG_Dual.d0[177] = ecos_workspace->z[177];
  CPG_Dual.d0[178] = ecos_workspace->z[178];
  CPG_Dual.d0[179] = ecos_workspace->z[179];
  CPG_Dual.d0[180] = ecos_workspace->z[180];
  CPG_Dual.d0[181] = ecos_workspace->z[181];
  CPG_Dual.d0[182] = ecos_workspace->z[182];
  CPG_Dual.d0[183] = ecos_workspace->z[183];
  CPG_Dual.d0[184] = ecos_workspace->z[184];
  CPG_Dual.d0[185] = ecos_workspace->z[185];
  CPG_Dual.d0[186] = ecos_workspace->z[186];
  CPG_Dual.d0[187] = ecos_workspace->z[187];
  CPG_Dual.d0[188] = ecos_workspace->z[188];
  CPG_Dual.d0[189] = ecos_workspace->z[189];
  CPG_Dual.d0[190] = ecos_workspace->z[190];
  CPG_Dual.d0[191] = ecos_workspace->z[191];
  CPG_Dual.d0[192] = ecos_workspace->z[192];
  CPG_Dual.d0[193] = ecos_workspace->z[193];
  CPG_Dual.d0[194] = ecos_workspace->z[194];
  CPG_Dual.d0[195] = ecos_workspace->z[195];
  CPG_Dual.d0[196] = ecos_workspace->z[196];
  CPG_Dual.d0[197] = ecos_workspace->z[197];
  CPG_Dual.d0[198] = ecos_workspace->z[198];
  CPG_Dual.d0[199] = ecos_workspace->z[199];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (ecos_workspace->info->pcost);
  CPG_Info.iter = ecos_workspace->info->iter;
  CPG_Info.status = ecos_flag;
  CPG_Info.pri_res = ecos_workspace->info->pres;
  CPG_Info.dua_res = ecos_workspace->info->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_c(){
  for (i=0; i<7; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
}

void cpg_copy_b(){
}

void cpg_copy_G(){
  for (i=0; i<1400; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<200; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.c) {
    cpg_canonicalize_c();
  }
  if (Canon_Outdated.G) {
    cpg_canonicalize_G();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!ecos_workspace  ) {
    cpg_copy_all();
    ecos_workspace = ECOS_setup(7, 200, 0, 200, 0, 0, 0, Canon_Params_conditioning.G->x, Canon_Params_conditioning.G->p, Canon_Params_conditioning.G->i, 0, 0, 0, Canon_Params_conditioning.c, Canon_Params_conditioning.h, 0);
  } else {
    if ( Canon_Outdated.A||Canon_Outdated.b||Canon_Outdated.G) {
      cpg_copy_all();
      ECOS_updateData(ecos_workspace, Canon_Params_conditioning.G->x, 0, Canon_Params_conditioning.c, Canon_Params_conditioning.h, 0);
    } else {
      if ( Canon_Outdated.c) {
        cpg_copy_c();
        for (i=0; i<7; i++) { ecos_updateDataEntry_c(ecos_workspace, i, Canon_Params_conditioning.c[i]); };
      }
      if ( Canon_Outdated.h) {
        cpg_copy_h();
        for (i=0; i<200; i++) { ecos_updateDataEntry_h(ecos_workspace, i, Canon_Params_conditioning.h[i]); };
      }
    }
  }
  ecos_workspace->stgs->feastol = Canon_Settings.feastol;
  ecos_workspace->stgs->abstol = Canon_Settings.abstol;
  ecos_workspace->stgs->reltol = Canon_Settings.reltol;
  ecos_workspace->stgs->feastol_inacc = Canon_Settings.feastol_inacc;
  ecos_workspace->stgs->abstol_inacc = Canon_Settings.abstol_inacc;
  ecos_workspace->stgs->reltol_inacc = Canon_Settings.reltol_inacc;
  ecos_workspace->stgs->maxit = Canon_Settings.maxit;
  // Solve with ECOS
  ecos_flag = ECOS_solve(ecos_workspace);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.c = 0;
  Canon_Outdated.G = 0;
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.feastol = 1e-8;
  Canon_Settings.abstol = 1e-8;
  Canon_Settings.reltol = 1e-8;
  Canon_Settings.feastol_inacc = 1e-4;
  Canon_Settings.abstol_inacc = 5e-5;
  Canon_Settings.reltol_inacc = 5e-5;
  Canon_Settings.maxit = 100;
}

void cpg_set_solver_feastol(cpg_float feastol_new){
  Canon_Settings.feastol = feastol_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_feastol_inacc(cpg_float feastol_inacc_new){
  Canon_Settings.feastol_inacc = feastol_inacc_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_maxit(cpg_int maxit_new){
  Canon_Settings.maxit = maxit_new;
}
