
/*
Auto-generated by CVXPYgen on August 24, 2025 at 20:38:57.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Domain(0, -2.37961266350062139452);
  cpg_update_A_mat(0, -0.67448347893922933061);
  cpg_update_b_vec(0, -0.74857319361357410603);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<7; i++) {
    printf("var2[%d] = %f\n", i, CPG_Result.prim->var2[i]);
  }

  // Print dual solution
  for(i=0; i<200; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }

  return 0;

}
