
/*
Auto-generated by CVXPYgen on August 24, 2025 at 04:13:00.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Domain(0, 2.74497231765499050127);
  cpg_update_A_mat(0, 1.44807699131253464486);
  cpg_update_b_vec(0, 0.43966674049660336987);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<7; i++) {
    printf("var2[%d] = %f\n", i, CPG_Result.prim->var2[i]);
  }

  // Print dual solution
  for(i=0; i<200; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }

  return 0;

}
